#	$Csoft: Makefile,v 1.1 2005/04/14 06:19:40 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

LIB=		space
LIB_SHARED=	Yes
LIB_STATIC=	No

SRCS=	space.c
#MAN3=	space.3

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/mk/csoft.man.mk
