TOP=	../..
include ${TOP}/Makefile.config

SUBDIR=	bitmap

TTFSRCS=ttf-bitstream-vera-1.10
TTF=	COPYRIGHT.TXT \
	README.TXT \
	RELEASENOTES.TXT \
	Vera.ttf \
	VeraBI.ttf \
	VeraBd.ttf \
	VeraIt.ttf \
	VeraMoBI.ttf \
	VeraMoBd.ttf \
	VeraMoIt.ttf \
	VeraMono.ttf \
	VeraSe.ttf \
	VeraSeBd.ttf

SHARE=	${TTF}
SHAREDIR=${TTFDIR}

include ${TOP}/mk/build.prog.mk
