#	$Csoft: Makefile,v 1.1 2004/06/26 03:42:18 vedge Exp $

TOP=	..
include ${TOP}/Makefile.config

LIB=	mat
SRCS=	mat.c lu.c vec.c veci.c gaussj.c

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
