.\"	$Csoft: button.3,v 1.15 2003/02/25 03:57:14 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 20, 2002
.Dt BUTTON 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm button
.Nd agar button widget
.Sh SYNOPSIS
.Bd -literal
#include <engine/widget/button.h>
.Ed
.Sh DESCRIPTION
The
.Nm
widget implements a simple push-button containing a string of text or
an image.
.Sh INITIALIZATION
.nr nS 1
.Ft "struct button *"
.Fn button_new "struct region *reg" "char *caption" "SDL_Surface *image" "int flags" "int rw" "int rh"
.Pp
.Ft void
.Fn button_init "struct button *button" "char *caption" "SDL_Surface *image" "int flags" "int rw" "int rh"
.nr nS 0
.Pp
The
.Fn button_new
function allocates, initializes, and attaches a
.Nm
widget.
The
.Fn button_init
function initializes a
.Nm
widget of size
.Fa rw
x
.Fa rh
displaying either a string of text if
.Fa caption
is non-null, or an image if
.Fa image
is non-null.
The
.Fa flags
can be changed at runtime, and may include:
.Pp
.Bd -literal
#define BUTTON_STICKY	0x01		/* Sticky state */
#define BUTTON_NOFOCUS	0x02		/* Don't gain focus */
.Ed
.Sh EVENTS
The
.Nm
widget reacts to the following events:
.Pp
.Bl -tag -compact -width 25n
.It window-mousebuttonup
Release the button if the cursor is inside the widget area.
.It window-mousebuttondown
Press the button.
.It window-keyup
Release the button.
.It window-keydown
Press the button.
.It window-mousemotion
Abort a button press if the cursor is moving outside the button area.
.El
.Pp
The
.Nm
widget generates the following events:
.Pp
.Bl -tag -compact -width 2n
.It Fn button-pushed "int new_state"
Button was pressed.
.El
.Sh BINDINGS
The
.Nm
widget provides the following bindings:
.Pp
.Bl -tag -compact -width "int *state"
.It Va int *state
Button state (1=pressed, 0=released)
.El
.Sh SEE ALSO
.Xr agar 3 ,
.Xr widget 3 ,
.Xr window 3 ,
.Xr region 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.0.
