.\"	$Csoft: graph.3,v 1.19 2004/01/08 02:20:10 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003, 2004 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 20, 2002
.Dt GRAPH 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm graph
.Nd agar graphic widget
.Sh SYNOPSIS
.Bd -literal
#include <engine/widget/graph.h>
.Ed
.Sh DESCRIPTION
The
.Nm
widget implements a scrollable graph display.
.Sh INITIALIZATION
.nr nS 1
.Ft "struct graph *"
.Fn graph_new "void *parent, const char *caption, enum graph_type type" \
              "int flags" "graph_val_t yrange"
.Pp
.Ft void
.Fn graph_init "struct graph *graph, const char *caption" \
               "enum graph_type type, int flags, graph_val_t yrange"
.nr nS 0
.Pp
The
.Fn graph_new
function allocates, initializes, and attaches a
.Nm
widget.
.Fn graph_init
initializes a
.Nm
widget.
.Fa caption
is a short description of the graph; it is truncated if its length
exceeds
.Dv GRAPH_CAPTION_MAX - 1
characters.
.Fa yrange
is the maximum expected value for which to adjust display.
The
.Fa type
argument is one of:
.Bd -literal
enum graph_type {
	GRAPH_POINTS,   /* Dots */
	GRAPH_LINES     /* Lines */
} type;
.Ed
.Pp
The
.Fa flags
may include:
.Bd -literal
#define GRAPH_SCROLL  0x01   /* Scroll if the end is not visible */
#define GRAPH_ORIGIN  0x02   /* Visible origin */
.Ed
.Sh PLOTTING
.nr nS 1
.Ft "struct graph_item *"
.Fn graph_add_item "struct graph *graph, const char *name" \
                   "Uint8 r, Uint8 g, Uint8 b, Uint32 limit"
.Pp
.Ft void
.Fn graph_plot "struct graph_item *item" "graph_val_t val"
.nr nS 0
.Pp
The
.Fn graph_add_item
function inserts a new item into
.Fa graph .
If the length of
.Fa name
exceeds
.Dv GRAPH_ITEM_NAME_MAX - 1
bytes, the string is truncated.
The
.Fa r ,
.Fa g ,
.Fa b
triplet composes a color to visually identify the item.
.Fa limit
is the maximum number of points (if 0, the maximum is implicitely 0xffffffff-1).
.Pp
The
.Fn graph_plot
function adds a value
.Fa val
to the graph item
.Fa item .
.Sh EVENTS
The
.Nm
widget reacts to the following events:
.Pp
.Bl -tag -compact -width "window-mousebuttondown"
.It window-mousemotion
Scroll (x motion) or change the origin position (y motion).
.It window-keydown
Key 0 moves to offset 0, left key scrolls left, right key scrolls right,
.It window-mousebuttonup
Stop moving.
.It window-mousebuttondown
Start moving.
.El
.Pp
The
.Nm
widget does not generate any event.
.Sh SEE ALSO
.Xr agar 3 ,
.Xr widget 3 ,
.Xr window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.0.
