.\"	$Csoft: textbox.3,v 1.23 2004/03/25 06:48:29 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003, 2004 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 21, 2002
.Dt TEXTBOX 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm textbox
.Nd agar text box widget
.Sh SYNOPSIS
.Bd -literal
#include <engine/widget/textbox.h>
.Ed
.Sh DESCRIPTION
The
.Nm
widget binds to a NUL-terminated string and allows the user to edit its
contents.
The string may contain Unicode characters in UTF-8 format,
.Nm
operates on UCS-4 strings internally.
.Sh INITIALIZATION
.nr nS 1
.Ft "struct textbox *"
.Fn textbox_new "void *parent" "const char *label"
.Pp
.Ft void
.Fn textbox_init "struct textbox *textbox" "const char *label"
.Pp
.Ft void
.Fn textbox_set_writeable "struct textbox *textbox" "int writeable"
.Pp
.Ft void
.Fn textbox_prescale "struct textbox *textbox" "const char *text"
.nr nS 0
.Pp
The
.Fn textbox_new
function allocates, initializes, and attaches a
.Nm
widget.
The
.Fn textbox_init
function initializes a
.Nm
widget with the label text set to
.Fa label .
.Pp
The
.Fn textbox_set_writeable
function enables/disables user edition of the string.
If
.Fa writeable
is 0, the string is read-only; if it is 1, the string may be edited (this is the
default).
.Pp
.Fn textbox_prescale
arranges for
.Fa textbox
to be large enough to display the given string.
.Sh TEXT MANIPULATION
.nr nS 1
.Ft void
.Fn textbox_printf "struct textbox *textbox" "const char *fmt" "..."
.Pp
.Ft "char *"
.Fn textbox_string "struct textbox *textbox"
.Pp
.Ft "size_t"
.Fn textbox_copy_string "struct textbox *textbox" "char *dst" "size_t dst_size"
.Pp
.Ft int
.Fn textbox_int "struct textbox *textbox"
.nr nS 0
.Pp
The
.Fn textbox_printf
function uses
.Xr vsnprintf 3
to overwrite the contents of the text buffer.
If the
.Fa fmt
argument is NULL, a NUL string is assigned instead.
.Pp
The
.Fn textbox_string
function returns a copy of the text buffer.
.Pp
The
.Fn textbox_copy_string
function copies up to
.Fa dst_size
- 1 bytes from the text buffer
.Fa dst ,
NUL-terminating the result and returning the number of bytes that would
have been copied if
.Fa dst_size
was unlimited.
.Pp
.Fn textbox_int
tries to convert the string to an integer value.
.Sh BINDINGS
The
.Nm
widget provides the following bindings:
.Pp
.Bl -tag -compact -width "char *string "
.It Va char *string
Fixed-size buffer of UTF-8 text.
.El
.Sh EVENTS
The
.Nm
widget reacts to the following events:
.Pp
.Bl -tag -compact -width 25n
.It window-mousebuttondown
Move focus to the widget.
Position the cursor at a specific position.
.It window-mousemotion
Move the cursor and scroll.
.It window-keydown
Perform the action that the current keymap associates with this key.
.El
.Pp
The
.Nm
widget generates the following events:
.Pp
.Bl -tag -width 2n
.It Fn textbox-return "void"
Return was pressed.
.It Fn textbox-prechg "void"
The string is about to be modified.
.It Fn textbox-postchg "void"
The string was just modified.
.El
.Sh SEE ALSO
.Xr agar 3 ,
.Xr widget 3 ,
.Xr window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.0.
.Sh BUGS
.Fn textbox_int
will be obsoleted by integral type bindings.
.Pp
UTF-8 string boundary check is not space efficient.
