.\"	$Csoft$
.\"
.\" Copyright (c) 2002 CubeSoft Communications, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistribution of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistribution in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of CubeSoft Communications, nor the names of its
.\"    contributors may be used to endorse or promote products derived from
.\"    this software without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\"	$OpenBSD: mdoc.template,v 1.6 2001/02/03 08:22:44 niklas Exp $
.\"
.Dd JANUARY 30, 2002
.Dt TEXT 3
.Os
.Sh NAME
.Nm text
.Nd AGAR font engine
.Sh SYNOPSIS
.Fd #include <engine/text/text.h>
.Sh DESCRIPTION
The
.Nm
module renders overlapping text dialogs over a maskable surface,
such as a map view.
Those dialogs are controlled by real time or input devices
.El
.Sh INITIALIZATION
.nr nS 1
.Ft "int"
.Fn text_init "void"
.Pp
.Ft "void"
.Fn text_quit "void"
.Pp
.Ft "struct text *"
.Fn text_create "Uint32 x" "Uint32 y" "Uint32 w" "Uint32 h" "Uint32 flags" "Uint32 sleepms"
.Pp
.nr nS 0
.Pp
.Fn text_init initializes the font engine.
.Fn text_quit deallocate all font engine resources.
.Fn text_create creates a new text dialog structure of a fixed size.
.Fn text_destroy frees an unlinked text dialog structure.
.Pp
.nr nS 1
.Ft "void"
.Fn char_setspeed "struct character *ch" "Uint32 speed"
.Pp
.Ft "void"
.Fn char_add "struct character *ch" "struct map *map" "int x" "int y" 
.Pp
.Ft "void"
.Fn char_canmove "struct character *ch" "int nx" "int ny"
.Pp
.Ft "void"
.Fn char_move "struct character *ch" "int nx" "int ny"
.Pp
.Ft "void"
.Fn char_del "struct character *ch" "struct map *map" "int x" "int y" 
.Pp
.Ft "void"
.Fn char_setsprite "struct character *ch" "int soffs"
.Pp
.Ft "void"
.Fn char_setanim "struct character *ch" "int aoffs"
.Pp
.nr nS 0
.Pp
.Fn char_setspeed
readjusts the character's timer.
The
.Fa speed
argument should be something between 0 and the character's maxspeed.
The display's refresh rate will be added to this interval.
.Pp
.Fn char_add
positions the character
.Fa ch
on
.Fa map
at the given coordinates, and
.Fn char_del
removes any reference to
.Fa ch
at the given coordinates.
.Fn char_canmove
returns 0 if the character is able to move to new coordinates
on the current map.
.Fn char_move
moves the character
.Fa ch
to new coordinates on the current map.
.Fn char_setsprite
sets the active sprite, and
.Fn char_setanim
sets the active animation.
.Sh SEE ALSO
.Xr agar 3
