.\"	$Csoft: window.3,v 1.18 2003/01/01 05:18:42 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 21, 2002
.Dt WINDOW 3
.Os
.Sh NAME
.Nm window
.Nd agar window structure
.Sh SYNOPSIS
.Bd -literal
#include <engine/widget/widget.h>
#include <engine/widget/window.h>
.Ed
.Sh DESCRIPTION
The
.Nm
structure implements a mobile, resizable window.
.Sh INITIALIZATION
.nr nS 1
.Ft "struct window *"
.Fn window_new "char *name" "int flags" "int x" "int y" "int w" "int h" "int minwidth, int minheight"
.Pp
.Ft "struct window *"
.Fn window_generic_new "int w" "int h" "const char *name" "..."
.Pp
.Ft void
.Fn window_init "struct window *win" "char *name" "int flags" "int x" "int y" "int w" "int h, int minwidth, int minheight"
.Pp
.Ft void
.Fn window_destroy "struct window *win"
.Pp
.Ft void
.Fn window_set_caption "struct window *win" "const char *fmt" "..."
.Pp
.Ft void
.Fn window_attach "struct window *parent" "struct region *child"
.Pp
.Ft void
.Fn window_detach "struct window *parent" "struct region *child"
.nr nS 0
.Pp
The
.Fn window_new
function allocates, initializes, and attaches a
.Nm
structure.
.Pp
The
.Fn window_generic_new
function allocates, initializes and attaches a centered
.Nm
with a minimum and default geometry of
.Fa w
by
.Fa h
pixels.
If
.Fa name
is non-NULL, it specifies the name of the window (implying the
.Dv WINDOW_SAVE_POSITION
flag) and causes the function to return NULL if such a window exists.
.Pp
The
.Fn window_init
function initializes a
.Nm
structure.
The
.Fa name
argument points to a null-terminated string to identify the window, if it is
unique (so the window coordinates and geometry can be saved to disk), or
.Dv NULL
if more than one instance of this window will be created.
The
.Fa x
and
.Fa y
arguments define the initial absolute position of the window in pixels,
and are ignored with the
.Dv WINDOW_CENTER
flag.
The
.Fa w
and
.Fa h
arguments define the default window geometry in pixels (or in percentiles
of the total view size with the
.Dv WINDOW_SCALE
flag).
.Pp
The
.Fa flags
may be modified at run time (assuming the
.Nm
is locked), and may include:
.Pp
.Bd -literal
#define WINDOW_TITLEBAR		0x01	/* Draw a title bar */
#define WINDOW_SCALE		0x02	/* Scale the initial geometry (%) */
#define WINDOW_CENTER		0x04	/* Center the initial position */
#define WINDOW_SHOWN		0x10	/* Window is visible */
#define WINDOW_SAVE_POSITION	0x20	/* Save position/geometry on close */
#define WINDOW_HIDDEN_BODY	0x40	/* Draw the titlebar only */
#define WINDOW_PERSISTENT	WINDOW_HIDDEN_BODY
.Ed
.Pp
The
.Fn window_destroy
function frees resources allocated by a window, assuming it is no longer
attached to a view.
.Pp
The
.Fn window_attach
function attaches the region
.Fa region
to the window
.Fa parent .
The
.Fn window_detach
function detaches the region
.Fa region
from the window
.Fa parent .
.Pp
The
.Fn window_set_caption
function sets the text shown inside the window titlebar, which is initially
set to
.Sq Untitled .
.Sh VISIBILITY
.nr nS 1
.Ft int
.Fn window_show "struct window *win"
.Pp
.Ft int
.Fn window_hide "struct window *win"
.Pp
.Ft void
.Fn window_resize "struct window *win"
.nr nS 0
.Pp
The
.Fn window_show
and
.Fn window_hide
functions control the visibility of a window, returning 1 if the window was
previously visible, otherwise 0.
.Pp
The
.Fn window_resize
function effects a change in window geometry by updating the regions
and widgets inside the window
.Fa win .
The window structure
.Fa win
must be locked when
.Fn window_resize
is called.
.Sh RENDERING
.nr nS 1
.Ft void
.Fn window_draw "struct window *win"
.nr nS 0
.Pp
The
.Fn window_draw
function draws the window
.Fa win
to video memory.
The
.Fa win
structure must be locked when
.Fn window_draw
is called.
.Sh EVENT DISPATCHING
.nr nS 1
.Ft int
.Fn window_event "SDL_Event *ev"
.nr nS 0
.Pp
The
.Fn window_event
function translates the
.Xr SDL_Event 3
pointed to by the
.Fa ev
argument and dispatches appropriate events to relevant widgets.
The view structure must be locked, and the window list must not be
empty when
.Fn window_event
is called.
.Sh GENERIC EVENT HANDLERS
.nr nS 1
.Ft void
.Fn window_generic_detach "int argc" "union evarg *argv"
.Pp
.Ft void
.Fn window_generic_hide "int argc" "union evarg *argv"
.nr nS 0
.Pp
The
.Fn window_generic_detach
event handler detaches the window given as the first argument, freeing all
associated resources.
.Fn window_generic_detach
is registered as the
.Sq window-close
event handler for windows created with
.Fn window_generic_new .
The
.Fn window_generic_hide
function hides the window given as the first argument, if it is currently
visible.
.Sh EVENTS
The
.Nm
object reacts directly to events of type
.Xr SDL_Event 3 ,
translates, and dispatches them to relevant
.Xr widget 3
structures.
.Pp
The
.Nm
object delivers the following events to
.Xr widget 3
objects:
.Pp
.Bl -tag -width 2n
.It Fn window-gainfocus "void"
Window gained focus.
.It Fn window-lostfocus "void"
Window no longer focused.
.It Fn window-mousemotion "int x" "int y" "int xrel" "int yrel"
The mouse cursor has moved to widget-relative coordinates
.Fa x
and
.Fa y
(which may be negative).
The
.Fa xrel
and
.Fa yrel
arguments represent the displacement relative to the last position of the
mouse cursor.
Regardless of the mouse position, this event is posted to widgets that either
hold focus inside the focused window, or have the
.Dv WIDGET_UNFOCUSED_MOTION
flag set.
.It Fn window-mousebuttonup "int button" "int x" "int y"
The mouse button indexed by
.Fa button
was released at widget-relative
.Fa x ,
.Fa y
coordinates.
Regarldess of the mouse position, this event is posted to the widget that
holds focus inside the focused window.
.It Fn window-mousebuttondown "int button" "int x" "int y"
The mouse button indexed by
.Fa button
was pressed at widget-relative
.Fa x ,
.Fa y
coordinates, which must be inside the widget area.
.It Fn window-keyup "int keysym" "int keymod"
The key identified by
.Fa keysym
was released, and the widget holds the focus.
.It Fn window-keydown "int keysym" "int keymod"
The key identified by
.Fa keysym
was pressed, and the widget holds the focus.
.It Fn window-close "void"
The window's titlebar close button was pressed.
This event is generated after the window is no longer visible.
.El
.Sh SEE ALSO
.Xr agar 3 ,
.Xr widget 3 ,
.Xr region 3
.Sh HISTORY
The
.Nm
system first appeared in AGAR 1.0.
