#	$Csoft: Makefile,v 1.1 2002/12/01 14:41:05 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

LIB=	media
SRCS=	art.c xcf.c
OBJS=	art.o xcf.o

CFLAGS+=	${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
