TOP=	../..
include ${TOP}/Makefile.config

LIB=		ag_unicode
LIB_SHARED=	Yes
LIB_STATIC=	No

SRCS=	unicode.c ucslcpy.c ucslcat.c ucssep.c

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/build.lib.mk
include ${TOP}/mk/build.man.mk
