TOP=	..
include ${TOP}/Makefile.config

PROG=		agar-net-config
PROG_TYPE=	"CLI"
PROG_GUID=	"d5dd9022-5d93-4ab6-bda6-ac03ab256fa8"

SRCS=	agar-net-config.c
CFLAGS+=-I..

include ${TOP}/mk/build.prog.mk
