TOP=	../..
include ${TOP}/Makefile.config

SHAREDIR=	${TTFDIR}
SHARESRC=	minimal.xcf \
		serif.xcf \
		Vera-Copyright.txt \
		Vera-README.txt \
		Vera-ReleaseNotes.txt \
		Vera.ttf \
		VeraBI.ttf \
		VeraBd.ttf \
		VeraIt.ttf \
		VeraMoBI.ttf \
		VeraMoBd.ttf \
		VeraMoIt.ttf \
		VeraMono.ttf \
		VeraSe.ttf \
		VeraSeBd.ttf

include ${TOP}/mk/build.prog.mk
