#	$Csoft: Makefile,v 1.6 2005/03/20 06:42:30 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

XCF=	map-edition.xcf \
	map-cursors.xcf \
	object-editor.xcf \
	objects.xcf \
	vg.xcf \
	vg-snap.xcf \
	eda.xcf \
	rg.xcf \
	anim.xcf \
	symbols.xcf

DEN=		icons.den
DEN_DIR=	engine/icons
DEN_NAME=	"Agar GUI icons"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2001, 2002, 2003, 2004, 2005 CubeSoft Communications, Inc"

DENCOMP=${TOP}/dencomp/dencomp
include ${TOP}/mk/csoft.den.mk
