TOP=	../..
include ../Makefile.config

XGETTEXT_FLAGS=	--no-location --from-code=UTF-8

SRC=	..
DOMAIN= agarpaint
POS=	fr.po
MOS=	fr.mo

ENABLE_NLS=yes
HAVE_GETTEXT=yes

include ${TOP}/mk/build.po.mk
