#!/bin/sh

PROGRAM_NAME="sd-configpkg"

. ${SYSDEP_BASE_DIRECTORY}/sysdep-subs || exit 1

debug()
{
  SYSDEP_DEBUG "${PROGRAM_NAME}: $1"
}

if [ $# -ne 2 ]
then
  ${SYSDEP_UTIL_ECHO} "${PROGRAM_NAME}: usage: pkg flags"
  ${SYSDEP_UTIL_EXIT} 1
fi

PACKAGE_NAME="$1"
CONFIG_FLAGS="$2"

#
# Search in each element of ${PATH} and execute pkg-config binary using
# absolute path.
#

for PATH_ELEMENT in ${SYSDEP_STDBIN}
do
  if [ ! -x ${PATH_ELEMENT}/pkg-config ]
  then
    debug "${PATH_ELEMENT}/pkg-config not executable or nonexistent"
  else
    debug "executing ${PATH_ELEMENT}/pkg-config ${CONFIG_FLAGS}"
    ${PATH_ELEMENT}/pkg-config ${PACKAGE_NAME} ${CONFIG_FLAGS} 2>/dev/null
    RETURN_CODE=$?
    if [ ${RETURN_CODE} -eq 0 ]
    then
      debug "execution successful"
    else
      debug "execution failed"
    fi
    ${SYSDEP_UTIL_EXIT} ${RETURN_CODE}
  fi
done

debug "could not locate or execute pkg-config"
${SYSDEP_UTIL_EXIT} 1
