TOP=	..
include ${TOP}/Makefile.config

PROG=		agar-core-config
PROG_TYPE=	"CLI"
PROG_GUID=	"78a4d875-2e6c-4a81-98a1-2f8241c72654"

SRCS=	agar-core-config.c
CFLAGS+=-I..

include ${TOP}/mk/build.prog.mk
