TOP=	..
include ${TOP}/Makefile.config

PROG=		agar-math-config
PROG_TYPE=	"CLI"
PROG_GUID=	"fb9d278f-50c6-49bb-98fb-631b55c2790f"

SRCS=	agar-math-config.c
CFLAGS+=-I..

include ${TOP}/mk/build.prog.mk
