# $Csoft: Makefile,v 1.1 2004/01/08 02:19:47 vedge Exp $

TOP=	../..

DOC=		agar-manual.ps
MACROS=		-mdoc
DOCSRC=		Cover.tr \
		Macros.tr \
		Manual.tr \
		Contents.tr

include ${TOP}/mk/csoft.doc.mk
