.\"	$OpenBSD$
.\"
.\" Copyright (c) 2002 CubeSoft Communications, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistribution of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Neither the name of CubeSoft Communications, nor the names of its
.\"    contributors may be used to endorse or promote products derived from
.\"    this software without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 21, 2002
.Dt REGION 3
.Os
.Sh NAME
.Nm region
.Nd agar widget container
.Sh SYNOPSIS
.Bd -literal
#include <engine/widget/widget.h>
#include <engine/widget/window.h>
.Ed
.Sh DESCRIPTION
The
.Nm
structure is a simple container for widgets.
.Xr window 3
objects may contain a list of
.Nm
structures, and
.Nm
structures may contain a list of
.Xr widget 3
structures.
.Sh INITIALIZATION
.nr nS 1
.Ft struct region *
.Fn region_new "struct window *parent" "int flags" "int rx" "int ry" "int rw" "int rh"
.Pp
.Ft void
.Fn region_init "struct region *region" "int flags" "int rx" "int ry" "int rw" "int rh"
.Pp
.Ft void
.Fn region_attach "struct region *parent" "struct widget *child"
.Pp
.Ft void
.Fn region_detach "struct region *parent" "struct widget *child"
.Pp
.nr nS 0
.Pp
The
.Fn region_new
function allocates, initializes, and attaches a
.Nm
structure.
The
.Fn region_init
function initializes a
.Nm
structure.
The
.Fa rx ,
.Fa ry ,
.Fa rw
and
.Fa rh
arguments are percentiles of the window space, or fixed coordinates if
negative.
The region takes all remaining space if coordinates are zero.
The
.Fa flags
can be changed at runtime, and may include:
.Pp
.Bd -literal
#define REGION_HALIGN	0x01	/* Align widgets horizontally */
#define REGION_VALIGN	0x02	/* Align widgets vertically */
#define REGION_LEFT	0x04	/* Left/top justify widgets */
#define REGION_CENTER	0x08	/* Center widgets */
#define REGION_RIGHT	0x10	/* Right/down justify widgets */
#define REGION_BORDER	0x20	/* Draw region decorations */
.Ed
.Pp
.Sh EVENTS
The
.Nm
structure generates the following events:
.Pp
.Bl -tag -width 10n -compact
.It attached
Widget attached to region.
.It detached
Widget detached from region.
.El
.Sh SEE ALSO
.Xr agar 3 ,
.Xr widget 3
.Sh HISTORY
The
.Nm
widget first appeared in AGAR 1.0.
