.\"	$Csoft: region.3,v 1.8 2003/02/02 21:16:15 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 21, 2002
.Dt REGION 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm region
.Nd agar widget container
.Sh SYNOPSIS
.Bd -literal
#include <engine/widget/window.h>
.Ed
.Sh DESCRIPTION
The
.Nm
structure is a simple container for widgets.
.Xr window 3
objects may contain a list of
.Nm
structures, and
.Nm
structures may contain a list of
.Xr widget 3
structures.
.Sh INITIALIZATION
.nr nS 1
.Ft struct region *
.Fn region_new "struct window *parent" "int flags" "int rx" \
               "int ry" "int rw" "int rh"
.Pp
.Ft void
.Fn region_init "struct region *region" "int flags" "int rx" \
                "int ry" "int rw" "int rh"
.Pp
.Ft void
.Fn region_attach "struct region *parent" "struct widget *child"
.Pp
.Ft void
.Fn region_detach "struct region *parent" "struct widget *child"
.Pp
.nr nS 0
.Pp
The
.Fn region_new
function allocates, initializes, and attaches a
.Nm
structure.
The
.Fn region_init
function initializes a
.Nm
structure.
The
.Fa rx
and
.Fa ry
arguments define the position of the region inside the window, and have the
following meanings:
.Pp
.Bl -tag -compact -width ">= 0"
.It >= 0
A value in % scaled to the window size.
.It -1
With
.Dv REGION_HALIGN ,
position at the left of the last region.
With
.Dv REGION_VALIGN ,
position at the bottom of the last region.
.El
.Pp
The
.Fa rw
and
.Fa rh
arguments define the size of the region, and have the following meanings:
.Pp
.Bl -tag -compact -width ">= 0"
.It > 0
A value in % scaled to the view size.
.It 0
With
.Dv REGION_HALIGN ,
all remaining space at the right of the last region.
With
.Dv REGION_VALIGN ,
all remaining space at the bottom the last region.
.El
.Pp
The
.Fa flags
may include:
.Pp
.Bd -literal
#define REGION_HALIGN	0x01	/* Align widgets horizontally */
#define REGION_VALIGN	0x02	/* Align widgets vertically */
#define REGION_CLIPPING	0x04	/* Set the clipping rectangle to the region
			 	   area before drawing */
.Ed
.Pp
.Sh EVENTS
The
.Nm
structure generates the following events:
.Pp
.Bl -tag -width 2n
.It Fn attached "struct region *parent"
Widget attached to region
.Fa parent .
.It Fn detached "struct region *parent"
Widget detached from region
.Fa parent .
.El
.Sh SEE ALSO
.Xr agar 3 ,
.Xr view 3 ,
.Xr widget 3 ,
.Xr window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.0.
