.\"	$Csoft: tlist.3,v 1.46 2005/05/11 09:59:33 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003, 2004, 2005 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 20, 2002
.Dt TLIST 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm tlist
.Nd agar tree/list widget
.Sh SYNOPSIS
.Bd -literal
#include <engine/widget/tlist.h>
.Ed
.Sh DESCRIPTION
The
.Nm
widget implements a dynamic, scrollable list of items.
Individual items are typically associated with user-supplied pointers.
Single or multiple selections of items are possible.
.Sh INHERITANCE HIERARCHY
.Pp
.Xr object 3 ->
.Xr widget 3 ->
.Nm .
.Sh INITIALIZATION
.nr nS 1
.Ft "struct tlist *"
.Fn tlist_new "void *parent" "int flags"
.Pp
.Ft void
.Fn tlist_init "struct tlist *tlist" "int flags"
.Pp
.Ft void
.Fn tlist_set_item_height "struct tlist *tl" "int item_height"
.Pp
.Ft void
.Fn tlist_set_icon "struct tlist *tl, struct tlist_item *item" "SDL_Surface *icon"
.Pp
.Ft void
.Fn tlist_prescale "struct tlist *tl" "const char *text" "int nitems"
.nr nS 0
.Pp
The
.Fn tlist_new
function allocates, initializes, and attaches a
.Nm
widget.
.Fn tlist_init
initializes a
.Nm
widget.
The
.Fa flags
may include:
.Pp
.Bd -literal
#define TLIST_MULTI		0x01  /* Ctrl/shift multiple selections */
#define TLIST_MULTITOGGLE	0x02  /* Multiple toggle selections */
#define TLIST_POLL		0x04  /* Generate tlist-poll events */
#define TLIST_TREE		0x10  /* Arrange the items in a tree */
.Ed
.Pp
If the
.Dv TLIST_MULTI
flag is set, selecting an item while holding the
.Dv KMOD_CTRL
key will not cause other currently selected item
to be deselected.
If the flag
.Dv TLIST_MULTITOGGLE
is set in addition to
.Dv TLIST_MULTI ,
this behavior is achieved without having to hold
.Dv KMOD_CTRL .
.Pp
The
.Dv TLIST_POLL
flag causes the posting of a
.Sq tlist-poll
event every time the widget is redrawn.
Typically, the
.Sq tlist-poll
event handler clears the list with
.Fn tlist_clear_items ,
inserts the items with
.Fn tlist_insert
and restores the previous selections using
.Fn tlist_restore_selections .
.Pp
The
.Dv TLIST_TREE
option indicates that a tree is to be displayed.
.Pp
The
.Fn tlist_set_item_height
function sets the height of all items to
.Fa item_height
pixels .
.Pp
The
.Fn tlist_set_icon
function updates the icon shown with
.Fa item ,
scaled to
.Fa w
by
.Fa h
pixels.
.Pp
.Fn tlist_prescale
requests sufficient height to display
.Fa nitems
items at once, and sufficient width to display an item containing
.Fa text .
.Sh MANIPULATING ITEMS
.nr nS 1
.Ft "struct tlist_item *"
.Fn tlist_insert "struct tlist *tl" "SDL_Surface *iconsrc" "const char *format" "..."
.Pp
.Ft "struct tlist_item *"
.Fn tlist_insert_item "struct tlist *tlist, SDL_Surface *iconsrc" "const char *text" "const void *p1"
.Pp
.Fn tlist_insert_item_head "struct tlist *tlist, SDL_Surface *iconsrc" "const char *text" "const void *p1"
.Pp
.Ft "void"
.Fn tlist_remove_item "struct tlist *tlist" "struct tlist_item *item"
.Pp
.Ft "void"
.Fn tlist_clear_items "struct tlist *tlist"
.Pp
.Ft "void"
.Fn tlist_restore_selections "struct tlist *tlist"
.Pp
.Ft "void"
.Fn tlist_select "struct tlist *tlist" "struct tlist_item *item"
.Pp
.Ft "void"
.Fn tlist_select_all "struct tlist *tlist"
.Pp
.Ft "void"
.Fn tlist_unselect "struct tlist *tlist" "struct tlist_item *item"
.Pp
.Ft "void"
.Fn tlist_unselect_all "struct tlist *tlist"
.Pp
.Ft "struct tlist_item *"
.Fn tlist_select_pointer "struct tlist *tlist" "void *ptr"
.Pp
.Ft "struct tlist_item *"
.Fn tlist_select_text "struct tlist *tlist" "const char *text"
.Pp
.Ft "struct tlist_item *"
.Fn tlist_find_index "struct tlist *tlist" "int index"
.Pp
.Ft "struct tlist_item *"
.Fn tlist_selected_item "struct tlist *tlist"
.Pp
.Ft "int"
.Fn tlist_find_pointer "struct tlist *tlist" "void **p"
.Pp
.Ft "struct tlist_item *"
.Fn tlist_find_text "struct tlist *tlist" "const char *text"
.Pp
.Ft "struct tlist_item *"
.Fn tlist_first_item "struct tlist *tlist"
.Pp
.Ft "struct tlist_item *"
.Fn tlist_item_last "struct tlist *tlist"
.nr nS 0
.Pp
The
.Fn tlist_insert
function (and its alternate interface
.Fn tlist_insert_item )
are used to insert a new item in the list.
.Pp
The
.Fa text
argument defines the text label to display.
Unless it is NULL,
.Fa icon
defines the icon to display at the left of the label.
.Pp
The
.Fa p1
argument is a user-defined pointer associated with the item.
.Pp
The
.Fn tlist_insert_item_head
varient inserts the item at the head of the list instead of the tail.
.Pp
The
.Fn tlist_remove_item
function detaches and frees
.Fa item
from its parent
.Nm tlist .
.Pp
The
.Fn tlist_clear_items
function removes all items attached to
.Fa tlist ,
but remembers the selected items.
.Fn tlist_restore_selections
compares each item against the previous selections and restores
the
.Va selected
flag accordingly.
.Pp
The
.Fn tlist_select
and
.Fn tlist_unselect
functions manipulate the selected flag on
.Fa item .
Unless the
.Dv TLIST_MULTI
flag is set,
.Fn tlist_select
clears the selection flag on all other items.
The
.Fn tlist_select_all
and
.Fn tlist_unselect_all
functions sets/unsets the selection on all items attached to
.Fa tlist .
.Pp
The
.Fn tlist_select_pointer
function selects and returns the first item with a user pointer value
matching
.Fa ptr .
Similarly,
.Fn tlist_select_text
selects and returns the first item with a text field equal to
.Fa text .
Both of these functions invoke
.Sq tlist-poll
if the
.Dv TLIST_POLL
option is set.
.Pp
The
.Fn tlist_find_index
function returns the item at
.Fa index ,
or NULL if there is no such item.
The
.Fn tlist_selected_item
function returns the first selected item, or
.Dv NULL
if there are none.
.Fn tlist_find_pointer
is a variant that copies the user pointer associated with the first
selected item into
.Fa p ,
returning 0 on success or -1 if there is no item selected.
The
.Fn tlist_find_text
function searches
.Fa tlist
for an item containing the
.Fa text
string and returns NULL if there is no such item.
.Pp
The
.Fn tlist_first_item
and
.Fn tlist_last_item
functions return the first and last items on the list.
.Pp
The caller must ensure that the
.Nm
is locked prior to invoking
.Fn tlist_find_index ,
.Fn tlist_selected_item ,
.Fn tlist_find_pointer ,
.Fn tlist_find_text ,
.Fn tlist_first_item
or
.Fn tlist_last_item .
.Sh EVENTS
The
.Nm
widget reacts to the following events:
.Pp
.Bl -tag -compact -width 25n
.It window-mousemotion
Scroll if a mouse button is pressed.
.It window-mousebuttondown
Select an item.
.It window-keydown
Up/down changes a single selection.
Pageup/pagedown scrolls 4 items.
.El
.Pp
The
.Nm
widget generates the following events:
.Pp
.Bl -tag -compact -width 2n
.It Fn tlist-changed "struct tlist_item *item" "int state"
.Fa item
was selected or unselected.
.It Fn tlist-selected "struct tlist_item *item"
.Fa item
was selected.
.It Fn tlist-dblclick "struct tlist_item *item"
The user just double-clicked
.Fa item .
.It Fn tlist-poll "void"
The
.Dv TLIST_POLL
flag is set and the widget is about to be drawn or an event is being
processed.
.El
.Sh BINDINGS
The
.Nm
widget provides the following bindings:
.Pp
.Bl -tag -compact -width "void *selected "
.It Va void *selected
The
.Va p1
(user pointer) value of the selected item, or NULL if there is no selection.
The value of this binding is undefined if the
.Dv TLIST_MULTI
or
.Dv TLIST_MULTITOGGLE
flags are in use.
.El
.Sh TROUBLETONS
A horizontal scrollbar should display when there are labels exceeding the
.Nm
width.
.Pp
Polled mode handling is inefficient since selections must be saved and restored
each polling cycle.
.Pp
.Dv TLIST_TREE
is a cheap and bletcherous hack.
.Pp
The
.Fn tlist_insert_item
function should probably be renamed
.Fn tlist_insert
and take a
.Xr printf 3
format string.
.Pp
It is possible to generate a double click by quickly clicking on two different
items; comparing with the previously clicked item is not an option since it
may have been destroyed.
.Sh EFFICIENCY
Item insertion and removal are O(1) operations.
For n items, lookup and mouse selection handling is O(n), which becomes
significant when viewing the bottom of lists with large n.
.Pp
For polled lists where the item list is rebuilt very frequently, it would
be much more efficient to store the items in an array, at the cost of O(n)
removal.
This would also allow O(1) handling of mouse selections since all items have
the same height.
.Pp
The allocation of items also incur significant overhead with polled lists.
.Sh SEE ALSO
.Xr agar 3 ,
.Xr widget 3 ,
.Xr window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.0.
