#!/bin/sh
#
# Generate MYPROJECT_SVN_REVISION if sources are from svn and svn exists.
# Otherwise, fail gracefully and return a revision number of "0".
#

TOP=$1
DEFN=$2
if [ "${TOP}" = "" -o "${DEFN}" = "" ]; then
	echo "Usage: gen-revision.sh [top-dir] [define]"
	exit 1
fi

echo "/* Generated by gen-revision.sh */"
echo "#ifndef $DEFN"

if [ -e "${TOP}/.svn" ]; then
	IFS=":"
	SVN=""
	for path in $PATH; do
		if [ -x "${path}/svn" ]; then
			SVN="${path}/svn"
			break
		elif [ -x "${path}/svn.exe" ]; then
			SVN="${path}/svn.exe"
			break
		fi
	done
	if [ "${SVN}" != "" ]; then
		SVN_REV=`${SVN} info --show-item revision`
		if [ "$?" == "0" ]; then
			echo "#define $DEFN $SVN_REV"
		else
			echo '/* svn info failed */'
			echo "#define $DEFN 0"
		fi
	else
		echo '/* svn not found */'
		echo "#define $DEFN 0"
	fi
else
	echo '/* sources not from svn */'
	echo "#define $DEFN 0"
fi
echo '#endif'
