#	$Csoft: Makefile,v 1.3 2003/07/28 04:37:01 vedge Exp $

TOP=	..
include ${TOP}/Makefile.config

LIB=	intl
SRCS=	gettext.c
OBJS=	gettext.o

MAN3=	gettext.3
CATMAN3=gettext.cat3
PSMAN3=	gettext.ps3

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/mk/csoft.man.mk
