TOP=	../..
include ${TOP}/Makefile.config

DATADIR=	${TTFDIR}
DATAFILES_SRC=	OFL11.txt OFL-FAQ.txt \
		Charter-LICENSE.txt \
		Vera-Copyright.txt \
		League-Gothic-LICENSE.md \
		League-Spartan-LICENSE.md \
		Mukta-OFL.txt \
		agar-minimal.agbf \
		agar-minimal-12.png \
		agar-ideograms.agbf \
		agar-ideograms-12.png \
		algue.ttf \
		algue-bold.ttf \
		algue-italic.ttf \
		algue-bold-italic.ttf \
		charter-bold-italic.otf \
		charter-bold.otf \
		charter-italic.otf \
		charter.otf \
		fraktur-LICENSE.txt \
		fraktur.ttf \
		league-gothic.otf \
		league-gothic-italic.otf \
		league-gothic-condensed.otf \
		league-gothic-condensed-italic.otf \
		league-spartan.otf \
		league-spartan-black.otf \
		league-spartan-bold.otf \
		league-spartan-extrabold.otf \
		league-spartan-extralight.otf \
		league-spartan-light.otf \
		league-spartan-semibold.otf \
		monoalgue.ttf \
		monoalgue-bold.ttf \
		monoalgue-italic.ttf \
		monoalgue-bold-italic.ttf \
		unialgue.ttf

include ${TOP}/mk/build.prog.mk
