#	$Csoft: Makefile,v 1.65 2004/03/30 15:50:44 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

XCF=		window.xcf

DEN=		pixmaps.den
DEN_DIR=	engine/widget
DEN_NAME=	"Agar widget pixmaps"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2003, 2004 CubeSoft Communications, Inc."

DENCOMP=${TOP}/dencomp/dencomp
include ${TOP}/mk/csoft.den.mk
