.\"	$Csoft: agar.3,v 1.39 2004/02/20 04:20:33 vedge Exp $
.\"
.\" Copyright (c) 2001, 2002, 2003 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\"	$OpenBSD: mdoc.template,v 1.6 2001/02/03 08:22:44 niklas Exp $
.\"
.Dd NOVEMBER 26, 2001
.Dt AGAR 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm agar
.Nd graphical C application framework
.Sh DESCRIPTION
.Nm
is a high-level, cross-platform C application framework aimed primarly at
graphical games and simulations.
.Sh OBJECT DESIGN
.Nm
applications are built around a tree of
.Xr object 3
structures whose state is persistent.
.Pp
For instance, in a game, the initial hierarchy of objects is created by
level designers and their state is saved to files which are distributed with
the game binary (which is essentially an interpreter).
As the game progresses, the player modifies the objects and the world remains
persistent.
.Sh INCLUDE FILES
The
.Pa Aq compat/*.h
and
.Pa Aq config/*.h
includes should come first, followed by
.Pa Aq engine/engine.h ,
which itself includes:
.Pp
.Bl -tag -width "<engine/loader/integral.h> " -compact
.It Pa Aq pthread.h
POSIX threads, if available.
.It Pa Aq SDL.h
Software DirectMedia Layer.
.It Pa Aq GL/GL.h
OpenGL interface, if available.
.It Pa Aq compat/queue.h
4.4BSD
.Xr queue 3
definitions.
.It Pa Aq compat/strlcpy.h
For
.Xr strlcpy 3 .
.It Pa Aq compat/strlcat.h
For
.Xr strlcat 3 .
.It Pa Aq compat/snprintf.h
For
.Xr snprintf 3 .
.It Pa Aq compat/vsnprintf.h
For
.Xr vsnprintf 3 .
.It Pa Aq compat/vasprintf.h
For
.Xr vasprintf 3 .
.It Pa Aq compat/asprintf.h
For
.Xr asprintf 3 .
.It Pa Aq compat/strsep.h
For
.Xr strsep 3 .
.It Pa Aq engine/loader/netbuf.h
For the
.Ft struct netbuf
definition, required by load/save function prototypes.
.It Pa Aq engine/loader/integral.h
For saving integers.
.It Pa Aq engine/loader/real.h
For saving real numbers.
.It Pa Aq engine/loader/string.h
For saving text.
.It Pa Aq engine/loader/version.h
For versioning.
.It Pa Aq engine/error/error.h
Generic error handling.
.It Pa Aq engine/object.h
Generic
.Xr object 3
types and operations.
.It Pa Aq engine/event.h
For the
.Ft union evarg
definition and generic
.Xr event 3
handling.
.El
.Sh SEE ALSO
.Xr event 3 ,
.Xr map 3 ,
.Xr mapedit 3 ,
.Xr object 3 ,
.Xr perso 3 ,
.Xr position 3 ,
.Xr prop 3 ,
.Xr rootmap 3 ,
.Xr version 3 ,
.Xr view 3 ,
.Xr widget 3 ,
.Xr window 3
.Pp
.Bd -literal
http://www.libsdl.org/
http://www.opengl.org/
.Ed
