.\"	$Csoft: engine.3,v 1.6 2005/06/18 04:25:18 vedge Exp $
.\"
.\" Copyright (c) 2001, 2002, 2003, 2005 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\"	$OpenBSD: mdoc.template,v 1.6 2001/02/03 08:22:44 niklas Exp $
.\"
.Dd NOVEMBER 26, 2001
.Dt AGAR 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm engine
.Nd agar engine initialization and globals
.Sh SYNOPSIS
.Bd -literal
#include <engine/engine.h>
.Ed
.Sh DESCRIPTION
.Pp
These functions are responsible for the initialization of Agar's internals,
the initialization of SDL (and possibly OpenGL), the selection of the video
mode, the font engine and the attachment of input devices.
.Pp
.nr nS 1
.Ft "int"
.Fn engine_preinit "const char *progname"
.Pp
.Ft "int"
.Fn engine_init "void"
.nr nS 0
.Pp
The
.Fn engine_preinit
function initializes Agar's internal data structures as well as SDL.
Agar applications should invoke
.Fn engine_preinit
first, with the name of the application as the
.Fa progname
argument.
By default, Agar will use
.Pa ~/.<progname>
for the application's data files.
.Pp
The
.Fn engine_init
function sets the video mode, initializes the font engine and input devices.
.Pp
Between the calls to
.Fn engine_init
and
.Fn engine_preinit ,
several parameters may be set, such as the font engine, the font directory,
the default font and the graphic mode to use.
.Sh INCLUDE FILES
The
.Pa Aq compat/*.h
and
.Pa Aq config/*.h
includes should come first, followed by
.Pa Aq engine/engine.h ,
which itself includes:
.Pp
.Bl -tag -width "<engine/loader/integral.h> " -compact
.It Pa Aq pthread.h
POSIX threads, if available and enabled.
.It Pa Aq SDL.h
Software DirectMedia Layer.
.It Pa Aq GL/GL.h
OpenGL interface, if available and enabled.
.It Pa Aq compat/queue.h
4.4BSD
.Xr queue 3
definitions.
.It Pa Aq compat/strlcpy.h
For
.Xr strlcpy 3 .
.It Pa Aq compat/strlcat.h
For
.Xr strlcat 3 .
.It Pa Aq compat/snprintf.h
For
.Xr snprintf 3 .
.It Pa Aq compat/vsnprintf.h
For
.Xr vsnprintf 3 .
.It Pa Aq compat/vasprintf.h
For
.Xr vasprintf 3 .
.It Pa Aq compat/asprintf.h
For
.Xr asprintf 3 .
.It Pa Aq compat/strsep.h
For
.Xr strsep 3 .
.It Pa Aq engine/loader/netbuf.h
For the
.Ft AG_Netbuf
definition, required by load/save function prototypes.
.It Pa Aq engine/loader/integral.h
For saving integers.
.It Pa Aq engine/loader/real.h
For saving real numbers.
.It Pa Aq engine/loader/string.h
For saving text.
.It Pa Aq engine/loader/version.h
For versioning.
.It Pa Aq engine/error/error.h
Generic error handling.
.It Pa Aq engine/object.h
Generic
.Xr AG_Object 3
types and operations.
.It Pa Aq engine/event.h
For the
.Ft union evarg
definition and generic
.Xr event 3
handling.
.El
.Sh SEE ALSO
.Xr AG_Object 3 ,
.Xr input 3 ,
.Xr map 3 ,
.Xr view 3 ,
.Xr vg 3 ,
.Xr widget 3 ,
.Xr window 3
.Pp
.Bd -literal
http://www.libsdl.org/
http://www.opengl.org/
.Ed
