.\"	$Csoft: event.3,v 1.23 2004/05/10 11:25:03 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003, 2004 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd September 16, 2002
.Dt EVENT 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm event
.Nd agar event system
.Sh SYNOPSIS
.Bd -literal
#include <engine/event.h>
.Ed
.Sh DESCRIPTION
Once an Agar
.Xr object 3
has registered an event handler function for a specific type of event
(using the
.Fn event_new
function), a call to
.Fn event_post
for this type of event will trigger the execution of the event handler
function.
It is also possible to delay the execution of the event handler by a given
number of
.Sq ticks
using
.Fn event_schedule .
.Pp
The prototype for event handler functions looks like:
.Pp
.nr nS 1
.Ft void
.Fn foo "int argc" "union evarg *argv"
.nr nS 0
.Pp
The
.Fa argv
argument is a pointer to an array of
.Fa argc
unions, defined as:
.Bd -literal
typedef union evarg {
	void	*p;
	char	*s;
	char	 c;
	int	 i;
	long int li;
	double	 f;
} *evargs;
.Ed
.Pp
.Va argv[0]
always points to the
.Xr object 3
which is the receiver of the event.
.Va argv[argc]
always points to the
.Xr object 3
which is the sender of the event (or NULL).
.Pp
The
.Nm
subsystem also implements the
.Sq main loop
used by Agar applications, which performs the following operations:
.Bl -tag -width "SDL event processing "
.It Video updates
Agar attempts to maintain a stable video refresh rate by periodically
readjusting the delays.
This allows animations to run at the same speed under different hardware.
The nominal refresh rate is selected by
.Xr view_set_refresh 3 ,
usually at initialization time.
If Agar considers that there is enough time left after the refresh cycle, it
invokes 
.Xr SDL_Delay 3
to relinquish the CPU.
.It SDL event processing
SDL events are translated to
.Nm
structures, which are sent to the relevant subsystems, such as the
.Xr window 3
system for GUI events and
.Xr input 3
for generic input events.
.It Timeouts
The
.Xr timeout 3
system performs tasks specific to the timing schemes in use.
Under the default timing scheme, timeouts with a timestamp exceeding the
current time (as given by
.Xr SDL_GetTicks 3 )
are expired.
.El
.Sh EVENT PROCESSING
.nr nS 1
.Ft "struct event *"
.Fn event_new "void *obj" "const char *event_name" "void (*handler)(int argc, union evarg *argv)" "const char *fmt" "..."
.Pp
.Ft "void"
.Fn event_remove "void *obj" "const char *event_name"
.Pp
.Ft "int"
.Fn event_post "void *sndr" "void *rcvr" "const char *event_name" \
               "const char *fmt" "..."
.Pp
.Ft "int"
.Fn event_schedule "void *sndr" "void *rcvr" "Uint32 ticks" "const char *event_name" \
                   "const char *fmt" "..."
.Pp
.Ft "int"
.Fn event_resched "void *obj" "const char *event_name" "Uint32 ticks"
.Pp
.Ft "int"
.Fn event_cancel "void *obj" "const char *event_name"
.Pp
.Ft "void"
.Fn event_forward "void *rcvr" "const char *event_name" "int argc" "union evarg *argv"
.nr nS 0
.Pp
The
.Fn event_new
function registers a new event handler to service events of type
.Fa name .
If an event handler is already registered for the given event type, it
is replaced.
The
.Fa handler
argument specifies the event handler function.
.Pp
The
.Fa fmt
format string and subsequent arguments specify a list of arguments to
insert into the argument vector starting at position 1.
When the event handler function is invoked, it will be passed those
arguments as well as any additional arguments inserted into the argument
vector by
.Fn event_post
or
.Fn event_schedule.
.Pp
The format string in
.Fn event_post
and
.Fn event_schedule
accept the following sequences:
.Pp
.Bl -tag -compact -offset indent -width "diouxX "
.It diouxX
Converted to
.Ft int
.It DOU
Converted to
.Ft long int
.It eEfgG
Converted to
.Ft double
.It c
Converted to
.Ft char
.It s
Converted to
.Ft char *
.It p
Converted to
.Ft void *
.El
.Pp
The
.Fn event_remove
function removes the named event handler from the list.
Any future execution of this event handler as scheduled by
.Fn event_schedule
will be cancelled.
If this event handler is currently being executed (in the case of a multi-threaded
timing scheme), the function waits for its termination.
.Pp
The
.Fn event_post
function immediately executes the event handler function associated with the given
event type, if there is any.
.Fa fmt
is a format string and the arguments following it are inserted into the argument
vector passed to the event handler (following the arguments registered by
.Fn event_new ) .
.Fn event_post
returns 1 if an event handler was invoked, or 0 if there is no registered
event handler for the given event type.
.Pp
The
.Fn event_schedule
function is similar to
.Fn event_post ,
except that the event is scheduled to occur in the given number of ticks
(the meaning of which is specific to the timing scheme).
It is not possible to schedule the execution of the same event handler
multiple times.
.Fn event_schedule
returns 0 on success or -1 if no matching event handler was found.
.Pp
The
.Fn event_resched
function reschedules a previously scheduled event of the given name to
execute in the given number of ticks, using the same argument vector.
.Fn event_resched
returns 0 on success or -1 if there was no matching event handler.
.Pp
.Fn event_cancel
cancels any future execution of a previously scheduled event.
The function returns -1 if no matching event was found, 1 if a scheduled
event was cancelled, or 0 if there was nothing to cancel.
.Pp
The
.Fn event_forward
function forwards the given event to object
.Fa obj .
This function is usually called from an event handler.
.Sh EVENT FLAGS
.Pp
Acceptable flags for the
.Nm
structure include:
.Bd -literal
#define	EVENT_ASYNC	0x01	/* Event handler runs in own thread */
#define EVENT_PROPAGATE	0x02	/* Automatically forward to children */
#define EVENT_SCHEDULED	0x04	/* Pending execution (read-only flag) */
.Ed
.Pp
.Dv EVENT_ASYNC
arranges for the event handler to execute inside a separate thread.
This flag is only available if Agar was compiled with the
.Dv THREADS
option.
.Pp
If the
.Dv EVENT_PROPAGATE
flag is set, the event is automatically forwarded to every one of the
receiver's descendants prior to the execution of the receiver's event handler.
.Pp
.Dv EVENT_SCHEDULED
is a read-only flag that is set only if an event of this type has been
previously scheduled for execution by
.Fn event_schedule .
.Sh SEE ALSO
.Xr agar 3 ,
.Xr object 3 ,
.Xr timeout 3
.Sh HISTORY
The
.Nm
mechanism first appeared in Agar 1.0
