#	$Csoft$

TOP=	..
SUBDIR=	mapedit

.PATH:	mapedit

LIB=	engine
SRCS=	event.c object.c char.c world.c map.c xcf.c view.c audio.c \
	mapedit.c
OBJS=	event.o object.o char.o world.o map.o xcf.o view.o audio.o \
	mapedit.o

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/Makefile.inc
