#	$Csoft$

TOP=	../../..
include ${TOP}/Makefile.config

SHARE=	LICENSE.ttf \
	dignity.ttf kingrich.ttf larabie.ttf pakenham.ttf suigener.ttf \
	zekton.ttf zerothre.ttf zerotwos.ttf zrnic.ttf

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/libfobj/Makefile.inc
