#	$Csoft: Makefile,v 1.4 2003/06/06 02:18:04 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

TTF=	LICENSE.ttf \
	dignity.ttf kingrich.ttf larabie.ttf pakenham.ttf suigener.ttf \
	zekton.ttf zerothre.ttf zerotwos.ttf zrnic.ttf
SHARE=	${TTF}
SHAREDIR=${TTFDIR}

include ${TOP}/mk/csoft.lib.mk
