#	$Csoft: Makefile,v 1.2 2002/11/10 01:40:54 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

TTF=	LICENSE.ttf \
	dignity.ttf kingrich.ttf larabie.ttf pakenham.ttf suigener.ttf \
	zekton.ttf zerothre.ttf zerotwos.ttf zrnic.ttf

SHARE=		${TTF}
SHAREDIR=	${TTFDIR}

include ${TOP}/mk/csoft.lib.mk
