.\"
.\" Copyright (c) 2019 Julien Nadeau Carriere <vedge@csoft.net>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd JULY 21, 2019
.Dt AGARTEST 1
.Os
.ds vT Agar API Reference
.ds oS Agar 1.6
.Sh NAME
.Nm agartest
.Nd Agar interactive testsuite
.Sh SYNOPSIS
.Nm agartest
.Op Fl CWqv
.Op Fl d Ar agar-driver
.Op Fl s Ar stylesheet
.Op Fl t Ar font-spec
.Op Ar test-name ...
.Sh DESCRIPTION
.Nm
is a miniature test suite for the Agar-GUI library.
It includes various examples, interactive tests and microbenchmarks.
The command-line options are as follows:
.Bl -tag -width Ds
.It Fl C
Redirect verbose and debug message output to stderr.
By default, such messages are written to the GUI console (see
.Xr AG_Console 3 ) .
.It Fl b
Run the given command-line module(s) as benchmarks.
.It Fl W
Force timers using a software timing wheel.
By default, kernel APIs such as
.Xr select 3
and
.Xr kqueue 3
are used where available.
.It Fl q
Disable verbose and debug messages.
.It Fl d
Specify an alternate Agar driver / backend (see
.Dq AVAILABLE DRIVERS
in
.Xr AG_InitGraphics 3
for details; some drivers accept optional arguments).
.It Fl s
Specify an alternate stylesheet (see
.Xr AG_Stylesheet 3 ) .
.It Fl t
Set the default font (e.g.,
.Sq Luxi Sans:10 ,
.Sq Courier:10.5:b ,
.Sq my.otf:16 ) .
.It Fl v
Print version number and exit.
.El
.Sh ENVIRONMENT
.Bl -tag -width "LANG "
.It Dv LANG
ISO language code determining which translation should be used.
.El
.\" .Sh FILES
.Sh SEE ALSO
.Xr AG_Intro 3 ,
.Xr AG_Stylesheet 3
