TOP=	../..
include ${TOP}/Makefile.config

PROJECT=	install-sdk
PROJDIR=	ProjectFiles
PROJINCLUDES=	configure.lua
PROJFILES=	windows:vs2005::

PROG=		install-sdk
PROG_TYPE=	"CLI"
PROG_GUID=	"169b5878-2b55-481c-8b0a-9aed5db9cbe0"
SRCS=		install-sdk.c

include ${TOP}/mk/build.prog.mk
