# $Csoft: Makefile,v 1.2 2004/01/12 06:18:39 vedge Exp $

TOP=	../..

DOC=		agar-manual.ps
MACROS=		-mdoc
DOCSRC=		Cover.tr \
		Macros.tr \
		Manual.tr \
		Contents.tr

include ${TOP}/mk/csoft.doc.mk
