#	$Csoft: Makefile,v 1.1 2004/04/22 01:52:29 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

XCF=		window.xcf \
		arrow.xcf

DEN=		pixmaps.den
DEN_NAME=	"Agar widget pixmaps"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2003, 2004 CubeSoft Communications, Inc."

include ${TOP}/mk/csoft.den.mk
