/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of PixelFormat.xs. Do not edit this file, edit PixelFormat.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "PixelFormat.xs"
/*
 * Copyright (c) 2008 Hypertriton, Inc. <http://hypertriton.com/>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <agar/core.h>
#include <agar/gui.h>
#include "perl_agar.h"

#line 44 "PixelFormat.c"

XS(XS_Agar__PixelFormat_newRGB); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_newRGB)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::newRGB(package, depth, Rmask, Gmask, Bmask)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	int	depth = (int)SvIV(ST(1));
	Uint32	Rmask = (Uint32)SvUV(ST(2));
	Uint32	Gmask = (Uint32)SvUV(ST(3));
	Uint32	Bmask = (Uint32)SvUV(ST(4));
	Agar__PixelFormat	RETVAL;
#line 46 "PixelFormat.xs"
	RETVAL = AG_PixelFormatRGB(depth, Rmask, Gmask, Bmask);
#line 61 "PixelFormat.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::PixelFormat", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__PixelFormat_newRGBA); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_newRGBA)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::newRGBA(package, depth, Rmask, Gmask, Bmask, Amask)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	int	depth = (int)SvIV(ST(1));
	Uint32	Rmask = (Uint32)SvUV(ST(2));
	Uint32	Gmask = (Uint32)SvUV(ST(3));
	Uint32	Bmask = (Uint32)SvUV(ST(4));
	Uint32	Amask = (Uint32)SvUV(ST(5));
	Agar__PixelFormat	RETVAL;
#line 59 "PixelFormat.xs"
	RETVAL = AG_PixelFormatRGB(depth, Rmask, Gmask, Bmask);
#line 85 "PixelFormat.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::PixelFormat", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__PixelFormat_newIndexed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_newIndexed)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::newIndexed(package, depth)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	int	depth = (int)SvIV(ST(1));
	Agar__PixelFormat	RETVAL;
#line 68 "PixelFormat.xs"
	RETVAL = AG_PixelFormatIndexed(depth);
#line 105 "PixelFormat.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::PixelFormat", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__PixelFormat_newStandard); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_newStandard)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::newStandard(package)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	Agar__PixelFormat	RETVAL;
#line 76 "PixelFormat.xs"
	RETVAL = AG_PixelFormatDup(agView->stmpl->format);
#line 124 "PixelFormat.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::PixelFormat", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__PixelFormat_newVideo); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_newVideo)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::newVideo(package)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	Agar__PixelFormat	RETVAL;
#line 84 "PixelFormat.xs"
	RETVAL = AG_PixelFormatDup(agView->v->format);
#line 143 "PixelFormat.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::PixelFormat", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__PixelFormat_mapRGB); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_mapRGB)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::mapRGB(pf, r, g, b)");
    {
	Agar__PixelFormat	pf;
	Uint8	r = (unsigned char)SvUV(ST(1));
	Uint8	g = (unsigned char)SvUV(ST(2));
	Uint8	b = (unsigned char)SvUV(ST(3));
	Uint32	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "Agar::PixelFormat")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    pf = INT2PTR(Agar__PixelFormat,tmp);
	}
	else
	    Perl_croak(aTHX_ "pf is not of type Agar::PixelFormat");
#line 95 "PixelFormat.xs"
	RETVAL = AG_MapRGB(pf, r, g, b);
#line 173 "PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__PixelFormat_mapRGBA); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_mapRGBA)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::mapRGBA(pf, r, g, b, a)");
    {
	Agar__PixelFormat	pf;
	Uint8	r = (unsigned char)SvUV(ST(1));
	Uint8	g = (unsigned char)SvUV(ST(2));
	Uint8	b = (unsigned char)SvUV(ST(3));
	Uint8	a = (unsigned char)SvUV(ST(4));
	Uint32	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "Agar::PixelFormat")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    pf = INT2PTR(Agar__PixelFormat,tmp);
	}
	else
	    Perl_croak(aTHX_ "pf is not of type Agar::PixelFormat");
#line 107 "PixelFormat.xs"
	RETVAL = AG_MapRGBA(pf, r, g, b, a);
#line 203 "PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__PixelFormat_getRGB); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_getRGB)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::getRGB(pf, pixel)");
    SP -= items;
    {
	Agar__PixelFormat	pf;
	Uint32	pixel = (Uint32)SvUV(ST(1));
#line 116 "PixelFormat.xs"
	Uint8 r, g, b;
#line 222 "PixelFormat.c"

	if (sv_derived_from(ST(0), "Agar::PixelFormat")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    pf = INT2PTR(Agar__PixelFormat,tmp);
	}
	else
	    Perl_croak(aTHX_ "pf is not of type Agar::PixelFormat");
#line 118 "PixelFormat.xs"
	if (GIMME_V == G_SCALAR) {
		XPUSHs(newSVpvf("#%02x%02x%02x", r, g, b));
	} else {
		EXTEND(SP, 3);
		AG_GetRGB(pixel, pf, &r, &g, &b);
		PUSHs(newSViv(r));
		PUSHs(newSViv(g));
		PUSHs(newSViv(b));
	}
#line 240 "PixelFormat.c"
	PUTBACK;
	return;
    }
}


XS(XS_Agar__PixelFormat_getRGBA); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_getRGBA)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::getRGBA(pf, pixel)");
    SP -= items;
    {
	Agar__PixelFormat	pf;
	Uint32	pixel = (Uint32)SvUV(ST(1));
#line 133 "PixelFormat.xs"
	Uint8 r, g, b, a;
#line 259 "PixelFormat.c"

	if (sv_derived_from(ST(0), "Agar::PixelFormat")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    pf = INT2PTR(Agar__PixelFormat,tmp);
	}
	else
	    Perl_croak(aTHX_ "pf is not of type Agar::PixelFormat");
#line 135 "PixelFormat.xs"
	if (GIMME_V == G_SCALAR) {
		XPUSHs(newSVpvf("#%02x%02x%02x%02x", r, g, b, a));
	} else {
		EXTEND(SP, 3);
		AG_GetRGBA(pixel, pf, &r, &g, &b, &a);
		PUSHs(newSViv(r));
		PUSHs(newSViv(g));
		PUSHs(newSViv(b));
		PUSHs(newSViv(a));
	}
#line 278 "PixelFormat.c"
	PUTBACK;
	return;
    }
}


XS(XS_Agar__PixelFormat_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__PixelFormat_DESTROY)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Agar::PixelFormat::DESTROY(pf)");
    {
	Agar__PixelFormat	pf;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    pf = INT2PTR(Agar__PixelFormat,tmp);
	}
	else
	    Perl_croak(aTHX_ "pf is not a reference");
#line 150 "PixelFormat.xs"
	AG_PixelFormatFree(pf);
#line 302 "PixelFormat.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Agar__PixelFormat); /* prototype to pass -Wmissing-prototypes */
XS(boot_Agar__PixelFormat)
{
    dXSARGS;
    char* file = __FILE__;

        newXSproto("Agar::PixelFormat::newRGB", XS_Agar__PixelFormat_newRGB, file, "$$$$$");
        newXSproto("Agar::PixelFormat::newRGBA", XS_Agar__PixelFormat_newRGBA, file, "$$$$$$");
        newXSproto("Agar::PixelFormat::newIndexed", XS_Agar__PixelFormat_newIndexed, file, "$$");
        newXSproto("Agar::PixelFormat::newStandard", XS_Agar__PixelFormat_newStandard, file, "$");
        newXSproto("Agar::PixelFormat::newVideo", XS_Agar__PixelFormat_newVideo, file, "$");
        newXSproto("Agar::PixelFormat::mapRGB", XS_Agar__PixelFormat_mapRGB, file, "$$$$");
        newXSproto("Agar::PixelFormat::mapRGBA", XS_Agar__PixelFormat_mapRGBA, file, "$$$$$");
        newXSproto("Agar::PixelFormat::getRGB", XS_Agar__PixelFormat_getRGB, file, "$$");
        newXSproto("Agar::PixelFormat::getRGBA", XS_Agar__PixelFormat_getRGBA, file, "$$");
        newXSproto("Agar::PixelFormat::DESTROY", XS_Agar__PixelFormat_DESTROY, file, "$");
    XSRETURN_YES;
}

