/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Surface.xs. Do not edit this file, edit Surface.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Surface.xs"
/*
 * Copyright (c) 2008 Hypertriton, Inc. <http://hypertriton.com/>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <agar/core.h>
#include <agar/gui.h>
#include "perl_agar.h"

static const AP_FlagNames flagNames[] = {
	{ "hwSurface",   AG_HWSURFACE },
	{ "srcColorKey", AG_SRCCOLORKEY },
	{ "srcAlpha",    AG_SRCALPHA },
	{ NULL,          0 }
};

#line 51 "Surface.c"

XS(XS_Agar__Surface_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Surface_new)
{
    dXSARGS;
    if (items < 4)
	Perl_croak(aTHX_ "Usage: Agar::Surface::new(package, w, h, pf, ...)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	int	w = (int)SvIV(ST(1));
	int	h = (int)SvIV(ST(2));
	Agar__PixelFormat	pf;
#line 52 "Surface.xs"
	Uint flags = 0;
#line 66 "Surface.c"
	Agar__Surface	RETVAL;

	if (sv_derived_from(ST(3), "Agar::PixelFormat")) {
	    IV tmp = SvIV((SV*)SvRV(ST(3)));
	    pf = INT2PTR(Agar__PixelFormat,tmp);
	}
	else
	    Perl_croak(aTHX_ "pf is not of type Agar::PixelFormat");
#line 54 "Surface.xs"
	if ((items == 5 && SvTYPE(SvRV(ST(4))) != SVt_PVHV) || items > 5) {
		Perl_croak("Usage: Agar::Surface->new(w,h,pxFormat,[{opts}])");
	}
	if (items == 5) {
		AP_MapHashToFlags(SvRV(ST(4)), flagNames, &flags);
	}
	RETVAL = AG_SurfaceNew(w, h, pf, flags);
#line 83 "Surface.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::Surface", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__Surface_newIndexed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Surface_newIndexed)
{
    dXSARGS;
    if (items < 4)
	Perl_croak(aTHX_ "Usage: Agar::Surface::newIndexed(package, w, h, bitsPerPixel, ...)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	int	w = (int)SvIV(ST(1));
	int	h = (int)SvIV(ST(2));
	int	bitsPerPixel = (int)SvIV(ST(3));
#line 71 "Surface.xs"
	Uint flags = 0;
#line 104 "Surface.c"
	Agar__Surface	RETVAL;
#line 73 "Surface.xs"
	if ((items == 5 && SvTYPE(SvRV(ST(4))) != SVt_PVHV) || items > 5) {
		Perl_croak("Usage: Agar::Surface->newIndexed(w,h,depth,"
		           "[{opts}])");
	}
	if (items == 5) {
		AP_MapHashToFlags(SvRV(ST(4)), flagNames, &flags);
	}
	RETVAL = AG_SurfaceIndexed(w, h, bitsPerPixel, flags);
#line 115 "Surface.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::Surface", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__Surface_newEmpty); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Surface_newEmpty)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Agar::Surface::newEmpty(package)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	Agar__Surface	RETVAL;
#line 89 "Surface.xs"
	RETVAL = AG_SurfaceEmpty();
#line 134 "Surface.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::Surface", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__Surface_newFromBMP); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Surface_newFromBMP)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Agar::Surface::newFromBMP(package, path)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	const char *	path = (const char *)SvPV_nolen(ST(1));
	Agar__Surface	RETVAL;
#line 98 "Surface.xs"
	if ((RETVAL = AG_SurfaceFromBMP(path)) == NULL) {
		XSRETURN_UNDEF;
	}
#line 156 "Surface.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::Surface", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__Surface_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Surface_DESTROY)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Agar::Surface::DESTROY(s)");
    {
	Agar__Surface	s;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    s = INT2PTR(Agar__Surface,tmp);
	}
	else
	    Perl_croak(aTHX_ "s is not a reference");
#line 108 "Surface.xs"
	AG_SurfaceFree(s);
#line 181 "Surface.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Agar__Surface); /* prototype to pass -Wmissing-prototypes */
XS(boot_Agar__Surface)
{
    dXSARGS;
    char* file = __FILE__;

        newXSproto("Agar::Surface::new", XS_Agar__Surface_new, file, "$$$$;@");
        newXSproto("Agar::Surface::newIndexed", XS_Agar__Surface_newIndexed, file, "$$$$;@");
        newXSproto("Agar::Surface::newEmpty", XS_Agar__Surface_newEmpty, file, "$");
        newXSproto("Agar::Surface::newFromBMP", XS_Agar__Surface_newFromBMP, file, "$$");
        newXSproto("Agar::Surface::DESTROY", XS_Agar__Surface_DESTROY, file, "$");
    XSRETURN_YES;
}

