/* auto generated, do not edit */

#include <agar/core.h>
#include <agar/gui.h>

/* XXX: private */
typedef unsigned int Uint;
#include <agar/gui/titlebar.h>

#include <stdio.h>
#include <string.h>

struct {
  const char *type_name;
  unsigned int type_size;
} types[] = {
  { "AG_BlendFn", sizeof (AG_BlendFn) },
  { "enum ag_blend_func", sizeof (enum ag_blend_func) },
  { "AG_Color", sizeof (AG_Color) },
  { "struct ag_color", sizeof (struct ag_color) },
  { "AG_PixelFormat *", sizeof (AG_PixelFormat *) },
  { "AG_PixelFormat", sizeof (AG_PixelFormat) },
  { "AG_Point", sizeof (AG_Point) },
  { "struct ag_point", sizeof (struct ag_point) },
  { "AG_Rect *", sizeof (AG_Rect *) },
  { "struct ag_rect *", sizeof (struct ag_rect *) },
  { "AG_Rect", sizeof (AG_Rect) },
  { "struct ag_rect", sizeof (struct ag_rect) },
  { "AG_Rect2 *", sizeof (AG_Rect2 *) },
  { "struct ag_rect2 *", sizeof (struct ag_rect2 *) },
  { "AG_Rect2", sizeof (AG_Rect2) },
  { "struct ag_rect2", sizeof (struct ag_rect2) },
  { "AG_Style *", sizeof (AG_Style *) },
  { "struct ag_style *", sizeof (struct ag_style *) },
  { "AG_Style", sizeof (AG_Style) },
  { "struct ag_style", sizeof (struct ag_style) },
  { "AG_Surface *", sizeof (AG_Surface *) },
  { "AG_Surface", sizeof (AG_Surface) },
  { "AG_Font *", sizeof (AG_Font *) },
  { "struct ag_font *", sizeof (struct ag_font *) },
  { "AG_Font", sizeof (AG_Font) },
  { "struct ag_font", sizeof (struct ag_font) },
  { "enum ag_font_type", sizeof (enum ag_font_type) },
  { "AG_Glyph *", sizeof (AG_Glyph *) },
  { "struct ag_glyph *", sizeof (struct ag_glyph *) },
  { "AG_Glyph", sizeof (AG_Glyph) },
  { "struct ag_glyph", sizeof (struct ag_glyph) },
  { "enum ag_text_justify", sizeof (enum ag_text_justify) },
  { "AG_TextMetrics *", sizeof (AG_TextMetrics *) },
  { "struct ag_text_metrics *", sizeof (struct ag_text_metrics *) },
  { "AG_TextMetrics", sizeof (AG_TextMetrics) },
  { "struct ag_text_metrics", sizeof (struct ag_text_metrics) },
  { "enum ag_text_msg_title", sizeof (enum ag_text_msg_title) },
  { "AG_TextState *", sizeof (AG_TextState *) },
  { "struct ag_text_state *", sizeof (struct ag_text_state *) },
  { "AG_TextState", sizeof (AG_TextState) },
  { "struct ag_text_state", sizeof (struct ag_text_state) },
  { "AG_StaticFont *", sizeof (AG_StaticFont *) },
  { "struct ag_static_font *", sizeof (struct ag_static_font *) },
  { "AG_StaticFont", sizeof (AG_StaticFont) },
  { "struct ag_static_font", sizeof (struct ag_static_font) },
  { "enum ag_text_valign", sizeof (enum ag_text_valign) },
  { "AG_Unit", sizeof (AG_Unit) },
  { "struct ag_unit", sizeof (struct ag_unit) },
  { "AG_Display", sizeof (AG_Display) },
  { "struct ag_display", sizeof (struct ag_display) },
  { "AG_WidgetBinding *", sizeof (AG_WidgetBinding *) },
  { "struct ag_widget_binding *", sizeof (struct ag_widget_binding *) },
  { "AG_WidgetBinding", sizeof (AG_WidgetBinding) },
  { "struct ag_widget_binding", sizeof (struct ag_widget_binding) },
  { "AG_WidgetBindingType", sizeof (AG_WidgetBindingType) },
  { "enum ag_widget_binding_type", sizeof (enum ag_widget_binding_type) },
  { "AG_Box *", sizeof (AG_Box *) },
  { "struct ag_box *", sizeof (struct ag_box *) },
  { "AG_Box", sizeof (AG_Box) },
  { "struct ag_box", sizeof (struct ag_box) },
  { "enum ag_box_type", sizeof (enum ag_box_type) },
  { "AG_Button *", sizeof (AG_Button *) },
  { "struct ag_button *", sizeof (struct ag_button *) },
  { "AG_Button", sizeof (AG_Button) },
  { "struct ag_button", sizeof (struct ag_button) },
  { "AG_Checkbox *", sizeof (AG_Checkbox *) },
  { "struct ag_checkbox *", sizeof (struct ag_checkbox *) },
  { "AG_Checkbox", sizeof (AG_Checkbox) },
  { "struct ag_checkbox", sizeof (struct ag_checkbox) },
  { "AG_WidgetClass *", sizeof (AG_WidgetClass *) },
  { "struct ag_widget_class *", sizeof (struct ag_widget_class *) },
  { "AG_WidgetClass", sizeof (AG_WidgetClass) },
  { "struct ag_widget_class", sizeof (struct ag_widget_class) },
  { "AG_Combo *", sizeof (AG_Combo *) },
  { "struct ag_combo *", sizeof (struct ag_combo *) },
  { "AG_Combo", sizeof (AG_Combo) },
  { "struct ag_combo", sizeof (struct ag_combo) },
  { "AG_Console *", sizeof (AG_Console *) },
  { "struct ag_console *", sizeof (struct ag_console *) },
  { "AG_Console", sizeof (AG_Console) },
  { "struct ag_console", sizeof (struct ag_console) },
  { "AG_ConsoleLine *", sizeof (AG_ConsoleLine *) },
  { "struct ag_console_line *", sizeof (struct ag_console_line *) },
  { "AG_ConsoleLine", sizeof (AG_ConsoleLine) },
  { "struct ag_console_line", sizeof (struct ag_console_line) },
  { "AG_Editable *", sizeof (AG_Editable *) },
  { "struct ag_editable *", sizeof (struct ag_editable *) },
  { "AG_Editable", sizeof (AG_Editable) },
  { "struct ag_editable", sizeof (struct ag_editable) },
  { "enum ag_editable_encoding", sizeof (enum ag_editable_encoding) },
  { "AG_FileDlg *", sizeof (AG_FileDlg *) },
  { "struct ag_file_dlg *", sizeof (struct ag_file_dlg *) },
  { "AG_FileDlg", sizeof (AG_FileDlg) },
  { "struct ag_file_dlg", sizeof (struct ag_file_dlg) },
  { "AG_FileType *", sizeof (AG_FileType *) },
  { "struct ag_file_type *", sizeof (struct ag_file_type *) },
  { "AG_FileType", sizeof (AG_FileType) },
  { "struct ag_file_type", sizeof (struct ag_file_type) },
  { "AG_FileOption *", sizeof (AG_FileOption *) },
  { "struct ag_file_type_option *", sizeof (struct ag_file_type_option *) },
  { "AG_FileOption", sizeof (AG_FileOption) },
  { "struct ag_file_type_option", sizeof (struct ag_file_type_option) },
  { "enum ag_file_type_option_type", sizeof (enum ag_file_type_option_type) },
  { "AG_Fixed *", sizeof (AG_Fixed *) },
  { "struct ag_fixed *", sizeof (struct ag_fixed *) },
  { "AG_Fixed", sizeof (AG_Fixed) },
  { "struct ag_fixed", sizeof (struct ag_fixed) },
  { "AG_FixedPlotterItem *", sizeof (AG_FixedPlotterItem *) },
  { "struct ag_fixed_plotter_item *", sizeof (struct ag_fixed_plotter_item *) },
  { "AG_FixedPlotterItem", sizeof (AG_FixedPlotterItem) },
  { "struct ag_fixed_plotter_item", sizeof (struct ag_fixed_plotter_item) },
  { "AG_FixedPlotter *", sizeof (AG_FixedPlotter *) },
  { "struct ag_fixed_plotter *", sizeof (struct ag_fixed_plotter *) },
  { "AG_FixedPlotter", sizeof (AG_FixedPlotter) },
  { "struct ag_fixed_plotter", sizeof (struct ag_fixed_plotter) },
  { "enum ag_fixed_plotter_type", sizeof (enum ag_fixed_plotter_type) },
  { "AG_FlagDescr *", sizeof (AG_FlagDescr *) },
  { "struct ag_flag_descr *", sizeof (struct ag_flag_descr *) },
  { "AG_FlagDescr", sizeof (AG_FlagDescr) },
  { "struct ag_flag_descr", sizeof (struct ag_flag_descr) },
  { "AG_GraphEdge *", sizeof (AG_GraphEdge *) },
  { "struct ag_graph_edge *", sizeof (struct ag_graph_edge *) },
  { "AG_GraphEdge", sizeof (AG_GraphEdge) },
  { "struct ag_graph_edge", sizeof (struct ag_graph_edge) },
  { "AG_Graph *", sizeof (AG_Graph *) },
  { "struct ag_graph *", sizeof (struct ag_graph *) },
  { "AG_Graph", sizeof (AG_Graph) },
  { "struct ag_graph", sizeof (struct ag_graph) },
  { "AG_GraphVertex *", sizeof (AG_GraphVertex *) },
  { "struct ag_graph_vertex *", sizeof (struct ag_graph_vertex *) },
  { "enum ag_graph_vertex_style", sizeof (enum ag_graph_vertex_style) },
  { "AG_GraphVertex", sizeof (AG_GraphVertex) },
  { "struct ag_graph_vertex", sizeof (struct ag_graph_vertex) },
  { "AG_HBox *", sizeof (AG_HBox *) },
  { "struct ag_hbox *", sizeof (struct ag_hbox *) },
  { "AG_HBox", sizeof (AG_HBox) },
  { "struct ag_hbox", sizeof (struct ag_hbox) },
  { "AG_HSVPal *", sizeof (AG_HSVPal *) },
  { "struct ag_hsvpal *", sizeof (struct ag_hsvpal *) },
  { "AG_HSVPal", sizeof (AG_HSVPal) },
  { "struct ag_hsvpal", sizeof (struct ag_hsvpal) },
  { "AG_Icon *", sizeof (AG_Icon *) },
  { "struct ag_icon *", sizeof (struct ag_icon *) },
  { "AG_Icon", sizeof (AG_Icon) },
  { "struct ag_icon", sizeof (struct ag_icon) },
  { "struct ag_label_flag", sizeof (struct ag_label_flag) },
  { "AG_LabelFormatFn", sizeof (AG_LabelFormatFn) },
  { "AG_LabelFormatSpec *", sizeof (AG_LabelFormatSpec *) },
  { "struct ag_label_format_spec *", sizeof (struct ag_label_format_spec *) },
  { "AG_LabelFormatSpec", sizeof (AG_LabelFormatSpec) },
  { "struct ag_label_format_spec", sizeof (struct ag_label_format_spec) },
  { "AG_Label *", sizeof (AG_Label *) },
  { "struct ag_label *", sizeof (struct ag_label *) },
  { "AG_Label", sizeof (AG_Label) },
  { "struct ag_label", sizeof (struct ag_label) },
  { "enum ag_label_type", sizeof (enum ag_label_type) },
  { "enum ag_menu_binding", sizeof (enum ag_menu_binding) },
  { "AG_MenuItem *", sizeof (AG_MenuItem *) },
  { "struct ag_menu_item *", sizeof (struct ag_menu_item *) },
  { "AG_MenuItem", sizeof (AG_MenuItem) },
  { "struct ag_menu_item", sizeof (struct ag_menu_item) },
  { "AG_Menu *", sizeof (AG_Menu *) },
  { "struct ag_menu *", sizeof (struct ag_menu *) },
  { "AG_Menu", sizeof (AG_Menu) },
  { "struct ag_menu", sizeof (struct ag_menu) },
  { "AG_PopupMenu *", sizeof (AG_PopupMenu *) },
  { "struct ag_popup_menu *", sizeof (struct ag_popup_menu *) },
  { "AG_PopupMenu", sizeof (AG_PopupMenu) },
  { "struct ag_popup_menu", sizeof (struct ag_popup_menu) },
  { "AG_MenuView *", sizeof (AG_MenuView *) },
  { "struct ag_menu_view *", sizeof (struct ag_menu_view *) },
  { "AG_MenuView", sizeof (AG_MenuView) },
  { "struct ag_menu_view", sizeof (struct ag_menu_view) },
  { "enum ag_mpane_layout", sizeof (enum ag_mpane_layout) },
  { "AG_MPane *", sizeof (AG_MPane *) },
  { "struct ag_mpane *", sizeof (struct ag_mpane *) },
  { "AG_MPane", sizeof (AG_MPane) },
  { "struct ag_mpane", sizeof (struct ag_mpane) },
  { "AG_Notebook *", sizeof (AG_Notebook *) },
  { "struct ag_notebook *", sizeof (struct ag_notebook *) },
  { "AG_Notebook", sizeof (AG_Notebook) },
  { "struct ag_notebook", sizeof (struct ag_notebook) },
  { "AG_NotebookTab *", sizeof (AG_NotebookTab *) },
  { "struct ag_notebook_tab *", sizeof (struct ag_notebook_tab *) },
  { "enum ag_notebook_tab_alignment", sizeof (enum ag_notebook_tab_alignment) },
  { "AG_NotebookTab", sizeof (AG_NotebookTab) },
  { "struct ag_notebook_tab", sizeof (struct ag_notebook_tab) },
  { "AG_Numerical *", sizeof (AG_Numerical *) },
  { "struct ag_numerical *", sizeof (struct ag_numerical *) },
  { "AG_Numerical", sizeof (AG_Numerical) },
  { "struct ag_numerical", sizeof (struct ag_numerical) },
  { "AG_Pane *", sizeof (AG_Pane *) },
  { "struct ag_pane *", sizeof (struct ag_pane *) },
  { "AG_Pane", sizeof (AG_Pane) },
  { "struct ag_pane", sizeof (struct ag_pane) },
  { "enum ag_pane_type", sizeof (enum ag_pane_type) },
  { "AG_Pixmap *", sizeof (AG_Pixmap *) },
  { "struct ag_pixmap *", sizeof (struct ag_pixmap *) },
  { "AG_Pixmap", sizeof (AG_Pixmap) },
  { "struct ag_pixmap", sizeof (struct ag_pixmap) },
  { "AG_ProgressBar *", sizeof (AG_ProgressBar *) },
  { "struct ag_progress_bar *", sizeof (struct ag_progress_bar *) },
  { "AG_ProgressBar", sizeof (AG_ProgressBar) },
  { "struct ag_progress_bar", sizeof (struct ag_progress_bar) },
  { "enum ag_progress_bar_type", sizeof (enum ag_progress_bar_type) },
  { "AG_RadioItem *", sizeof (AG_RadioItem *) },
  { "struct ag_radio_item *", sizeof (struct ag_radio_item *) },
  { "AG_RadioItem", sizeof (AG_RadioItem) },
  { "struct ag_radio_item", sizeof (struct ag_radio_item) },
  { "AG_RadioItem *", sizeof (AG_RadioItem *) },
  { "struct ag_radio *", sizeof (struct ag_radio *) },
  { "AG_RadioItem", sizeof (AG_RadioItem) },
  { "struct ag_radio", sizeof (struct ag_radio) },
  { "enum ag_scrollbar_button", sizeof (enum ag_scrollbar_button) },
  { "AG_Scrollbar *", sizeof (AG_Scrollbar *) },
  { "struct ag_scrollbar *", sizeof (struct ag_scrollbar *) },
  { "AG_Scrollbar", sizeof (AG_Scrollbar) },
  { "struct ag_scrollbar", sizeof (struct ag_scrollbar) },
  { "enum ag_scrollbar_type", sizeof (enum ag_scrollbar_type) },
  { "AG_Separator *", sizeof (AG_Separator *) },
  { "struct ag_separator *", sizeof (struct ag_separator *) },
  { "AG_Separator", sizeof (AG_Separator) },
  { "struct ag_separator", sizeof (struct ag_separator) },
  { "enum ag_separator_type", sizeof (enum ag_separator_type) },
  { "AG_SizeReq *", sizeof (AG_SizeReq *) },
  { "struct ag_size_req *", sizeof (struct ag_size_req *) },
  { "AG_SizeReq", sizeof (AG_SizeReq) },
  { "struct ag_size_req", sizeof (struct ag_size_req) },
  { "enum ag_widget_sizespec", sizeof (enum ag_widget_sizespec) },
  { "enum ag_slider_button", sizeof (enum ag_slider_button) },
  { "AG_Slider *", sizeof (AG_Slider *) },
  { "struct ag_slider *", sizeof (struct ag_slider *) },
  { "AG_Slider", sizeof (AG_Slider) },
  { "struct ag_slider", sizeof (struct ag_slider) },
  { "enum ag_slider_type", sizeof (enum ag_slider_type) },
  { "enum ag_socket_bg_type", sizeof (enum ag_socket_bg_type) },
  { "AG_Socket *", sizeof (AG_Socket *) },
  { "struct ag_socket *", sizeof (struct ag_socket *) },
  { "AG_Socket", sizeof (AG_Socket) },
  { "struct ag_socket", sizeof (struct ag_socket) },
  { "AG_TableCell *", sizeof (AG_TableCell *) },
  { "struct ag_table_cell *", sizeof (struct ag_table_cell *) },
  { "AG_TableCell", sizeof (AG_TableCell) },
  { "struct ag_table_cell", sizeof (struct ag_table_cell) },
  { "enum ag_table_cell_type", sizeof (enum ag_table_cell_type) },
  { "AG_TableCol *", sizeof (AG_TableCol *) },
  { "struct ag_table_col *", sizeof (struct ag_table_col *) },
  { "AG_TableCol", sizeof (AG_TableCol) },
  { "struct ag_table_col", sizeof (struct ag_table_col) },
  { "AG_TablePopup *", sizeof (AG_TablePopup *) },
  { "struct ag_table_popup *", sizeof (struct ag_table_popup *) },
  { "AG_TablePopup", sizeof (AG_TablePopup) },
  { "struct ag_table_popup", sizeof (struct ag_table_popup) },
  { "enum ag_table_selmode", sizeof (enum ag_table_selmode) },
  { "AG_Table *", sizeof (AG_Table *) },
  { "struct ag_table *", sizeof (struct ag_table *) },
  { "AG_Table", sizeof (AG_Table) },
  { "struct ag_table", sizeof (struct ag_table) },
  { "AG_Textbox *", sizeof (AG_Textbox *) },
  { "struct ag_textbox *", sizeof (struct ag_textbox *) },
  { "AG_Textbox", sizeof (AG_Textbox) },
  { "struct ag_textbox", sizeof (struct ag_textbox) },
  { "AG_Titlebar *", sizeof (AG_Titlebar *) },
  { "struct ag_titlebar *", sizeof (struct ag_titlebar *) },
  { "AG_Titlebar", sizeof (AG_Titlebar) },
  { "struct ag_titlebar", sizeof (struct ag_titlebar) },
  { "AG_TlistItem *", sizeof (AG_TlistItem *) },
  { "struct ag_tlist_item *", sizeof (struct ag_tlist_item *) },
  { "AG_TlistItem", sizeof (AG_TlistItem) },
  { "struct ag_tlist_item", sizeof (struct ag_tlist_item) },
  { "AG_TlistPopup *", sizeof (AG_TlistPopup *) },
  { "struct ag_tlist_popup *", sizeof (struct ag_tlist_popup *) },
  { "AG_TlistPopup", sizeof (AG_TlistPopup) },
  { "struct ag_tlist_popup", sizeof (struct ag_tlist_popup) },
  { "AG_Tlist *", sizeof (AG_Tlist *) },
  { "struct ag_tlist *", sizeof (struct ag_tlist *) },
  { "AG_Tlist", sizeof (AG_Tlist) },
  { "struct ag_tlist", sizeof (struct ag_tlist) },
  { "AG_Toolbar *", sizeof (AG_Toolbar *) },
  { "struct ag_toolbar *", sizeof (struct ag_toolbar *) },
  { "AG_Toolbar", sizeof (AG_Toolbar) },
  { "struct ag_toolbar", sizeof (struct ag_toolbar) },
  { "enum ag_toolbar_type", sizeof (enum ag_toolbar_type) },
  { "AG_UCombo *", sizeof (AG_UCombo *) },
  { "struct ag_ucombo *", sizeof (struct ag_ucombo *) },
  { "AG_UCombo", sizeof (AG_UCombo) },
  { "struct ag_ucombo", sizeof (struct ag_ucombo) },
  { "AG_VBox *", sizeof (AG_VBox *) },
  { "struct ag_vbox *", sizeof (struct ag_vbox *) },
  { "AG_VBox", sizeof (AG_VBox) },
  { "struct ag_vbox", sizeof (struct ag_vbox) },
  { "AG_Widget *", sizeof (AG_Widget *) },
  { "struct ag_widget *", sizeof (struct ag_widget *) },
  { "AG_Widget", sizeof (AG_Widget) },
  { "struct ag_widget", sizeof (struct ag_widget) },
  { "enum ag_window_alignment", sizeof (enum ag_window_alignment) },
  { "enum ag_window_close_action", sizeof (enum ag_window_close_action) },
  { "AG_Window *", sizeof (AG_Window *) },
  { "struct ag_window *", sizeof (struct ag_window *) },
  { "AG_Window", sizeof (AG_Window) },
  { "struct ag_window", sizeof (struct ag_window) },
};
const unsigned int types_size = sizeof (types) / sizeof (types[0]);

void
find (const char *name)
{
  unsigned int pos;
  for (pos = 0; pos < types_size; ++pos) {
    if (strcmp (types[pos].type_name, name) == 0) {
      printf ("%u\n", types[pos].type_size * 8);
      return;
    }
  }
  fprintf (stderr, "fatal: unknown C type\n");
  exit (112);
}

int
main (int argc, char *argv[])
{
  if (argc != 2) exit (111);
  find (argv[1]);
  return 0;
}
