#	$Csoft: Makefile,v 1.22 2004/03/18 21:27:48 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

XCF=		toolbar.xcf monitor.xcf
DEN=		pixmaps.den
DEN_DIR=	engine/monitor
DEN_NAME=	"Agar debug monitor pixmaps"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2002, 2003, 2004 CubeSoft Communications, Inc."

DENCOMP=${TOP}/dencomp/dencomp
include ${TOP}/mk/csoft.den.mk
