TOP=	..
include ${TOP}/Makefile.config

PROG=		agar-dev-config
PROG_TYPE=	"CLI"
PROG_GUID=	"65c3f109-7bbf-4c01-b0a4-57ee5fcce8ac"

SRCS=	agar-dev-config.c
CFLAGS+=-I..

include ${TOP}/mk/build.prog.mk
