.\" Copyright (c) 2022 Julien Nadeau Carriere <vedge@csoft.net>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd December 23, 2022
.Dt AG_DRIVERSDL2GL 3
.Os Agar 1.7
.Sh NAME
.Nm AG_DriverSDL2GL
.Nd agar SDL2 OpenGL driver
.Sh DESCRIPTION
.\" IMAGE(http://libagar.org/widgets/AG_DriverSDL2GL.png, "The sdl2gl driver")
The Agar
.Va sdl2gl
driver provides an interface to the Simple DirectMedia Layer (SDL) library
version 2, and renders GUI elements as OpenGL primitives and managed textures.
.Pp
Using
.Xr AG_InitVideoSDL 3
as opposed to
.Xr AG_InitGraphics 3 ,
it is possible to attach Agar to an existing SDL display surface.
If the SDL surface has the
.Dv SDL_OPENGL
flag set then
.Va sdl2gl
will be auto-selected by default.
.Sh INHERITANCE HIERARCHY
.Xr AG_Driver 3 ->
.Xr AG_DriverSw 3 ->
.Nm .
.Sh EXAMPLES
.Bd -literal -offset indent
.\" SYNTAX(c)
AG_InitGraphics("sdl2gl(width=640:height=480)");
AG_InitGraphics("sdl2gl(width=60%:height=80%)");
AG_InitGraphics("sdl2gl(bgColor=0/120/120)");
AG_InitGraphics("sdl2gl(out=%08d.jpg:outFirst=10)");
AG_InitGraphics("sdl2gl(depth=64:stereo)");

AG_InitVideoSDL(an_existing_SDL_screen, 0);
.Ed
.Sh OPTIONS
.Bl -tag -compact -width "clampOnResize "
.It debug
Capture
.Dv GL_DEBUG_OUTPUT
errors.
.It stereo
Request a stereoscopic visual.
.It width
Display width in pixels (e.g., "320"), percent of total desktop size (e.g., "50%") or "auto".
.It height
Display height in pixels (e.g., "240"), percent of total desktop size (e.g., "50%") or "auto".
.It depth
Depth in bits per pixel, or "auto".
.It fpsMax
Limit refresh rate in frames/second (e.g., "60").
.It out
Dump video frames to JPEG or PNG image files.
The filename path may include a printf-style (with frame number as argument).
For example,
.Sq %08d.jpg
will output frames to 00000001.jpg, 00000002.jpg, etc.
.It outFirst
Override first frame number (default = 0).
.It outLast
Terminate application after # frames have been rendered.
.It bgColor
Solid background color specified as "R/G/B", from "0/0/0" (black) to
"255/255/255" (white).
.It !bgPopup
Disable the right-click background popup menu
(which includes, notably the list of active windows).
.It jpegQual
If exporting to JPEG, set quality factor (100% = best).
.It jpegDCT
If exporting to JPEG, specify DCT method ("islow" for slow but accurate
integer method, "ifast" for fast but less accurate integer method, or
"float" for floating point method).
.It clampOnResize
Whenever the display is resized, clamp Agar window positions and sizes
to fit the new display size.
.El
.Sh SEE ALSO
.Xr AG_DriverSDL2FB 3 ,
.Xr AG_DriverSDL2MW 3 ,
.Xr AG_DriverSDLFB 3 ,
.Xr AG_DriverSDLGL 3 ,
.Xr AG_Driver 3 ,
.Xr AG_DriverSw 3 ,
.Xr AG_GL 3 ,
.Xr AG_InitGraphics 3 ,
.Xr AG_Intro 3
.Pp
.Bl -tag -compact
.It Lk https://libsdl.org/ Simple DirectMedia Layer
.It Lk https://www.opengl.org/ OpenGL
.El
.Sh HISTORY
The
.Va sdl2gl
driver first appeared in Agar 1.7.0.
The
.Va clampOnResize
option appeared in Agar 1.7.
