.\" Copyright (c) 2022 Julien Nadeau Carriere <vedge@csoft.net>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd December 21, 2022
.Dt AG_DRIVERSDL2GL 3
.Os Agar 1.7
.Sh NAME
.Nm AG_DriverSDL2MW
.Nd agar SDL2 multi-window OpenGL driver
.Sh DESCRIPTION
.\" IMAGE(http://libagar.org/widgets/AG_DriverSDL2MW.png, "The sdl2mw driver")
The Agar
.Va sdl2mw
driver provides an interface to the Simple DirectMedia Layer (SDL) library
version 2, and renders GUI elements as OpenGL primitives and managed textures
in separate windows.
.Sh INHERITANCE HIERARCHY
.Xr AG_Driver 3 ->
.Xr AG_DriverMw 3 ->
.Nm .
.Sh EXAMPLES
.Bd -literal -offset indent
.\" SYNTAX(c)
AG_InitGraphics("sdl2mw");
AG_InitGraphics("sdl2mw(stereo)");
AG_InitGraphics("sdl2mw(out=%08d.jpg)");
.Ed
.Sh OPTIONS
.Bl -tag -compact -width "noAutoCapture "
.It noAutoCapture
Disable mouse auto-capture behavior
(see
.Dv SDL_HINT_MOUSE_AUTO_CAPTURE ) .
Enabled by default.
May be set by widget code with the
.Fn setMouseAutoCapture
driver operation (see
.Xr AG_Driver 3 ) .
.It debug
Capture
.Dv GL_DEBUG_OUTPUT
errors.
.It stereo
Request a stereoscopic visual.
.It out
Dump video frames to JPEG or PNG image files.
The filename path may include a printf-style (with frame number as argument).
For example,
.Sq %08d.jpg
will output frames to 00000001.jpg, 00000002.jpg, etc.
.It outFirst
Override first frame number (default = 0).
.It outLast
Terminate application after # frames have been rendered.
.It jpegQual
If exporting to JPEG, set quality factor (100% = best).
.It jpegDCT
If exporting to JPEG, specify DCT method ("islow" for slow but accurate
integer method, "ifast" for fast but less accurate integer method, or
"float" for floating point method).
.El
.Sh SEE ALSO
.Xr AG_DriverSDL2FB 3 ,
.Xr AG_DriverSDL2GL 3 ,
.Xr AG_DriverSDLFB 3 ,
.Xr AG_DriverSDLGL 3 ,
.Xr AG_Driver 3 ,
.Xr AG_DriverMw 3 ,
.Xr AG_GL 3 ,
.Xr AG_InitGraphics 3 ,
.Xr AG_Intro 3
.Pp
.Bl -tag -compact
.It Lk https://libsdl.org/ Simple DirectMedia Layer
.It Lk https://www.opengl.org/ OpenGL
.El
.Sh HISTORY
The
.Va sdl2mw
driver first appeared in Agar 1.7.0.
