.\" Copyright (c) 2010-2019 Julien Nadeau Carriere <vedge@csoft.net>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd May 2, 2010
.Dt AG_DRIVERSDLFB 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.4.1
.Sh NAME
.Nm AG_DriverSDLFB
.Nd agar SDL frame-buffer driver
.Sh DESCRIPTION
.\" IMAGE(http://libagar.org/widgets/AG_DriverSDLFB.png, "The sdlfb driver")
The Agar
.Va sdlfb
driver provides an interface to the Simple DirectMedia Layer (SDL) library,
and renders GUI elements directly to the frame-buffer.
Using
.Xr AG_InitVideoSDL 3
as opposed to
.Xr AG_InitGraphics 3 ,
it is possible to attach Agar to an existing SDL display surface.
.Sh INHERITANCE HIERARCHY
.Xr AG_Driver 3 ->
.Xr AG_DriverSw 3 ->
.Nm .
.Sh EXAMPLES
.Bd -literal -offset indent
AG_InitGraphics("sdlfb(width=640:height=480)");
AG_InitGraphics("sdlfb(width=60%:height=80%)");
AG_InitGraphics("sdlgl(bgColor=0/120/120)");

AG_InitVideoSDL(an_existing_SDL_screen, 0);
.Ed
.Sh OPTIONS
.Bl -tag -compact -width "bgColor "
.It width
Width in pixels, in % of available desktop space, or "auto".
.It height
Height in pixels, in % of available desktop space, or "auto".
.It depth
Depth in bits per pixel, or "auto".
.It fpsMax
Limit GUI refresh rate in frames/second (default = 60fps).
.It bgColor
Solid background color specified as "R/G/B", from "0/0/0" (black) to
"255/255/255" (white).
.It !bgPopup
Disable the right-click background popup menu
(which includes, notably the list of active windows).
.El
.Sh SEE ALSO
.Xr AG_Driver 3 ,
.Xr AG_DriverSw 3 ,
.Xr AG_InitGraphics 3 ,
.Xr AG_Intro 3
.Pp
.Lk https://libsdl.org/ Simple_DirectMedia_Layer
.Pp
.Lk https://www.opengl.org/ OpenGL
.Sh HISTORY
The
.Va sdlfb
driver first appeared in Agar 1.4.0.
