.\" Copyright (c) 2008-2020 Julien Nadeau Carriere <vedge@csoft.net>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd May 21, 2005
.Dt AG_FONT_SELECTOR 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.3.4
.Sh NAME
.Nm AG_FontSelector
.Nd agar font selection widget
.Sh SYNOPSIS
.Bd -literal
#include <agar/core.h>
#include <agar/gui.h>
.Ed
.Sh DESCRIPTION
.\" IMAGE(http://libagar.org/widgets/AG_FontSelector.png, "The AG_FontSelector widget")
.Nm
allows the user to select a specific font from parameters such as family (face),
size and style options.
Types listed include:
.Bl -bullet
.It
Compiled-in fonts (fonts statically built into libag_gui).
.It
Agar core fonts, application-specific and user fonts obtained by scanning the
font path
.Dv ( the AG_CONFIG_PATH_FONTS
setting of
.Xr AG_Config 3 )
for recognized extensions (.otf .ttf .ttc .woff2 .woff .dfont .fnt .bmp or .png).
.It
System fonts (obtained via fontconfig where available).
.El
.Sh INHERITANCE HIERARCHY
.Xr AG_Object 3 ->
.Xr AG_Widget 3 ->
.Nm .
.Sh INITIALIZATION
.nr nS 1
.Ft "AG_FontSelector *"
.Fn AG_FontSelectorNew "AG_Widget *parent" "Uint flags"
.Pp
.nr nS 0
The
.Fn AG_FontSelectorNew
function allocates, initializes, and attaches a new
.Nm
widget.
Acceptable
.Fa flags
include:
.Bl -tag -width "AG_FONTSELECTOR_ALT_PHRASE "
.It AG_FONTSELECTOR_ALT_PHRASE
Select a different text string for preview.
.It AG_FONTSELECTOR_SW_STYLES
Display "Software styles".
.It AG_FONTSELECTOR_HFILL
Expand horizontally in parent container.
.It AG_FONTSELECTOR_VFILL
Expand horizontally in parent container.
.It AG_FONTSELECTOR_EXPAND
Shorthand for
.Dv AG_FONTSELECTOR_HFILL | AG_FONTSELECTOR_VFILL .
.El
.Sh BINDINGS
The
.Nm
widget provides the following bindings:
.Pp
.Bl -tag -compact -width "AG_Font **font "
.It Va AG_Font **font
Pointer to an
.Xr AG_Font 3
pointer which will be modified according to the user's selection.
.El
.Sh EVENTS
The
.Nm
widget does not generate any event.
.Sh EXAMPLES
The following code fragment creates a new window containing a
.Nm
widget:
.Bd -literal -offset indent
AG_Window *win;
AG_FontSelector *fs;
AG_Font *myFont;

win = AG_WindowNew(0);
fs = AG_FontSelectorNew(win, AG_FONTSELECTOR_EXPAND);
myFont = AG_TextFontPct(150);
AG_BindPointer(fs, "font", (void **)&myFont);
AG_WindowShow(win);
.Ed
.Sh SEE ALSO
.Xr AG_Intro 3 ,
.Xr AG_Text 3 ,
.Xr AG_Widget 3 ,
.Xr AG_Window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.3.4.
