.\" Copyright (c) 2007-2018 Julien Nadeau Carriere <vedge@csoft.net>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd November 17, 2007
.Dt AG_ICON 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.3
.Sh NAME
.Nm AG_Icon
.Nd agar icon widget
.Sh SYNOPSIS
.Bd -literal
#include <agar/core.h>
#include <agar/gui.h>
.Ed
.Sh DESCRIPTION
The
.Nm
widget is a simple icon suitable for drag-and-drop.
It is commonly used with
.Xr AG_Socket 3 .
.Sh INHERITANCE HIERARCHY
.Xr AG_Object 3 ->
.Xr AG_Widget 3 ->
.Nm .
.Sh INITIALIZATION
.nr nS 1
.Ft "AG_Icon *"
.Fn AG_IconNew "void *parent" "Uint flags"
.Pp
.Ft "AG_Icon *"
.Fn AG_IconFromSurface "AG_Surface *s"
.Pp
.Ft "AG_Icon *"
.Fn AG_IconFromBMP "const char *filename"
.Pp
.Ft "void"
.Fn AG_IconSetPadding "AG_Icon *icon" "int left" "int right" "int top" "int bottom"
.Pp
.Ft "void"
.Fn AG_IconSetSurface "AG_Icon *icon" "AG_Surface *s"
.Pp
.Ft "void"
.Fn AG_IconSetSurfaceNODUP "AG_Icon *icon" "AG_Surface *s"
.Pp
.Ft "void"
.Fn AG_IconSetText "AG_Icon *icon" "const char *format" "..."
.Pp
.Ft "void"
.Fn AG_IconSetTextS "AG_Icon *icon" "const char *label"
.Pp
.Ft "void"
.Fn AG_IconSetBackgroundFill "AG_Icon *icon" "int enable" "const AG_Color *c"
.Pp
.nr nS 0
The
.Fn AG_IconNew
function allocates, initializes, and attaches a new
.Nm
widget without any associated surface.
There are currently no
.Fa flags
options defined.
.Pp
The
.Fn AG_IconFromSurface
variant also assigns a surface
.Fa s ,
and
.Fn AG_IconFromBMP
loads the surface from a bitmap file.
.Pp
.Fn AG_IconSetPadding
sets the padding around the surface in pixels.
.Pp
.Fn AG_IconSetSurface
changes the surface associated with an icon.
The
.Fn AG_IconSetSurfaceNODUP
variant does not create a copy of the surface.
.Pp
.Fn AG_IconSetText
arranges for the specified text string to be displayed under the icon.
.Pp
.Fn AG_IconSetBackgroundFill
enables or disables background color fill.
.Sh EVENTS
The
.Nm
widget does not generate any event.
.Sh EXAMPLES
See
.Pa tests/sockets.c
in the Agar source distribution.
.Sh SEE ALSO
.Xr AG_Intro 3 ,
.Xr AG_Socket 3 ,
.Xr AG_Surface 3 ,
.Xr AG_Widget 3 ,
.Xr AG_Window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.3.
