.\"	$Csoft: text.3,v 1.24 2005/05/11 15:16:00 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003, 2004, 2005 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd April 24, 2003
.Dt TEXT 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm AG_Text
.Nd agar font engine interface
.Sh SYNOPSIS
.Bd -literal
#include <agar/gui.h>
.Ed
.Sh DESCRIPTION
The
.Nm
interface uses an underlying font engine (such as FreeType) to render text.
.Sh INITIALIZATION
.nr nS 1
.Ft void
.Fn AG_TextParseFontSpec "const char *fontspec"
.Pp
.Ft int
.Fn AG_TextInit "enum text_engine te"
.Pp
.Ft void
.Fn AG_TextDestroy "void"
.nr nS 0
.Pp
The
.Fn AG_TextParseFontSpec
function parses a font specification of the form
.Sq face,size,style
(valid separators include
.Sq :,./ )
and assigns the default font.
This function is typically called prior to
.Fn AG_TextInit ,
to parse font specifications on the command line.
.Pp
The
.Fn AG_TextInit
function initializes the text subsystem using the given font engine:
.Bd -literal
enum text_engine {
	TEXT_ENGINE_FREETYPE,		/* FreeType */
	TEXT_ENGINE_BITMAP,		/* Fixed-size bitmap */
	TEXT_ENGINE_PIXMAP		/* Fixed-size pixmap */
};
.Ed
.Pp
.Fn AG_TextInit
selects the default font style by looking at the following
.Xr AG_Config 3
settings:
.Bl -tag -width "font-engine.default-style "
.It Va font-engine.default-font
This specifies the default font face to use.
With
.Dv TEXT_ENGINE_FREETYPE ,
this is the name of the font file to load.
With
.Dv TEXT_ENGINE_BITMAP
and
.Dv TEXT_ENGINE_PIXMAP ,
this is the name of the font bitmap file.
In both cases, the file should reside in one of the directories specified in
the
.Va font-path
.Xr AG_Config 3
setting.
.It Va font-engine.default-size
The default font size in points.
.It Va font-engine.default-style
The default font style, or flags, specified in hexadecimal format.
The meaning of these flags is specific to the font engine being used.
.El
.Pp
The
.Fn AG_TextDestroy
function frees all resources allocated by the font engine.
.Sh RENDERING
.nr nS 1
.Ft "SDL_Surface *"
.Fn AG_TextRenderUnicode "const char *font_name, int font_size, Uint32 color" "const Uint32 *ucs"
.Pp
.Ft "SDL_Surface *"
.Fn AG_TextRender "const char *font_name, int font_size, Uint32 color" "const char *text"
.Pp
.Ft "SDL_Surface *"
.Fn AG_TextRenderGlyph "const char *font_name, int font_size, Uint32 color" "Uint32 uch"
.Pp
.Ft "void"
.Fn AG_TextPrescaleUnicode "const Uint32 *ucs" "int *w" "int *h"
.Pp
.Ft "void"
.Fn AG_TextPrescale "const char *text" "int *w" "int *h"
.nr nS 0
.Pp
The
.Fn AG_TextRender
function renders UTF-8 text to a newly allocated surface.
.Fn AG_TextRenderUnicode
renders UCS-4 text to a newly allocated surface.
.Fn AG_TextRenderGlyph
renders an UCS-4 encoded Unicode character onto a new surface.
A
.Fa font_name
argument of NULL or a
.Fa font_size
argument of -1 indicates that the defaults should be used.
.Pp
The
.Fn AG_TextPrescale
and
.Fn AG_TextPrescaleUnicode
functions return the expected surface dimensions for the given text.
.Sh CANNED DIALOGS
.nr nS 1
.Ft "void"
.Fn AG_TextMsg "enum ag_text_msg_title title" "const char *format" "..."
.Pp
.Ft "void"
.Fn AG_TextTmsg "enum ag_text_msg_title title" "Uint32 expire" "const char *format" "..."
.Pp
.Ft "void"
.Fn AG_TextEditFloat "enum text_float_type type" "double *fp" "double min" "double max" "const AG_Unit *unit" "const char *format" "..."
.Pp
.Ft "void"
.Fn AG_TextEditString "char **buf" "size_t len" "const char *format" "..."
.nr nS 0
.Pp
The
.Fn AG_TextMsg
function displays a text message window containing the given
.Xr printf 3
formatted string, and an
.Sq OK
button.
The
.Fn AG_TextTmsg
variant displays the message for a period of time given in milliseconds.
.Fa title
is one of the following:
.Bd -literal
enum ag_text_msg_title {
	AG_MSG_ERROR,
	AG_MSG_WARNING,
	AG_MSG_INFO
};
.Ed
.Pp
The
.Fn AG_TextEditFloat
function displays a dialog asking for a floating-point value.
The
.Fa fp
argument is a pointer to the variable, while
.Fa min
and
.Fa max
define the acceptable range.
Unless
.Fa unit
is NULL, the argument indicates the unit system to use (as in
.Xr AG_Units 3 ) .
.Pp
Similarly,
.Fn AG_TextEditString
displays a dialog asking for a string, where
.Fa buf
is a pointer to the string buffer, and
.Fa len
is the size of the buffer.


.Sh TROUBLETONS
Something more sophisticated is needed to deal with unpredictable text surface
dimensions.
Currently,
.Fn AG_TextPrescale
is used prior to allocating fixed-size surfaces, but this is troublesome to
maintain with translations.
.Pp
.Fn AG_TextRenderGlyph
does not work.
.Sh SEE ALSO
.Xr AG_Intro 3 ,
.Xr AG_Config 3 ,
.Xr AG_Button 3 ,
.Xr AG_Combo 3 ,
.Xr AG_Label 3 ,
.Xr AG_Radio 3 ,
.Xr AG_Spinbutton 3 ,
.Xr AG_Statusbar 3 ,
.Xr AG_FSpinbutton 3 ,
.Xr AG_MFSpinbutton 3 ,
.Xr AG_Textbox 3 ,
.Xr AG_Titlebar 3 ,
.Xr AG_Tlist 3 ,
.Xr AG_UCombo 3 ,
.Xr AG_Widget 3
.Bd -literal
The FreeType project - http://www.freetype.org/
Unicode home page - http://www.unicode.org/
.Ed
.Sh HISTORY
The
.Nm
interface first appeared in Agar 1.0.
