.\"	$Csoft: combo.3,v 1.6 2005/05/24 08:12:48 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003, 2004, 2005 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd November 19, 2003
.Dt COMBO 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm combo
.Nd agar text input + drop-down menu widget
.Sh SYNOPSIS
.Bd -literal
#include <engine/widget/combo.h>
.Ed
.Sh DESCRIPTION
The
.Nm
widget is a composite widget that packs a
.Xr textbox 3
widget left to a
.Xr button 3 ,
which causes a
.Xr tlist 3
to be displayed when pressed.
The tlist disappears when an option is selected, and is directly accessed
as the
.Va list
member of the
.Nm
structure.
.Pp
.Sh INHERITANCE HIERARCHY
.Pp
.Xr AG_Object 3 ->
.Xr widget 3 ->
.Nm .
.Sh INITIALIZATION
.nr nS 1
.Ft "AG_Combo *"
.Fn AG_ComboNew "void *parent" "int flags" "const char *format" "..."
.Pp
.Ft "void"
.Fn AG_ComboInit "AG_Combo *combo" "const char *label" "int flags"
.nr nS 0
.Pp
The
.Fn AG_ComboNew
function allocates, initializes, and attaches a
.Nm
widget.
.Fn AG_ComboInit
initializes a
.Nm
widget.
The
.Fa label
argument defines the text to be displayed at the left of the textbox.
Acceptable
.Fa flags
include:
.Bd -literal
#define AG_COMBO_POLL	0x01	/* Polled list (AG_TLIST_POLL) */
#define AG_COMBO_TREE	0x02	/* Tree display (AG_TLIST_TREE) */
#define AG_COMBO_ANY_TEXT	0x04	/* Accept text not matching an item */
.Ed
.Sh ITEM SELECTION
.nr nS 1
.Ft void
.Fn combo_select "AG_Combo *combo" "AG_TlistItem *item"
.Pp
.Ft "AG_TlistItem *"
.Fn AG_ComboSelectPointer "AG_Combo *combo" "void *ptr"
.Pp
.Ft "AG_TlistItem *"
.Fn AG_ComboSelectText "AG_Combo *combo" "const char *text"
.nr nS 0
.Pp
The
.Fn combo_select
function sets the selection flag on the given
.Fa item .
.Pp
The
.Fn AG_ComboSelectPointer
function selects the first item with a user pointer value matching
.Fa ptr .
Similarly,
.Fn AG_ComboSelectText
selects the first item with a text string equal to
.Fa text .
.Pp
If the
.Dv AG_COMBO_POLL
option is set, both
.Fn AG_ComboSelectPointer
and
.Fn AG_ComboSelectText
will raise a
.Sq tlist-poll
event prior to making the selection.
.Sh EVENTS
The
.Nm
widget generates the following events:
.Pp
.Bl -tag -compact -width 2n
.It Fn combo-selected "AG_TlistItem *item"
An item was selected.
.It Fn combo-text-entry "const char *text"
The
.Dv AG_COMBO_ANY_TEXT
option is set and the user has entered a string
.Fa text
which does not match any item in the list.
.It Fn combo-text-unknown "const char *text"
The
.Dv AG_COMBO_ANY_TEXT
flag is not set and the user has entered a string
.Fa text
which does not match any item in the list.
.El
.Sh SEE ALSO
.Xr agar 3 ,
.Xr button 3 ,
.Xr textbox 3 ,
.Xr tlist 3 ,
.Xr widget 3 ,
.Xr window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.0.
