#	$Csoft: Makefile,v 1.3 2002/12/25 22:07:39 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

TTF=	LICENSE.ttf \
	dignity.ttf kingrich.ttf larabie.ttf pakenham.ttf suigener.ttf \
	zekton.ttf zerothre.ttf zerotwos.ttf zrnic.ttf
SHARE=	${TTF}

include ${TOP}/mk/csoft.lib.mk
