#	$Csoft: Makefile,v 1.1 2002/05/25 08:50:15 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

SHARE=	LICENSE.ttf \
	dignity.ttf kingrich.ttf larabie.ttf pakenham.ttf suigener.ttf \
	zekton.ttf zerothre.ttf zerotwos.ttf zrnic.ttf
SHAREDIR=${TTFDIR}

include ${TOP}/mk/csoft.lib.mk
