#	$Csoft: Makefile,v 1.2 2003/08/06 04:08:16 vedge Exp $

TOP=	..
include ${TOP}/Makefile.config

LIB=	intl
SRCS=	gettext.c textdomain.c
MAN3=	gettext.3

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/mk/csoft.man.mk
