#	$Csoft: Makefile,v 1.63 2004/04/10 02:36:38 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

XCF=	map-edition.xcf \
	map-cursors.xcf \
	object-editor.xcf \
	objects.xcf \
	vg.xcf

DEN=		icons.den
DEN_DIR=	engine/icons
DEN_NAME=	"Agar GUI icons"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2001, 2002, 2003, 2004 CubeSoft Communications, Inc"

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/dencomp/Makefile.inc
