#	$Csoft: Makefile,v 1.3 2003/08/06 04:11:31 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

LIB=	unicode
SRCS=	unicode.c ucslcpy.c ucslcat.c ucssep.c

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/mk/csoft.man.mk
