#	$Csoft: Makefile,v 1.2 2003/07/28 04:37:01 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

LIB=	unicode
SRCS=	unicode.c ucslcpy.c ucslcat.c ucssep.c
OBJS=	unicode.o ucslcpy.o ucslcat.o ucssep.o

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/mk/csoft.man.mk
