.\"
.\" Copyright (c) 2006-2007 Hypertriton, Inc.
.\" <http://www.hypertriton.com/>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd June 27, 2006
.Dt SG_CAMERA 3
.Os
.ds vT Agar-SG API Reference
.ds oS Agar-SG 1.0
.Sh NAME
.Nm SG_Camera
.Nd agar-sg camera
.Sh SYNOPSIS
.Bd -literal
#include <agar/sg.h>
.Ed
.Sh DESCRIPTION
A
.Nm
node defines a point of view inside a
.Xr SG 3
scene-graph.
When rendering a scene, the
.Xr SG_View 3
widget is associated with a
.Nm
node, which defines both the projection matrix and the initial OpenGL
modelview matrix.
.Pp
The
.Nm
class implements perspective, orthographic and user-specified projection modes.
.Sh INHERITANCE HIERARCHY
.Pp
.Xr SG_Node 3 ->
.Nm .
.Sh INITIALIZATION
.nr nS 1
.Ft "SG_Camera *"
.Fn SG_CameraNew "SG_Node *parent" "const char *name"
.Pp
.Ft "void"
.Fn SG_CameraInit "SG_Node *parent" "const char *name"
.Pp
.nr nS 0
The
.Fn SG_CameraNew
function allocates, initializes, and attaches a
.Nm
object.
.Fn SG_Init
initializes a
.Nm
structure.
.Sh PROJECTION TRANSFORMATIONS
.Pp
Projection transformations are used to map object coordinates to window
coordinates for two-dimensional display devices.
Each
.Nm
instance is associated with a projection transformation.
.Pp
.nr nS 1
.Ft "void"
.Fn SG_CameraGetProjection "SG_Camera *cam" "SG_Matrix *P"
.Pp
.Ft "void"
.Fn SG_CameraSetOrthographic "SG_Camera *cam"
.Pp
.Ft "void"
.Fn SG_CameraSetPerspective "SG_Camera *cam" "SG_Real fovY" "SG_Real aspect"
.Pp
.Ft "void"
.Fn SG_CameraSetUser "SG_Camera *cam" "const SG_Matrix *P"
.Pp
.Ft "void"
.Fn SG_CameraSetClipPlanes "SG_Camera *cam" "SG_Real zNear" "SG_Real zFar"
.Pp
.Ft "void"
.Fn SG_CameraProject "SG_Camera *cam"
.nr nS 0
.Pp
The
.Fn SG_CameraGetProjection
function returns the current projection matrix of
.Fa cam
into
.Fa P .
.Pp
The
.Fn SG_CameraSetOrthographic
function sets the projection matrix of
.Fa cam
to an orthographic projection matrix.
.Fn SG_CameraSetPerspective
selects a perspective matrix.
For perspective projections,
.Fa aspect
defines the aspect ratio (ratio of width to height) and
.Fa fovY
defines the field-of-view angle in degrees in the y direction.
.Pp
The
.Fn SG_CameraSetUser
function sets the projection matrix of
.Fa cam
to a user-specified matrix
.Fa P .
.Pp
The near and far clipping planes are defined by
.Fn SG_CameraSetClipPlanes .
.Fa zNear
and
.Fa zFar
represent the distance from the standard XY plane to the near and far clipping
planes.
.Pp
The
.Fn SG_CameraProject
function multiplies the current OpenGL matrix by the projection matrix
.Fa cam .
It is not necessary to invoke this function when using
.Xr SG_View 3 .
.Sh SEE ALSO
.Xr SG 3 ,
.Xr SG_Light 3 ,
.Xr SG_Matrix 3 ,
.Xr SG_Vector 3 ,
.Xr SG_View 3
.Sh HISTORY
The
.Nm
node first appeared in Agar-SG 1.0.
