/*
 * Copyright (c) 2007 Hypertriton, Inc. <http://hypertriton.com/>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * These functions implement placement of entities based on their constraints
 * with respect to either single entity or a set of two constrained entities.
 *
 * They are implemented as generic sketch instructions (which are usually
 * going to be generated by DOF analysis).
 */ 

#include <config/have_opengl.h>
#ifdef HAVE_OPENGL

#include <core/core.h>

#include "sk.h"
#include "sk_constraint.h"

static int
PtFromIncidentPt(SK_Constraint *ct, void *self, void *other)
{
	SK_MatrixCopy(self, other);
	return (0);
}

static int
PtFromIncidentLine(SK_Constraint *ct, void *self, void *other)
{
	SK_Point *p = self;
	SG_Vector v = SK_NodeCoords(p);
	SG_Vector p1 = SK_NodeCoords(SKLINE(other)->p1);
	SG_Vector p2 = SK_NodeCoords(SKLINE(other)->p2);
	SG_Real mag, u;

	mag = SG_VectorDistance(p2, p1);
	u = ( ((v.x - p1.x)*(p2.x - p1.x)) +
              ((v.y - p1.y)*(p2.y - p1.y)) ) / (mag*mag);
	if (u < 0.0 || u > 1.0) {
		v = p1;
	} else {
		v = SG_VectorAdd(p1, SG_VectorScale(SG_VectorSubp(&p2,&p1),u));
	}
	SK_Identity(p);
	SK_Translatev(p, &v);
	return (0);
}

static int
LineFromIncidentPt(SK_Constraint *ct, void *self, void *other)
{
	SK_Line *L = self;
	SG_Vector p1 = SK_NodeCoords(other);
	
	SK_Identity(L->p1);
	SK_Translatev(L->p1, &p1);

	p1.x += 1.0;					/* Arbitrary */
	SK_Identity(L->p2);
	SK_Translatev(L->p2, &p1);
	return (0);
}

static int
PtFromIncidentCircle(SK_Constraint *ct, void *self, void *other)
{
	SK_Point *p = self;
	SK_Circle *C1 = other;
	SG_Vector p1 = SK_NodeCoords(C1->p);
	
	SK_Identity(p);
	SK_Translatev(p, &p1);
	SK_Translate2(p, C1->r, 0.0);
	return (0);
}

static int
CircleFromIncidentPt(SK_Constraint *ct, void *self, void *other)
{
	SK_Circle *C = self;
	SG_Vector p1 = SK_NodeCoords(other);

	p1.x -= C->r;
	SK_Identity(C);
	SK_Translatev(C, &p1);
	return (0);
}

static int
PtFromDistantPt(SK_Constraint *ct, void *self, void *other)
{
	SG_Vector p1 = SK_NodeCoords(other);

	p1.x += ct->ct_distance;
	SK_Identity(self);
	SK_Translatev(self, &p1);
	return (0);
}

static int
PtFromDistantLine(SK_Constraint *ct, void *self, void *other)
{
	SG_Vector p1 = SK_NodeCoords(SKLINE(other)->p1);

	p1.x += ct->ct_distance;
	SK_Identity(self);
	SK_Translatev(self, &p1);
	return (0);
}

static int
LineFromDistantPt(SK_Constraint *ct, void *self, void *other)
{
	SK_Line *L = self;

	SK_MatrixCopy(L->p1, other);
	SK_MatrixCopy(L->p2, other);
	SK_Translate2(L->p2, 0.0, 1.0);				/* Arbitrary */
	return (0);
}

static int
LineFromDistantLine(SK_Constraint *ct, void *self, void *other)
{
	SK_Line *L = self;
	SK_Line *L1 = other;

	SK_MatrixCopy(L->p1, L1->p1);
	SK_MatrixCopy(L->p2, L1->p2);
	SK_Translate2(L->p1, ct->ct_distance, 0.0);
	SK_Translate2(L->p2, ct->ct_distance, 0.0);
	return (0);
}

static int
LineFromAngledLine(SK_Constraint *ct, void *self, void *other)
{
	SK_Line *L = self;
	SK_Line *L1 = other;

	SK_MatrixCopy(L->p1, L1->p1);
	SK_MatrixCopy(L->p2, L1->p2);
	SK_Rotatev(L->p1, ct->ct_angle, SG_K);
	SK_Rotatev(L->p2, ct->ct_angle, SG_K);
	return (0);
}

/*
 * Compute the position of a point relative to two fixed points from
 * distance/incidence constraints. This is a system of two quadratic
 * equations describing the intersection of two imaginary circles with
 * radii corresponding to the distances.
 */
static int
PtFrom2Pts(void *self, SK_Constraint *ct1, void *n1, SK_Constraint *ct2,
    void *n2)
{
	SG_Vector p1 = SK_NodeCoords(n1);
	SG_Vector p2 = SK_NodeCoords(n2);
	SG_Real d1 = (ct1->type == SK_DISTANCE) ? ct1->ct_distance : 0.0;
	SG_Real d2 = (ct2->type == SK_DISTANCE) ? ct2->ct_distance : 0.0;
	SG_Real d12 = SG_VectorDistancep(&p1, &p2);
	SG_Real a, h, b;
	SG_Vector p;

	dprintf("PtFrom2Pts(%s,[%f:%s],[%f:%s])\n",
	    SK_NodeName(self),
	    ct1->ct_distance, SK_NodeName(n1),
	    ct2->ct_distance, SK_NodeName(n2));

	if (d12 > (d1+d2)) {
		AG_SetError("Distances inconsistent (%f>(%f+%f))",
		    d12, d1, d2);
		return (-1);
	}
#if 0
	if (d12 < SG_Fabs(d1-d2)) {
		AG_SetError("Distances inconsistent (%f<abs(%f-%f))",
		    d12, d1, d2);
		return (-1);
	}
#endif

	a = (d1*d1 - d2*d2 + d12*d12) / (2.0*d12);
	h = SG_Sqrt(d1*d1 - a*a);
	p = SG_VectorLERP(p1, p2, a/d12);
	b = h/d12;

	SK_Identity(self);
	SK_Translate2(self, p.x - b*(p2.y-p1.y),
	                    p.y + b*(p2.x-p1.x));

	dprintf("p = %f,%f, a=%f, h=%f, b=%f", p.x, p.y, a, h, b);

	return (0);
}

/*
 * Compute the position of a point relative to a fixed point and a fixed
 * line from distance/incidence constraints. This is a system of one
 * linear and one quadratic equation, describing the intersection of a line
 * and a circle.
 */
static int
PtFromPtAndLine(void *self, SK_Constraint *ct1, void *n1,
    SK_Constraint *ct2, void *n2)
{
	return (0);
}

const SK_ConstraintPairFn skConstraintPairFns[] = {
	{ SK_COINCIDENT, "Point:*", "Point:*",	PtFromIncidentPt },
	{ SK_COINCIDENT, "Point:*", "Line:*",	PtFromIncidentLine },
	{ SK_COINCIDENT, "Point:*", "Circle:*",	PtFromIncidentCircle },
	{ SK_COINCIDENT, "Line:*",  "Point:*",	LineFromIncidentPt },
	{ SK_DISTANCE,	 "Point:*", "Point:*",	PtFromDistantPt },
	{ SK_DISTANCE,	 "Point:*", "Line:*",	PtFromDistantLine },
	{ SK_DISTANCE,	 "Line:*",  "Point:*",	LineFromDistantPt },
	{ SK_DISTANCE,	 "Line:*",  "Line:*",	LineFromDistantLine },
	{ SK_ANGLE,	 "Line:*",  "Line:*",	LineFromAngledLine },
};
const SK_ConstraintRingFn skConstraintRingFns[] = {
	{
		"Point:*",
		SK_CONSTRAINT_ANY, "Point:*",
		SK_CONSTRAINT_ANY, "Point:*",
		PtFrom2Pts
	}, {
		"Point:*",
		SK_CONSTRAINT_ANY, "Point:*",
		SK_CONSTRAINT_ANY, "Line:*",
		PtFromPtAndLine
	},
};

const int skConstraintPairFnCount = sizeof(skConstraintPairFns) /
                                    sizeof(skConstraintPairFns[0]);
const int skConstraintRingFnCount = sizeof(skConstraintRingFns) /
                                    sizeof(skConstraintRingFns[0]);

#endif /* HAVE_OPENGL */
