.\"	$Csoft: agar.3,v 1.47 2005/06/21 10:49:47 vedge Exp $
.\"
.\" Copyright (c) 2001, 2002, 2003, 2004 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\"	$OpenBSD: mdoc.template,v 1.6 2001/02/03 08:22:44 niklas Exp $
.\"
.Dd NOVEMBER 26, 2001
.Dt AG_INTRO 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm AG_Intro
.Nd agar introduction
.Sh DESCRIPTION
Agar is a portable and window-system independent graphics toolkit for SDL
and OpenGL. In addition to a fully functional GUI toolkit, a set of separate
higher-level graphics libraries are included in the distribution.
.Pp
.Sh CORE AGAR LIBRARY
.Bl -tag -width "AG_Timeout(3) " -compact
.It Xr AG_Core 3
Core Agar library initialization.
.It Xr AG_Gfx 3
Graphic resource management.
.It Xr AG_Object 3
Object linkage, memory management, persistence, dependencies and events.
.It Xr AG_Event 3
Event handling for objects.
.It Xr AG_Prop 3
Generic runtime properties for objects.
.It Xr AG_View 3
Interface to the graphics display.
.It Xr AG_Timeout 3
Timing-related routines.
.El
.Sh RASTER GRAPHICS LIBRARY (RG)
.Bl -tag -width "tileview(3) " -compact
.It Xr RG_Tileview
Display and edition of 2D vector and raster graphics.
.El
.Sh USER INTERFACE RELATED
.Bl -tag -width "window(3) " -compact
.It Xr AG_Text 3
High-level interface to font engine (ie. FreeType).
.It Xr AG_Units 3
Conversion between different unit systems.
.It Xr AG_Widget 3
Generic widget interface.
.It Xr AG_Window 3
Basic window widget; interface to built-in window manager.
.El
.Sh STANDARD WIDGETS
.Bl -tag -width "fspinbutton(3) " -compact
.It Xr AG_Pixmap 3
Displays arbitrary surfaces.
.It Xr AG_Box 3
Horizontal/vertical widget container.
.It Xr AG_Button 3
Generic push-button widget (boolean bindings).
.It Xr AG_Checkbox 3
Generic checkbox widget (boolean bindings).
.It Xr AG_Combo 3
Text input/drop-down menu widget.
.It Xr AG_FSpinbutton 3
Spinbutton with unit conversion (floating point bindings).
.It Xr AG_Graph 3
Plot a set of integral values.
.It Xr AG_HBox 3
Alternate interface to
.Xr AG_Box 3 .
.It Xr AG_HSVPal 3
Hue/saturation/value color picker widget.
.It Xr AG_Label 3
Display a string of text (static or polled).
.It Xr AG_MFSpinbutton 3
Spinbutton widget for tuples.
.It Xr AG_Palette 3
Edit a RGB color value (Uint32/SDL_PixelFormat bindings). Obsoleted
by
.Xr AG_HSVPal 3 ) .
.It Xr AG_Radio 3
Simple radio group widget (integral bindings).
.It Xr AG_Scrollbar 3
Horizontal or vertical scrollbar (integral range and value bindings).
.It Xr AG_Spinbutton 3
Spinbutton widget for integer values (integral bindings).
.It Xr AG_Tableview 3
Table display widget (either static or polled; trees supported).
.It Xr AG_Textbox 3
Text edition widget (string bindings, UTF-8 supported).
.It Xr AG_Tlist 3
Tree/list widget (either static or polled).
.It Xr AG_Toolbar 3
Button container specialized for use as a toolbar.
.It Xr AG_UCombo 3
Variant of
.Xr AG_Combo 3
which displays a button instead of a text input.
.It Xr AG_VBox 3
Alternate interface to
.Xr AG_Box 3 .
.El
.Bd -literal
http://www.libsdl.org/
http://www.opengl.org/
.Ed
