.\" Copyright (c) 2001-2007 Hypertriton, Inc. <http://hypertriton.com/>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd NOVEMBER 26, 2001
.Dt AG_INTRO 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm AG_Intro
.Nd agar introduction
.Sh DESCRIPTION
Agar is a set of libraries for developing graphical applications that are
portable to numerous platforms.
.Pp
.Sh AGAR-CORE
Agar-Core implements the
.Xr AG_Object 3
object system and provides portable interfaces to some operating system
services.
.Pp
.Bl -tag -width "AG_DataSource(3) " -compact
.It Xr AG_Config 3
Manage Agar configuration settings.
.It Xr AG_Core 3
Core Agar library initialization.
.It Xr AG_DataSource 3
Generic interface to different data sources.
.It Xr AG_Error 3
Error handling in Agar.
.It Xr AG_Object 3
The Agar object system.
.It Xr AG_Event 3
Event handling for objects.
.It Xr AG_Prop 3
Generic runtime properties for objects.
.It Xr AG_Threads 3
Portable threads interface.
.It Xr AG_Timeout 3
Timing-related routines.
.It Xr AG_Version 3
Datafile versioning functions.
.El
.Sh AGAR-GUI
Agar-GUI implements a set of widget and a built-in window system that are
independent of the underlying graphics API.
.Pp
.Bl -tag -width "AG_Window(3) " -compact
.It Xr AG_Colors 3
Color scheme interface.
.It Xr AG_Style 3
The high-level themeing API.
.It Xr AG_Text 3
Interface to font engine (i.e., FreeType or bitmap fonts).
.It Xr AG_Units 3
Conversion between different unit systems.
.It Xr AG_View 3
Low-level interface to the graphics display.
.It Xr AG_Widget 3
Generic widget interface.
.It Xr AG_Window 3
Basic window widget; interface to built-in window manager.
.El
.Sh AGAR-GUI WIDGETS
These are the standard Agar widget classes.
The widget API is open, so libraries and applications will frequently
implement new widgets (inheriting from existing widget classes is made
possible by the
.Xr AG_Object 3
system).
.Pp
.Bl -tag -width "AG_ObjectSelector(3) " -compact
.It Xr AG_Box 3
Horizontal/vertical widget container.
.It Xr AG_Button 3
Generic push-button widget (boolean bindings).
.It Xr AG_Checkbox 3
Generic checkbox widget (boolean bindings).
.It Xr AG_Combo 3
Text input/drop-down menu widget.
.It Xr AG_Console 3
Scrollable text console widget.
.It Xr AG_FileDlg 3
File selection widget.
.It Xr AG_Fixed 3
Container for fixed position/geometry widgets.
.It Xr AG_GLView 3
Low-level OpenGL context widget.
.It Xr AG_Graph 3
Graph display widget.
.It Xr AG_FixedPlotter 3
Plotter for integral values.
.It Xr AG_HBox 3
Alternate interface to
.Xr AG_Box 3 .
.It Xr AG_HSVPal 3
Hue/saturation/value color picker widget.
.It Xr AG_Icon 3
Drag-and-droppable object that can be inserted into
.Xr AG_Socket 3
widgets.
.It Xr AG_Label 3
Display a string of text (static or polled).
.It Xr AG_MFSpinbutton 3
Spinbutton widget for tuples (real-valued).
.It Xr AG_MPane 3
Standard single, dual, triple and quad paned view.
.It Xr AG_MSpinbutton 3
Spinbutton widget for tuples (integer-only).
.It Xr AG_Matview 3
Matrix viewer widget.
.It Xr AG_Menu 3
Menu widget.
.It Xr AG_Notebook 3
Notebook widget.
.It Xr AG_Numerical 3
Numerical input / spinbutton widget for floating-point and integer
values.
.It Xr AG_ObjectSelector 3
Selector for
.Xr AG_Object 3
trees.
.It Xr AG_Palette 3
Edit a RGB color value (Uint32/SDL_PixelFormat bindings). Obsoleted
by
.Xr AG_HSVPal 3 .
.It Xr AG_Pane 3
Dual paned view.
.It Xr AG_Pixmap 3
Displays arbitrary surfaces.
.It Xr AG_Radio 3
Simple radio group widget (integer bindings).
.It Xr AG_Scrollbar 3
Horizontal or vertical scrollbar (integral range and value bindings).
.It Xr AG_Separator 3
Cosmetic separator widget.
.It Xr AG_Socket 3
Placeholder for drag-and-droppable
.Xr AG_Icon 3
objects.
.It Xr AG_Spinbutton 3
Spinbutton widget for integer values.
Superceded by
.Xr AG_Numerical 3 .
.It Xr AG_Statusbar 3
Specialized statusbar widget.
.It Xr AG_Table 3
Table display widget (best for polling; no trees).
.It Xr AG_Tableview 3
Table display widget with tree support (static/dynamic cells).
.It Xr AG_Textbox 3
Text edition widget (string bindings, UTF-8 supported).
.It Xr AG_Tlist 3
Tree/list widget (either static or polled).
.It Xr AG_Toolbar 3
Specialized button container for toolbars.
.It Xr AG_UCombo 3
Variant of
.Xr AG_Combo 3
which displays a button instead of a text input.
.It Xr AG_VBox 3
Alternate interface to
.Xr AG_Box 3 .
.El
.Sh AGAR-SG
Agar-SG is a generic 3D geometry and graphics rendering engine.
Given an input of geometrical and scene information, Agar-SG is designed
to provide efficient space partitioning, high-quality rendering from any
viewpoint and generic solving of geometrical constraints between entities.
.Pp
.Bl -tag -width "SG_Matrix(3) " -compact
.It Xr SG 3
Scene graph object.
.It Xr SG_Camera 3
Viewpoint object.
.It Xr SG_Light 3
Light source object.
.It Xr SG_Matrix 3
Optimized 4x4 matrix routines.
.\" .It Xr SG_Vector 3
.\" Optimized vector routines.
.It Xr SG_View 3
Scene visualization widget.
.It Xr SK 3
Dimensioned 2D sketch with geometrical constraints.
.El
.Sh AGAR-VG
Agar-VG is a simple 2D vector graphics library which allows developers
to specify hierarchical sketches consisting of elements such as lines, curves
and text, with associated linear transformations.
It is well suited to applications such as technical simulations; applications
requiring dimensioned, constrained vector drawings should use the
.Xr SK 3
object instead.
.Pp
.Bl -tag -width "VG_View(3) " -compact
.It Xr VG 3
Vector drawing object.
.It Xr VG_View 3
Visualization widget.
.El
.Sh AGAR-RG
Agar-RG is a library for generating and manipulating raster graphics (either
static or animated) by compositing a set of graphical elements. It implements
a "smart" image format which allows directives, transformations and instancing
of graphical elements.
.Pp
.Bl -tag -width "RG_Animview (3) " -compact
.It Xr RG_Tileset 3
Package for graphics, animations and textures.
.It Xr RG_Tile 3
Surface generated from a set of instructions.
.It Xr RG_Texture 3
Tile reference with texturing settings.
.It Xr RG_Anim 3
Animation generated from a set of instructions.
.It Xr RG_Pixmap 3
Graphical surface used internally.
.\" .It Xr RG_Sketch 3
.\" Vector drawing used internally.
.It Xr RG_Feature 3
Generic graphical operation framework.
.It Xr RG_Tileview 3
Widget for graphics edition, generic tool framework with undo.
.\" .It Xr RG_Animview 3
.\" Widget for displaying animations.
.El
.\" .Sh AGAR-SC
.\" Agar-SC is a set of tools commonly needed in simulations, such as basic
.\" linear algebra routines, a parallel solver for large, sparse matrices and
.\" a set of useful visualization widgets.
.\" .Pp
.\" .Bl -tag -width "SC_Matview(3) " -compact
.\" .It Xr SC_Matrix 3
.\" Routines for m-by-n matrices.
.\" .It Xr SC_Vector 3
.\" Routines for vectors.
.\" .It Xr SC_Matview 3
.\" Matrix visualization widget.
.\" .It Xr SC_Plotter 3
.\" Widget for plotting functions and derivatives.
.\" .El
.Sh AGAR-MAP
Agar-MAP is a 2D tiling library aimed at isometric games, platform games
and scrollers.
It depends on Agar-RG for graphics.
.Pp
.Bl -tag -width "MAP_Actor(3) " -compact
.It Xr MAP 3
The basic 2D map object.
.It Xr MAP_Actor 3
Dynamic map object.
.It Xr MAP_View 3
Map visualization and edition widget.
.El
.\" .Sh AGAR-NET
.\" Agar-NET is a network communication package which includes a portable,
.\" thread-safe client library along with a server framework.
.\" The server framework supports two models of operation: multi-process and
.\" multi-thread.
.\" Agar-NET provides support for multiple authentication methods, structured
.\" queries, sessions and efficient data streaming to a large number of clients.
.\" .Pp
.\" .Bl -tag -width "NS(3) " -compact
.\" .It Xr NC 3
.\" The network client library.
.\" .It Xr NS 3
.\" The server library.
.\" .El
