/*	Public domain	*/

#ifndef _MK_HAVE_UNSIGNED_TYPEDEFS
# undef Uchar
# undef Uint
# undef Ulong
#endif

#ifdef _AGAR_DEFINED_CC_DECLS_
# undef _AGAR_DEFINED_CC_DECLS_
# undef __BEGIN_DECLS
# undef __END_DECLS
#endif
#ifdef _AGAR_DEFINED_MAXPATHLEN_
# undef _AGAR_DEFINED_MAXPATHLEN_
# undef MAXPATHLEN
#endif
#ifdef _AGAR_DEBUG_
# undef _AGAR_DEBUG_
# undef DEBUG
#endif
#ifdef _AGAR_LOCKDEBUG_
# undef _AGAR_LOCKDEBUG_
# undef LOCKDEBUG
#endif
#ifdef _AGAR_THREADS_
# undef _AGAR_THREADS_
# undef THREADS
#endif
#ifdef _AGAR_THREADS_
# undef _AGAR_THREADS_
# undef THREADS
#endif
#ifdef _AGAR_HAVE_SYS_TYPES_H_
# undef _AGAR_HAVE_SYS_TYPES_H_
# undef _MK_HAVE_SYS_TYPES_H
#endif
#ifdef _AGAR_HAVE_64BIT_H_
# undef _AGAR_HAVE_64BIT_H_
# undef HAVE_64BIT
#endif
#ifdef _AGAR_HAVE_LONG_DOUBLE_H_
# undef _AGAR_HAVE_LONG_DOUBLE_H_
# undef HAVE_LONG_DOUBLE
#endif
#ifdef _AGAR_HAVE_STDLIB_H_
# undef _AGAR_HAVE_STDLIB_H_
# undef _MK_HAVE_STDLIB_H
#endif
#ifdef _AGAR_HAVE_UNISTD_H_
# undef _AGAR_HAVE_UNISTD_H_
# undef _MK_HAVE_UNISTD_H
#endif
#ifdef _AGAR_HAVE_UNSIGNED_TYPEDEFS_
# undef _AGAR_HAVE_UNSIGNED_TYPEDEFS_
# undef _MK_HAVE_UNSIGNED_TYPEDEFS
#endif
#ifdef _AGAR_HAVE_BOUNDED_ATTRIBUTE_
# undef _AGAR_HAVE_BOUNDED_ATTRIBUTE_
# undef HAVE_BOUNDED_ATTRIBUTE
#endif
#ifdef _AGAR_HAVE_FORMAT_ATTRIBUTE_
# undef _AGAR_HAVE_FORMAT_ATTRIBUTE_
# undef HAVE_FORMAT_ATTRIBUTE
#endif
#ifdef _AGAR_HAVE_NONNULL_ATTRIBUTE_
# undef _AGAR_HAVE_NONNULL_ATTRIBUTE_
# undef HAVE_NONNULL_ATTRIBUTE
#endif
#ifdef _AGAR_HAVE_PACKED_ATTRIBUTE_
# undef _AGAR_HAVE_PACKED_ATTRIBUTE_
# undef HAVE_PACKED_ATTRIBUTE
#endif
#ifdef _AGAR_HAVE_ALIGNED_ATTRIBUTE_
# undef _AGAR_HAVE_ALIGNED_ATTRIBUTE_
# undef HAVE_ALIGNED_ATTRIBUTE
#endif
