#	$Csoft: Makefile,v 1.1 2004/11/23 02:32:39 vedge Exp $

TOP=	..
include ${TOP}/Makefile.config

LIB=		mat
LIB_SHARED=	Yes
LIB_STATIC=	No

SRCS=	mat.c lu.c vec.c veci.c gaussj.c

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
