#	$Csoft: Makefile,v 1.19 2004/03/10 16:58:36 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

LIB=		tool
LIB_SHARED=	Yes
LIB_STATIC=	No

SRCS=	eraser.c fill.c flip.c magnifier.c merge.c propedit.c \
	resize.c select.c shift.c stamp.c invert.c

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
