.\"	$Csoft: agar.3,v 1.8 2002/09/16 06:10:51 vedge Exp $
.\"
.\" Copyright (c) 2001, 2002 CubeSoft Communications, Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistribution of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Neither the name of CubeSoft Communications, nor the names of its
.\"    contributors may be used to endorse or promote products derived from
.\"    this software without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\"	$OpenBSD: mdoc.template,v 1.6 2001/02/03 08:22:44 niklas Exp $
.\"
.Dd NOVEMBER 26, 2001
.Dt AGAR 3
.Os
.Sh NAME
.Nm agar
.Nd game engine
.Sh DESCRIPTION
.Nm
is an object-oriented graphical game engine.
.Sh LOCKING CONSTRAINTS
The engine defines macros around pthread locking calls, to catch errors.
.Pp
Locking constraints must be clearly commented at the beginning of each
function, whether it is assumed that a lock is held, or whether the
calling thread must not hold a lock.
Recursive mutex locks are not worth mentioning.
.Pp
Every subsystem must hide locking constraints from the other subsystems
by providing a well-defined interface.
.Sh OBJECT EXISTENCE PROTECTION
.Bl -bullet -width 4n
The global, recursive mutex
.Va world->lock ,
ensures that no game object is attached/detached, as long as it is locked.
.It
Since the rendering routines must frequently lock the object list when
resolving node references, the object list
.Va world->wobjs
and the object count
.Va world->nobjs
are visible to high-level code, and protected by the
.Va world->lock
mutex.
.It
The
.Va world->lock
mutex protects the existence of objects.
To avoid a race inside the async event handler, between entry and acquisition
of
.Va world->lock
(where another thread may be able to detach the object before the lock is
acquired), async event handlers must ensure that the object still exists
in the
.Va world->objs
list once the
.Va world->lock
mutex is acquired.
.El
.Sh SEE ALSO
.Xr fobj 3 ,
.Xr object 3 ,
.Xr map 3 ,
.Xr widget 3 ,
.Xr window 3 ,
