.\"	$Csoft: view.3,v 1.11 2002/12/31 05:45:56 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 23, 2002
.Dt VIEW 3
.Os
.Sh NAME
.Nm view
.Nd agar graphic engine
.Sh SYNOPSIS
.Bd -literal
#include <engine/view.h>
.Ed
.Sh DESCRIPTION
The Agar
.Nm
layer manages the video display and maintains a list of windows.
.Sh INITIALIZATION
.nr nS 1
.Ft "int"
.Fn view_init "gfx_engine_t engine"
.Pp
.Ft "void"
.Fn view_destroy "struct viewport *view"
.Pp
.Ft "int"
.Fn view_set_refresh "int min_delay" "int max_delay"
.nr nS 0
.Pp
The
.Fn view_init
function initializes the graphic engine, return 0 on success and -1 on failure.
.Fa engine
is one of:
.Bd -literal
typedef enum {
	GFX_ENGINE_GUI,			/* Direct GUI */
	GFX_ENGINE_TILEBASED,		/* Direct 2D tile-based */
	GFX_ENGINE_GL			/* OpenGL (if available) */
} gfx_engine_t;
.Ed
.Pp
The
.Fn view_set_refresh
functions sets the minimum and maximum display refresh rate, returning 0 on
success and -1 on failure.
.Sh WINDOW SYSTEM
.nr nS 1
.Ft "void"
.Fn view_attach "struct window *child"
.Pp
.Ft "void"
.Fn view_detach "struct window *child"
.Pp
.Ft void
.Fn view_detach_queued "void"
.nr nS 0
.Pp
The
.Fn view_attach
function attaches the window pointed to by
.Fa child
to the view.
The
.Fn view_detach
function detaches the window pointed to by
.Fa child
from the view by adding it to the detach queue.
The detachment will be performed later by
.Fa view_detach_queued .
.Sh VIDEO SURFACES
.nr nS 1
.Ft "SDL_Surface *"
.Fn view_surface "int flags" "int width" "int height"
.Pp
.Ft "SDL_Surface *"
.Fn view_scale_surface "SDL_Surface *source" "Uint16 w" "Uint16 h"
.Pp
.Ft void
.Fn VIEW_UPDATE "SDL_Rect rd"
.nr nS 0
.Pp
The
.Fn view_surface
function returns a newly allocated
.Xr SDL_Surface 3
adapted to the current display mode.
.Pp
The
.Fn view_scale_surface
function returns a pointer to a
.Xr SDL_Surface 3
structure which holds a copy of
.Fa source ,
bitmap-scaled to
.Fa w
by
.Fa h
pixels.
.Pp
The
.Fn VIEW_UPDATE
macro copies
.Fa rd
to the dirty rectangle array the event loop will pass to
.Xr SDL_UpdateRects 3
when the display is refreshed.
.Sh SEE ALSO
.Xr agar 3 ,
.Xr rootmap 3 ,
.Xr window 3 ,
.Xr SDL_SetVideoMode 3 ,
.Xr SDL_WM_SetCaption 3 ,
.Xr SDL_SetCursor 3 ,
.Xr SDL_CreateRGBSurface 3
.Sh HISTORY
The
.Nm
interface first appeared in AGAR 1.0
