.\"	$Csoft: mapview.3,v 1.1 2005/04/14 06:20:45 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003, 2004, 2005 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 20, 2002
.Dt MAPEDIT 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm mapview
.Nd agar map display/edition widget
.Sh SYNOPSIS
.Bd -literal
#include <engine/map/mapview.h>
.Ed
.Sh DESCRIPTION
The
.Nm
widget displays a portion of a
.Xr map 3
structure.
.Nm
also offers an interface for different types of graphical edition tools.
.Pp
Although the edition interface was originally intended for tile-based level
edition tools, it was extended to include lower-level events, and is now used
by
.Xr vg 3
for the edition of vector graphics (in which case the
.Xr map 3
displayed by
.Nm
is generated by the raster engine).
.Sh INITIALIZATION
.nr nS 1
.Ft struct mapview *
.Fn mapview_new "void *parent" "struct map *map" "int flags" "struct toolbar *toolbar" "struct statusbar *statbar"
.Pp
.Ft void
.Fn mapview_init "struct mapview *mv" "struct map *map" "int flags" "struct toolbar *toolbar" "struct statusbar *statbar"
.Pp
.Ft void
.Fn mapview_prescale "struct mapview *mv" "int w" "int h"
.Pp
.Ft void
.Fn mapview_center "struct mapview *mv" "int x" "int y"
.Pp
.Ft void
.Fn mapview_set_scale "struct mapview *mv" "u_int zoom"
.nr nS 0
.Pp
The
.Fn mapview_new
function allocates, initializes, and attaches a
.Nm
widget.
The
.Fn mapview_init
function initializes a
.Nm
widget displaying the given
.Fa map .
The
.Fa flags
may include:
.Bd -literal
#define MAPVIEW_EDIT	  0x01	/* Mouse/keyboard edition */
#define MAPVIEW_GRID	  0x02	/* Display the grid */
#define MAPVIEW_PROPS	  0x04	/* Display node properties */
#define MAPVIEW_CENTER	  0x08	/* Request initial centering */
#define MAPVIEW_NO_CURSOR 0x10	/* Disable the cursor */
.Ed
.Pp
If
.Fa toolbar
is not NULL, the
.Nm
will automatically create buttons in it for each tool registered with
.Fn mapview_reg_tool .
.Pp
The
.Dv MAPVIEW_EDIT
flag enables write operations on the map, assuming the level editor,
.Xr mapedit 3 ,
is initialized.
.Pp
The
.Fn mapview_prescale
function arranges for the
.Nm
to reserve enough space to display
.Fa w
by
.Fa h
nodes at the initial sizing stage.
.Pp
The
.Fn mapview_center
function centers the view around the node at
.Fa x ,
.Fa y .
The
.Fn mapview_set_scale
function sets the scaling factor to
.Fa zoom ,
given in % of the default tile geometry.
.Sh SELECTIONS
.nr nS 1
.Ft void
.Fn mapview_set_selection "struct mapview *mv" "int x" "int y" "int w" "int h"
.Pp
.Ft int
.Fn mapview_get_selection "struct mapview *mv" "int *x" "int *y" "int *w" "int *h"
.Pp
.nr nS 0
The
.Fn mapview_set_selection
function sets the active selection to
.Fa w
by
.Fa h
nodes at map position
.Fa x ,
.Fa y .
.Fn mapview_set_selection
also disables any mouse selection in progress.
.Pp
The
.Fn mapview_get_selection
returns 1 if there is an active selection or 0 if there is none.
If there is no selection, no value is written to
.Fa x ,
.Fa y ,
.Fa w
and
.Fa h .
.Sh EXTENSIONS
.nr nS 1
.Ft void
.Fn mapview_reg_tool "struct mapview *mv" "const struct tool *toolspec"
.Pp
.Ft void
.Fn mapview_reg_draw_cb "struct mapview *mv" "void (*f)(struct mapview *mv, void *p)"
.nr nS 0
.Pp
The
.Nm
widget provides a generic interface for tools that must accomplish
diverse map operations.
.Fn mapview_reg_tool
registers a tool for use from a
.Nm .
.Fa toolspec
is assumed to point to a
.Ft tool
structure with the following fields properly initialized:
.Bd -literal
struct tool {
	const char *name;		/* Name of the tool */
	const char *desc;		/* Short description */
	int icon;			/* Icon (-1 = none) */
	int cursor_index;		/* Static cursor (-1 = none) */

	void (*init)(struct tool *t);
	void (*destroy)(struct tool *t);
	int  (*load)(struct tool *t, struct netbuf *b);
	int  (*save)(struct tool *t, struct netbuf *b);
	int  (*cursor)(struct tool *t, SDL_Rect *r);
	void (*effect)(struct tool *t, struct node *n);
	void (*mousemotion)(struct tool *t, int x, int y, int xrel,
	                    int yrel, int xo, int yo, int xorel,
			    int yorel, int button_state);
	void (*mousebuttondown)(struct tool *t, int x, int y, int xoff,
	                        int yoff, int button);
	void (*mousebuttonup)(struct tool *t, int x, int y, int xoff,
	                      int yoff, int button);
	void (*keydown)(struct tool *t, int ksym, int kmod);
	void (*keyup)(struct tool *t, int ksym, int kmod);
};
.Ed
.Pp
The
.Fn init ,
.Fn destroy ,
.Fn load
and
.Fn save
operations are used to initialize, free, save and restore any private data
structures needed by the tool.
.Pp
The
.Fn cursor
operation is expected to draw the current cursor at the screen coordinates
given by the
.Xr SDL_Rect
argument.
.Pp
The
.Fn effect
operation is executed on mouse click events, and on mouse motion events where
the relative map (node) coordinates are >|1|.
Typically, simple tools that perform node-specific operations such as the
.Sq stamp
and
.Sq eraser
tools will use this operation.
.Pp
Tools that perform more complex operations (such as vector graphics
manipulations) will generally use the lower-level
.Fn mousemotion ,
.Fn mousebuttondown ,
.Fn mousebuttonup ,
.Fn keydown
and
.Fn keyup
operations.
.Pp
The
.Fn mapview_reg_draw_cb
function registers a function to invoke every time the
.Nm
widget is redrawn.
For instance, the
.Xr vg 3
subsystem uses this interface to register a function which performs
rasterization if the vector drawing's
.Va redraw
flag is set.
.Sh EVENTS
The
.Nm
widget reacts to the following events:
.Pp
.Bl -tag -width 25n
.It widget-lostfocus
Stop any zooming in progress.
.It window-mousebuttondown
The right mouse button enables scrolling.
The left mouse button invokes the current tool, if
.Dv MAPVIEW_EDIT
is set.
.It window-mousebuttonup
Stop scrolling or terminate a selection.
.It window-mousemotion
If the right mouse button is held, pan the view.
If a mouse selection is in progress, adjust the position relative to
the selection origin.
In edition mode, call current tool if the left mouse button is held,
or adjust the centering if the middle mouse button is held.
.It window-keydown
The default key bindings are:
.Bl -tag -width "SDLK_EQUALS " -compact
.It Dv SDLK_EQUALS
Increment the zoom.
.It Dv SDLK_MINUS
Decrement the zoom.
.It Dv SDLK_[01]
Zoom to 1:1 (no scaling).
.It Dv SDLK_[2-9]
Zoom to a predefine value.
.It Dv SDLK_o
Center around the map origin.
.El
.It window-keyup
Stop any zooming in progress
.El
.Pp
The
.Nm
widget generates the following events:
.Pp
.Bl -tag -compact -width 2n
.It Fn mapview-dblclick "int button" "int x" "int y" "int xoff" "int yoff"
The user double clicked over the given tile.
.El
.Sh SEE ALSO
.Xr agar 3 ,
.Xr map 3 ,
.Xr mapedit 3 ,
.Xr vg 3 ,
.Xr widget 3 ,
.Xr window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.0.
