/*	Public domain	*/

#undef HAVE_ALIGNED_ATTRIBUTE
#undef HAVE_BOUNDED_ATTRIBUTE
#undef HAVE_CONST_ATTRIBUTE
#undef HAVE_DEPRECATED_ATTRIBUTE
#undef HAVE_FORMAT_ATTRIBUTE
#undef HAVE_NONNULL_ATTRIBUTE
#undef HAVE_NORETURN_ATTRIBUTE
#undef HAVE_PACKED_ATTRIBUTE
#undef HAVE_PURE_ATTRIBUTE
#undef HAVE_WARN_UNUSED_RESULT_ATTRIBUTE

#undef ALIGNED_ATTRIBUTE
#undef BOUNDED_ATTRIBUTE
#undef CONST_ATTRIBUTE
#undef DEPRECATED_ATTRIBUTE
#undef FORMAT_ATTRIBUTE
#undef NONNULL_ATTRIBUTE
#undef NORETURN_ATTRIBUTE
#undef PACKED_ATTRIBUTE
#undef PURE_ATTRIBUTE
#undef WARN_UNUSED_RESULT_ATTRIBUTE
#undef UNUSED_VARIABLE_ATTRIBUTE
