/*	$Csoft$	*/
/*	Public domain	*/

#ifdef _AGAR_DEFINED_CC_DECLS_
# undef _AGAR_DEFINED_CC_DECLS_
# undef __BEGIN_DECLS
# undef __END_DECLS
#endif
#ifdef _AGAR_DEFINED_MAXPATHLEN_
# undef _AGAR_DEFINED_MAXPATHLEN_
# undef MAXPATHLEN
#endif
#ifdef _AGAR_THREADS_
# undef _AGAR_THREADS_
# undef THREADS
#endif
#ifdef _AGAR_HAVE_SYS_TYPES_H_
# undef _AGAR_HAVE_SYS_TYPES_H_
# undef HAVE_SYS_TYPES_H
#endif
#ifdef _AGAR_BSD_SOURCE_NEEDED_
# undef _AGAR_BSD_SOURCE_NEEDED_
# undef BSD_SOURCE_NEEDED
#endif
#ifdef _AGAR_BSD_TYPES_NEEDED_
# undef _AGAR_BSD_TYPES_NEEDED_
# undef BSD_TYPES_NEEDED
#endif
#ifdef _AGAR_HAVE_OPENGL_
# undef _AGAR_HAVE_OPENGL_
# undef HAVE_OPENGL
#endif
#ifdef _AGAR_HAVE_BOUNDED_ATTRIBUTE_
# undef _AGAR_HAVE_BOUNDED_ATTRIBUTE_
# undef HAVE_BOUNDED_ATTRIBUTE
#endif
#ifdef _AGAR_HAVE_FORMAT_ATTRIBUTE_
# undef _AGAR_HAVE_FORMAT_ATTRIBUTE_
# undef HAVE_FORMAT_ATTRIBUTE
#endif
#ifdef _AGAR_HAVE_NONNULL_ATTRIBUTE_
# undef _AGAR_HAVE_NONNULL_ATTRIBUTE_
# undef HAVE_NONNULL_ATTRIBUTE
#endif
