#!/bin/sh

exec 2>/dev/null
cache=0

sys="$1"
case "$sys" in
  SYSDEP_OS_DARWIN)
    cache="`sysctl hw.cacheline | awk '{print $2}'`"
    ;; 
esac

if [ -f ${SYSDEP_DIR_RELATIVE}./sd-cpuidx86 ]
then
  cache=`${SYSDEP_DIR_RELATIVE}./sd-cpuidx86 cacheline`
fi

if [ ! -z "${cache}" ]
then
  echo "$cache"
else
  echo 0
fi
