TOP=	../..
include ${TOP}/Makefile.config

XCF=	map-edition.xcf \
	object-editor.xcf \
	objects.xcf \
	vg.xcf \
	vg-snap.xcf \
	eda.xcf \
	rg.xcf \
	anim.xcf \
	symbols.xcf \
	arrow.xcf \
	window.xcf

DEN=		core-icons.den
DEN_NAME=	"Agar-Core Icons"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2001-2007 Hypertriton, Inc"

include ${TOP}/mk/build.den.mk
