/* Agar icon reference file */
/* Generated by agarpaint 1.1 */

#include "begin_code.h"
__BEGIN_DECLS
extern AG_StaticIcon vgIconPoints;
extern AG_StaticIcon vgIconLine;
extern AG_StaticIcon vgIconCircle;
extern AG_StaticIcon vgIconBezier;
extern AG_StaticIcon vgIconBlock;
extern AG_StaticIcon vgIconText;
extern AG_StaticIcon vgIconSnapFree;
extern AG_StaticIcon vgIconSnapRint;
extern AG_StaticIcon vgIconSnapGrid;
extern AG_StaticIcon vgIconSnapEndpt;
extern AG_StaticIcon vgIconSnapEndptDist;
extern AG_StaticIcon vgIconSnapClosest;
extern AG_StaticIcon vgIconSnapCenterPt;
extern AG_StaticIcon vgIconSnapMiddlePt;
extern AG_StaticIcon vgIconSnapIntsectAuto;
extern AG_StaticIcon vgIconSnapIntsectManual;
extern AG_StaticIcon vgIconPolygon;
extern AG_StaticIcon vgIconDrawing;
extern AG_StaticIcon vgIconProximity;
__END_DECLS
#include "close_code.h"
