#	$Csoft: Makefile,v 1.1 2003/09/07 00:24:09 vedge Exp $

TOP=../..
include ${TOP}/Makefile.config

LIB=		input
LIB_SHARED=	Yes
LIB_STATIC=	No

SRCS=	joy.c kbd.c mouse.c
CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
