TOP=	../..
include ${TOP}/Makefile.config

PROJECT=	install-agartest
PROJDIR=	ProjectFiles
PROJINCLUDES=	configure.lua
PROJFILES=	windows:vs2005::

PROG=		install-agartest
PROG_TYPE=	"CLI"
PROG_GUID=	"fd6c8252-8b4d-11ea-bb09-ac9e17b8d45b"
SRCS=		install-agartest.c

include ${TOP}/mk/build.prog.mk
