#	$Csoft: Makefile,v 1.5 2003/03/05 18:27:03 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

SUBDIR=	loader

LIB=	media
SRCS=	art.c
OBJS=	art.o

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/mk/csoft.man.mk
