#	$Csoft: Makefile,v 1.12 2004/11/25 02:49:01 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

LIB=		ag_sgimport
LIB_SHARED=	Yes
LIB_STATIC=	No

SRCS=	ply.c
CFLAGS+=${SDL_CFLAGS} ${AGAR_CFLAGS} -I..

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/mk/csoft.man.mk
