#!/bin/sh

exec 1> "$1"

args=""
path="${SYSDEP_STDLIB}"
lib="libSDLmain.a"

case ${SYSDEP_OS} in
  SYSDEP_OS_DARWIN)
    if [ -d "/Library/Frameworks/SDL.framework" ]
    then
      ${SYSDEP_INFO} "using SDL frameworks"
      args="-bind_at_load"    # darwin linker bug
      args="${args} -framework SDL -framework Cocoa -framework OpenGL -lobjc"
      echo "${args}"
      exit 0
    else
      ${SYSDEP_INFO} "using SDL 'unix style'" 
    fi
    ;;
  *)
    ;;
esac

FLAGS=`${SYSDEP_TRY_CONFIG_BIN} "sdl-config" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${args}
  exit 0
fi
${SYSDEP_ERROR} "config binary failed"

FLAGS=`${SYSDEP_TRY_PKG_CONFIG} "${pkg}" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${args}
  exit 0
else
  ${SYSDEP_ERROR} "pkg-config failed"
fi

FLAGS=`${SYSDEP_TRY_MANUAL} "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  case ${SYSDEP_OS} in
    SYSDEP_OS_DARWIN)
      echo ${args}
      exit 0
      ;;
    *)
      echo ${FLAGS} ${args}
      exit 0
      ;;
    esac
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
