TOP=	..
include ${TOP}/Makefile.config

XGETTEXT_FLAGS=	--no-location --from-code=UTF-8

DOMAIN=	agar
POS=	fr.po no.po
MOS=	fr.mo no.mo

ENABLE_NLS=yes
HAVE_GETTEXT=yes

include ${TOP}/mk/build.po.mk
