#	$Csoft: Makefile,v 1.4 2003/08/13 01:47:35 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

LIB=		unicode
LIB_SHARED=	Yes
LIB_STATIC=	No

SRCS=	unicode.c ucslcpy.c ucslcat.c ucssep.c

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/mk/csoft.man.mk
