/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Agar.xs. Do not edit this file, edit Agar.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Agar.xs"
/*
 * Copyright (c) 2008 Hypertriton, Inc. <http://hypertriton.com/>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Perl interface to the Agar GUI toolkit.
 */

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <agar/core.h>
#include <agar/gui.h>
#include "perl_agar.h"

extern XS(boot_Agar__PixelFormat);
extern XS(boot_Agar__Surface);
extern XS(boot_Agar__Window);

#line 52 "Agar.c"

XS(XS_Agar_Version); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar_Version)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Agar::Version()");
    {
#line 53 "Agar.xs"
	AG_AgarVersion v;
#line 63 "Agar.c"
	SV *	RETVAL;
#line 55 "Agar.xs"
	AG_GetVersion(&v);
	RETVAL = newSVpvf("%d.%d.%d", v.major, v.minor, v.patch);
#line 68 "Agar.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Agar_Release); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar_Release)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Agar::Release()");
    {
#line 63 "Agar.xs"
	AG_AgarVersion v;
#line 85 "Agar.c"
	SV *	RETVAL;
#line 65 "Agar.xs"
	AG_GetVersion(&v);
	RETVAL = newSVpv(v.release,0);
#line 90 "Agar.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Agar_SetError); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar_SetError)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Agar::SetError(msg)");
    {
	const char *	msg = (const char *)SvPV_nolen(ST(0));
#line 74 "Agar.xs"
	AG_SetError("%s", msg);
#line 108 "Agar.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Agar_GetError); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar_GetError)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Agar::GetError()");
    {
	SV *	RETVAL;
#line 79 "Agar.xs"
	RETVAL = newSVpv(AG_GetError(),0);
	SvUTF8_on(RETVAL);
#line 125 "Agar.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Agar_InitCore); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar_InitCore)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: Agar::InitCore(progName, ...)");
    {
	const char *	progName = (const char *)SvPV_nolen(ST(0));
#line 88 "Agar.xs"
	const AP_FlagNames flagNames[] = {
		{ "verbose", AG_CORE_VERBOSE },
		{ NULL,      0 }
	};
	Uint flags = 0;
#line 147 "Agar.c"
	int	RETVAL;
	dXSTARG;
#line 94 "Agar.xs"
	if (items == 2) {
		if (SvTYPE(SvRV(ST(1))) != SVt_PVHV) {
			Perl_croak("Usage: Agar::InitCore(progName,[{opts}])");
		}
		AP_MapHashToFlags(SvRV(ST(1)), flagNames, &flags);
	} else if (items != 1) {
		Perl_croak("Usage: Agar::InitCore(progName,[{opts}])");
	}
	RETVAL = (AG_InitCore(progName, flags) == 0);
#line 160 "Agar.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar_InitVideo); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar_InitVideo)
{
    dXSARGS;
    {
	int	w;
	int	h;
	int	bitsPerPixel;
#line 112 "Agar.xs"
	const AP_FlagNames flagNames[] = {
		{ "hwSurface",   AG_VIDEO_HWSURFACE },
		{ "asyncBlit",   AG_VIDEO_ASYNCBLIT },
		{ "anyFormat",   AG_VIDEO_ANYFORMAT },
		{ "hwPalette",   AG_VIDEO_HWPALETTE },
		{ "doubleBuf",   AG_VIDEO_DOUBLEBUF },
		{ "fullScreen",  AG_VIDEO_FULLSCREEN },
		{ "resizable",   AG_VIDEO_RESIZABLE },
		{ "noFrame",     AG_VIDEO_NOFRAME },
		{ "bgPopupMenu", AG_VIDEO_BGPOPUPMENU },
		{ "openGL",      AG_VIDEO_OPENGL },
		{ "openGLOrSDL", AG_VIDEO_OPENGL_OR_SDL },
		{ "noBgClear",   AG_VIDEO_NOBGCLEAR },
		{ NULL,          0 }
	};
	Uint flags = 0;
#line 192 "Agar.c"
	int	RETVAL;
	dXSTARG;

	if (items < 1)
	    w = 640;
	else {
	    w = (int)SvIV(ST(0));
	}

	if (items < 2)
	    h = 480;
	else {
	    h = (int)SvIV(ST(1));
	}

	if (items < 3)
	    bitsPerPixel = 32;
	else {
	    bitsPerPixel = (int)SvIV(ST(2));
	}
#line 129 "Agar.xs"
	if ((items == 4 && SvTYPE(SvRV(ST(3))) != SVt_PVHV) || items > 4) {
		Perl_croak("Usage: Agar::InitVideo(w,h,bitsPerPixel,[{opts}])");
	}
	if (items == 4) {
		AP_MapHashToFlags(SvRV(ST(3)), flagNames, &flags);
	}
	RETVAL = (AG_InitVideo(w, h, bitsPerPixel, flags) == 0);
#line 221 "Agar.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar_EventLoop); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar_EventLoop)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Agar::EventLoop()");
    {
#line 142 "Agar.xs"
	AG_EventLoop();
#line 237 "Agar.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Agar_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar_DESTROY)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Agar::DESTROY()");
    {
#line 147 "Agar.xs"
	AG_Destroy();
#line 252 "Agar.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Agar); /* prototype to pass -Wmissing-prototypes */
XS(boot_Agar)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Agar::Version", XS_Agar_Version, file);
        newXS("Agar::Release", XS_Agar_Release, file);
        newXS("Agar::SetError", XS_Agar_SetError, file);
        newXS("Agar::GetError", XS_Agar_GetError, file);
        newXS("Agar::InitCore", XS_Agar_InitCore, file);
        newXS("Agar::InitVideo", XS_Agar_InitVideo, file);
        newXS("Agar::EventLoop", XS_Agar_EventLoop, file);
        newXS("Agar::DESTROY", XS_Agar_DESTROY, file);

    /* Initialisation Section */

#line 46 "Agar.xs"
boot_Agar__PixelFormat(aTHX_ cv);
boot_Agar__Surface(aTHX_ cv);
boot_Agar__Window(aTHX_ cv);

#line 284 "Agar.c"

    /* End of Initialisation Section */

    XSRETURN_YES;
}

