/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Window.xs. Do not edit this file, edit Window.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Window.xs"
/*
 * Copyright (c) 2008 Hypertriton, Inc. <http://hypertriton.com/>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <agar/core.h>
#include <agar/gui.h>
#include "perl_agar.h"

static const AP_FlagNames flagNames[] = {
	{ "modal",         AG_WINDOW_MODAL },
	{ "keepAbove",     AG_WINDOW_KEEPABOVE },
	{ "keepBelow",     AG_WINDOW_KEEPBELOW },
	{ "denyFocus",     AG_WINDOW_DENYFOCUS },
	{ "noTitle",       AG_WINDOW_NOTITLE },
	{ "noBorders",     AG_WINDOW_NOBORDERS },
	{ "noHResize",     AG_WINDOW_NOHRESIZE },
	{ "noVResize",     AG_WINDOW_NOVRESIZE },
	{ "noResize",      AG_WINDOW_NORESIZE },
	{ "noClose",       AG_WINDOW_NOCLOSE },
	{ "noMinimize",    AG_WINDOW_NOMINIMIZE },
	{ "noMaximize",    AG_WINDOW_NOMAXIMIZE },
	{ "noBackground",  AG_WINDOW_NOBACKGROUND },
	{ "noUpdateRect",  AG_WINDOW_NOUPDATERECT },
	{ "focusOnAttach", AG_WINDOW_FOCUSONATTACH },
	{ "hMaximize",     AG_WINDOW_HMAXIMIZE },
	{ "vMaximize",     AG_WINDOW_VMAXIMIZE },
	{ "plain",         AG_WINDOW_PLAIN },
	{ NULL,            0 }
};

#line 66 "Window.c"

XS(XS_Agar__Window_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Window_new)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: Agar::Window::new(package, ...)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
#line 64 "Window.xs"
	Uint flags = 0;
#line 78 "Window.c"
	Agar__Window	RETVAL;
#line 66 "Window.xs"
	if ((items == 2 && SvTYPE(SvRV(ST(1))) != SVt_PVHV) || items > 2) {
		Perl_croak("Usage: Agar::Window->new([{opts}])");
	}
	if (items == 2) {
		AP_MapHashToFlags(SvRV(ST(1)), flagNames, &flags);
	}
	RETVAL = AG_WindowNew(flags);
#line 88 "Window.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::Window", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__Window_newNamed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Window_newNamed)
{
    dXSARGS;
    if (items < 2)
	Perl_croak(aTHX_ "Usage: Agar::Window::newNamed(package, name, ...)");
    {
	const char *	package = (const char *)SvPV_nolen(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
#line 81 "Window.xs"
	Uint flags = 0;
#line 107 "Window.c"
	Agar__Window	RETVAL;
#line 83 "Window.xs"
	if ((items == 3 && SvTYPE(SvRV(ST(2))) != SVt_PVHV) || items > 3) {
		Perl_croak("Usage: Agar::Window->newNamed(name,[{opts}])");
	}
	if (items == 3) {
		AP_MapHashToFlags(SvRV(ST(2)), flagNames, &flags);
	}
	if ((RETVAL = AG_WindowNewNamed(flags, "%s", name)) == NULL) {
		XSRETURN_UNDEF;
	}
#line 119 "Window.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::Window", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__Window_caption); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Window_caption)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: Agar::Window::caption(win, ...)");
    {
	Agar__Window	win;
	SV *	RETVAL;

	if (sv_derived_from(ST(0), "Agar::Window")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    win = INT2PTR(Agar__Window,tmp);
	}
	else
	    Perl_croak(aTHX_ "win is not of type Agar::Window");
#line 99 "Window.xs"
	if (items > 1) {
		AG_WindowSetCaption(win, "%s", (char *)SvPV_nolen(ST(1)));
	}
	RETVAL = newSVpv(win->caption,0);
#line 148 "Window.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Agar__Window_icon); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Window_icon)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: Agar::Window::icon(win, ...)");
    {
	Agar__Window	win;
	Agar__Surface	RETVAL;

	if (sv_derived_from(ST(0), "Agar::Window")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    win = INT2PTR(Agar__Window,tmp);
	}
	else
	    Perl_croak(aTHX_ "win is not of type Agar::Window");
#line 110 "Window.xs"
	if (items > 1) {
		Agar__Surface s;
		if (sv_derived_from(ST(1), "Agar::Surface")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			s = INT2PTR(Agar__Surface,tmp);
		} else {
	    		Perl_croak(aTHX_ "icon is not of type Agar::Surface");
		}
		AG_WindowSetIcon(win, s);
	}
	RETVAL = AGWIDGET_SURFACE(win->icon,win->icon->surface);
#line 184 "Window.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Agar::Surface", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Agar__Window_show); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Window_show)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Agar::Window::show(win)");
    {
	Agar__Window	win;

	if (sv_derived_from(ST(0), "Agar::Window")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    win = INT2PTR(Agar__Window,tmp);
	}
	else
	    Perl_croak(aTHX_ "win is not of type Agar::Window");
#line 128 "Window.xs"
	AG_WindowShow(win);
#line 209 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Agar__Window_hide); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Window_hide)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Agar::Window::hide(win)");
    {
	Agar__Window	win;

	if (sv_derived_from(ST(0), "Agar::Window")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    win = INT2PTR(Agar__Window,tmp);
	}
	else
	    Perl_croak(aTHX_ "win is not of type Agar::Window");
#line 134 "Window.xs"
	AG_WindowHide(win);
#line 232 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Agar__Window_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Agar__Window_DESTROY)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Agar::Window::DESTROY(win)");
    {
	Agar__Window	win;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    win = INT2PTR(Agar__Window,tmp);
	}
	else
	    Perl_croak(aTHX_ "win is not a reference");
#line 140 "Window.xs"
	AG_ViewDetach(win);
#line 255 "Window.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Agar__Window); /* prototype to pass -Wmissing-prototypes */
XS(boot_Agar__Window)
{
    dXSARGS;
    char* file = __FILE__;

        newXSproto("Agar::Window::new", XS_Agar__Window_new, file, "$;@");
        newXSproto("Agar::Window::newNamed", XS_Agar__Window_newNamed, file, "$$;@");
        newXSproto("Agar::Window::caption", XS_Agar__Window_caption, file, "$;@");
        newXSproto("Agar::Window::icon", XS_Agar__Window_icon, file, "$;@");
        newXSproto("Agar::Window::show", XS_Agar__Window_show, file, "$");
        newXSproto("Agar::Window::hide", XS_Agar__Window_hide, file, "$");
        newXSproto("Agar::Window::DESTROY", XS_Agar__Window_DESTROY, file, "$");
    XSRETURN_YES;
}

