#	$Csoft: Makefile,v 1.1.1.1 2002/09/01 09:00:48 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

LIB=	monitor_tool
SRCS=	monitor_tool.c object_browser.c
OBJS=	monitor_tool.o object_browser.o

CFLAGS+=	${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/libfobj/Makefile.inc
