#	$Csoft: Makefile,v 1.2 2002/09/04 03:21:01 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

LIB=	monitor_tool
SRCS=	monitor_tool.c sprite_browser.c object_browser.c
OBJS=	monitor_tool.o sprite_browser.o object_browser.o

CFLAGS+=	${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/libfobj/Makefile.inc
