#	$Csoft: Makefile,v 1.4 2003/08/13 01:47:35 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

XCF=		props.xcf
DEN=		mapview.den
DEN_DIR=	engine/mapedit/mapview
DEN_NAME=	"Mapview property indicators"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2002, 2003 CubeSoft Communications, Inc."

include ${TOP}/mk/csoft.common.mk
include ${TOP}/mk/csoft.subdir.mk
include ${TOP}/dencomp/Makefile.inc
