#	$Csoft: Makefile,v 1.2 2003/06/06 02:18:04 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

DEN=		mapview.den
DEN_DIR=	engine/mapedit/mapview
DEN_NAME=	"Mapview property indicators"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2002, 2003 CubeSoft Communications, Inc."
XCF=		props.xcf

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/dencomp/Makefile.inc
