#	$Csoft: Makefile,v 1.3 2003/06/21 06:50:23 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

XCF=		props.xcf
DEN=		mapview.den
DEN_DIR=	engine/mapedit/mapview
DEN_NAME=	"Mapview property indicators"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2002, 2003 CubeSoft Communications, Inc."

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/dencomp/Makefile.inc
