#	$Csoft: Makefile,v 1.7 2005/07/24 05:29:53 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

XCF=	map-edition.xcf \
	object-editor.xcf \
	objects.xcf \
	vg.xcf \
	vg-snap.xcf \
	eda.xcf \
	rg.xcf \
	anim.xcf \
	symbols.xcf \
	arrow.xcf \
	window.xcf

DEN=		core-icons.den
DEN_NAME=	"Agar Core Icons"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2001, 2002, 2003, 2004, 2005 CubeSoft Communications, Inc"

include ${TOP}/mk/csoft.den.mk
