/* Agar icon reference file */
/* Generated by agarpaint 1.1 */

#include <agar/map/begin.h>
__BEGIN_DECLS
extern AG_StaticIcon mapIconStamp;
extern AG_StaticIcon mapIconEraser;
extern AG_StaticIcon mapIconNewView;
extern AG_StaticIcon mapIconResize;
extern AG_StaticIcon mapIconGrid;
extern AG_StaticIcon mapIconLayerEditor;
extern AG_StaticIcon mapIconSelectNode;
extern AG_StaticIcon mapIconSelectItem;
extern AG_StaticIcon mapIconMerge;
extern AG_StaticIcon mapIconFill;
extern AG_StaticIcon mapIconMirror;
extern AG_StaticIcon mapIconFlip;
extern AG_StaticIcon mapIconActor;
extern AG_StaticIcon mapIconInvert;
extern AG_StaticIcon mapIconSettings;
extern AG_StaticIcon mapIconWalkable;
extern AG_StaticIcon mapIconClimbable;
extern AG_StaticIcon mapIconJumpable;
extern AG_StaticIcon mapIconSlippery;
extern AG_StaticIcon mapIconOrigin;
__END_DECLS
#include <agar/map/close.h>
