/* Agar icon reference file */
/* Generated by agarpaint 1.1 */

#include <agar/map/begin.h>
__BEGIN_DECLS
extern AG_StaticIcon rgIconStamp;
extern AG_StaticIcon rgIconMagnifier;
extern AG_StaticIcon rgIconLayerEditor;
extern AG_StaticIcon rgIconMirror;
extern AG_StaticIcon rgIconFlip;
extern AG_StaticIcon rgIconInvert;
extern AG_StaticIcon rgIconHGrad;
extern AG_StaticIcon rgIconVGrad;
extern AG_StaticIcon rgIconCGrad;
extern AG_StaticIcon rgIconTiling;
extern AG_StaticIcon rgIconSketchProj;
extern AG_StaticIcon rgIconSketch;
extern AG_StaticIcon rgIconSketchAttach;
extern AG_StaticIcon rgIconPixmapResize;
extern AG_StaticIcon rgIconPixmapAttach;
extern AG_StaticIcon rgIconPolygon;
extern AG_StaticIcon rgIconExtrusion;
extern AG_StaticIcon rgIconRevolution;
extern AG_StaticIcon rgIconSwap;
extern AG_StaticIcon rgIconControls;
extern AG_StaticIcon rgIconPixmap;
extern AG_StaticIcon rgIconWalkable;
extern AG_StaticIcon rgIconClimbable;
extern AG_StaticIcon rgIconJumpable;
extern AG_StaticIcon rgIconSlippery;
extern AG_StaticIcon rgIconObject;
extern AG_StaticIcon rgIconMap_n0;
extern AG_StaticIcon rgIconDrawing;
extern AG_StaticIcon rgIconTileset;
extern AG_StaticIcon rgIconEdit;
extern AG_StaticIcon rgIconDuplicate;
extern AG_StaticIcon rgIconOrigin;
extern AG_StaticIcon rgIconGrid;
extern AG_StaticIcon rgIconPlay;
extern AG_StaticIcon rgIconPause;
extern AG_StaticIcon rgIconStop;
extern AG_StaticIcon rgIconRewind;
extern AG_StaticIcon rgIconForward;
extern AG_StaticIcon rgIconRewindFrame;
extern AG_StaticIcon rgIconForwardFrame;
extern AG_StaticIcon rgIconFill;
__END_DECLS
#include <agar/map/close.h>
