/* Agar icon reference file */
/* Generated by agarpaint 1.1 */

#include <agar/sg/begin.h>
__BEGIN_DECLS
extern AG_StaticIcon sgIconLighting;
extern AG_StaticIcon sgIconZBuffer;
extern AG_StaticIcon sgIconWireframe;
extern AG_StaticIcon sgIconVertices;
extern AG_StaticIcon sgIconFacet;
extern AG_StaticIcon sgIconFacetNormals;
extern AG_StaticIcon sgIconVertexNormals;
extern AG_StaticIcon sgIconCamera;
extern AG_StaticIcon sgIconTriedre;
extern AG_StaticIcon sgIconI;
extern AG_StaticIcon sgIconJ;
extern AG_StaticIcon sgIconK;
extern AG_StaticIcon sgIconNode;
extern AG_StaticIcon sgIconCgProgram;
extern AG_StaticIcon sgIconOrigin;
extern AG_StaticIcon sgIconLine;
extern AG_StaticIcon sgIconTriangle;
extern AG_StaticIcon sgIconCircle;
extern AG_StaticIcon sgIconBezierCurve;
extern AG_StaticIcon sgIconBlock;
extern AG_StaticIcon sgIconText;
__END_DECLS
#include <agar/sg/close.h>
