.\"
.\" Copyright (c) 2010-2019 Julien Nadeau Carriere <vedge@csoft.net>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd April 28, 2010
.Dt SG_POINT 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.6
.Sh NAME
.Nm SG_Point
.Nd Agar-SG point node
.Sh SYNOPSIS
.Bd -literal
#include <agar/core.h>
#include <agar/sg.h>
.Ed
.Sh DESCRIPTION
The
.Nm
node represents a reference point in space.
This is useful in feature-based modeling, or as construction geometry.
.Sh INHERITANCE HIERARCHY
.Xr AG_Object 3 ->
.Xr SG_Node 3 ->
.Xr SG_Geom 3 ->
.Nm .
.Sh INITIALIZATION
.nr nS 1
.Ft "SG_Point *"
.Fn SG_PointNew "SG_Node *parent" "const char *name" "const M_Vector3 *p"
.Pp
.Ft "void"
.Fn SG_PointSize "SG_Node *parent" "M_Real size"
.Pp
.Ft "void"
.Fn SG_PointColor "SG_Node *parent" "M_Color color"
.Pp
.nr nS 0
The
.Fn SG_PointNew
function creates a new point at the origin of the parent node.
If the
.Fa p
argument is non-NULL, the point is translated to the specified coordinates.
.Pp
The functions
.Fn SG_PointSize
and
.Fn SG_PointColor
specify a point size in pixels, and a color, respectively, which will be used
in graphically rendering the point node.
.Sh STRUCTURE DATA
For the
.Nm
object:
.Bl -tag -width "M_Color color "
.It Ft float size
Size factor used in graphically rendering the point.
.It Ft M_Color color
Color used in graphically rendering the point.
.El
.Sh SEE ALSO
.Xr M_Color 3 ,
.Xr M_Real 3 ,
.Xr M_Vector 3 ,
.Xr SG 3 ,
.Xr SG_Geom 3 ,
.Xr SG_Intro 3 ,
.Xr SG_Node 3 ,
.Xr SG_Plane 3
.Sh HISTORY
The
.Nm
node class first appeared in Agar 1.6.0.
