.\"
.\" Copyright (c) 2006-2007 Hypertriton, Inc. <http://hypertriton.com/>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd October 18, 2006
.Dt SK 3
.Os
.ds vT Agar-SG API Reference
.ds oS Agar-SG 1.0
.Sh NAME
.Nm SK
.Nd agar 2D sketch object
.Sh SYNOPSIS
.Bd -literal
#include <agar/sg/sk.h>
.Ed
.Sh DESCRIPTION
The Agar
.Nm
object implements a general-purpose 2D sketching engine with a programming
interface similar to
.Xr SK 3 .
Sketches define a set of elements and a set of relations between those
elements.
.Pp
Elements are organized in a tree and the same structure is used to described
group and leaf nodes.
Each element in the graph is associated with a transformation matrix.
The major sketch elements are points, lines and arcs, but other types can
be added at runtime.
.Pp
Relations represent geometric constraints affecting points, lines, circles,
segments and arcs.
The following constraints are implemented:
.Pp
.Bl -bullet -compact
.It
Parallelism
.It
Incidence
.It
Perpendicularity
.It
Tangency
.It
Concentricity
.It
Colinearity
.It
Explicit distance
.It
Explicit angle
.El
.Pp
.Sh INHERITANCE HIERARCHY
.Pp
.Xr AG_Object 3 ->
.Nm .
.Sh INITIALIZATION
.nr nS 1
.Ft "SK *"
.Fn SK_New "void *parent" "const char *name"
.Pp
.Ft "void"
.Fn SK_Init "void *parent" "const char *name"
.Pp
.nr nS 0
.Pp
The
.Fn SK_New
function allocates, initializes, and attaches a
.Nm
object.
.Fn SK_Init
initializes a
.Nm
structure.
.Sh NODE MANIPULATION
.nr nS 1
.Ft "void"
.Fn SK_RegisterClass "SK_NodeOps *ops"
.Pp
.Ft "void"
.Fn SK_NodeInit "void *node" "const SK_NodeOps *ops" "Uint flags"
.Pp
.Ft "void *"
.Fn SK_NodeAdd "void *pnode" "const SK_NodeOps *ops" "Uint flags"
.Pp
.Ft "void"
.Fn SK_NodeAttach "void *pnode" "void *node"
.Pp
.Ft "void"
.Fn SK_NodeDetach "void *pnode" "void *node"
.Pp
.nr nS 0
The
.Fn SK_RegisterClass
function registers a new node class, described by the given
.Ft SK_NodeOps
structure.
.Pp
The
.Fn SK_NodeInit
function initializes the given
.Ft SK_Node
structure.
It is usually invoked from node constructor functions.
.Fa ops
points to the
.Ft SK_NodeOps
structure which contains class information.
The
.Fa flags
argument should be 0.
The
.Fn SK_NodeAdd
variant also allocates, initializes and attaches the node to a parent node.
.Pp
The
.Fn SK_NodeAttach
and
.Fn SK_NodeDetach
functions attach/detach a node to/from a given parent.
.Pp
.Sh NODE TRANSFORMATIONS
.Pp
These functions multiply a node's transformation matrix
.Va T
with a translation, scaling or rotation matrix.
They are only aliases for
.Ft SG_Matrix *
functions, except that they accept a pointer to a node instead of a matrix.
.Pp
.nr nS 0
.Ft "void"
.Fn SK_Translatev "SK_Node *node" "SG_Vector v"
.Pp
.Ft "void"
.Fn SK_Translate2 "SK_Node *node" "SG_Real x" "SG_Real y"
.Pp
.Ft "void"
.Fn SK_Scalev "SK_Node *node" "SG_Vector v"
.Pp
.Ft "void"
.Fn SK_Rotatev "SK_Node *node" "SG_Real theta" "SG_Vector axis"
.Pp
.Ft "void"
.Fn SK_Rotatevd "SK_Node *node" "SG_Real degrees" "SG_Vector axis"
.Pp
.Ft "void"
.Fn SK_GetNodeTransform "void *node" "SG_Matrix *T"
.Pp
.nr nS 1
.Pp
The
.Fn SK_Translate*
functions multiply
.Va T
by a 2D translation matrix.
.Pp
The
.Fn SK_Scalev
function multiplies
.Va T
by a 2D scaling matrix.
.Pp
.Fn SK_Rotate*
multiply
.Va T
by a 2D rotation matrix.
Angles are given in radians, except for
.Fn SK_Rotate*d
variants which accept angular arguments in degrees.
.Pp
.Fn SK_Rotatev
generates a rotation of
.Fa theta
radians around
.Fa axis .
The
.Fn SK_Rotate*
variants with the "d" suffix accept angles in degrees instead of radians.
.Pp
The
.Fn SK_GetNodeTransform
function returns a matrix which is the product of the transformation
matrices of the given node and all of its parents.
.Pp
.Sh SEE ALSO
.Xr SK_View 3 ,
.Xr SG_Matrix 3 ,
.Xr SG_Vector 3
.Sh HISTORY
The
.Nm
object first appeared in Agar-SG 1.0.
