# $Csoft: Makefile,v 1.1 2004/01/23 06:27:00 vedge Exp $

TOP=	../..

DOC=		agar-devguide.ps
OUTPUT=		ps
MACROS=		-me
DOCSRC=		00.Macros.me \
		00.Intro.me \
		00.Chapters.me \
		01.Overview.me \
		02.Initialization.me \
		03.Object.me \
		04.Den.me

DOCSRC+=	A.Code-listings.me \
		B.List-of-figures.me \
		00.Contents.me

include ${TOP}/mk/csoft.doc.mk
