TOP=	..
include ${TOP}/Makefile.config

PROG=		agar-map-config
PROG_TYPE=	"CLI"
PROG_GUID=	"0a155c34-8bb8-4f3a-a529-2dc91494d731"

SRCS=	agar-map-config.c
CFLAGS+=-I..

include ${TOP}/mk/build.prog.mk
