.\" Copyright (c) 2002-2012 Hypertriton, Inc. <http://hypertriton.com/>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd September 11, 2002
.Dt AG_SCROLLBAR 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm AG_Scrollbar
.Nd agar scroll bar widget
.Sh SYNOPSIS
.Bd -literal
#include <agar/core.h>
#include <agar/gui.h>
.Ed
.Sh DESCRIPTION
.\" IMAGE(http://libagar.org/widgets/AG_Scrollbar.png, "An AG_Scrollbar")
The
.Nm
widget provides a basic panning control.
.Nm
is almost always used as part of a widget's implementation, where the user
should be able to scroll over some partially visible graphics.
The scrollbar's range and value parameters are specified by integer or
floating-point bindings.
.Pp
For example, in
.Xr AG_Textbox 3 ,
the
.Va max
binding would be tied to the total line count, and
.Va value
to the index of the first line to display.
The
.Va visible
binding would be tied to the number of lines that can be displayed on-screen
(see
.Sx BINDINGS ) .
.Pp
NOTE: This widget is meant only as a panning control.
For general edition of numerical values, the simpler
.Xr AG_Slider 3
or
.Xr AG_Numerical 3
widgets should be used.
.Sh INHERITANCE HIERARCHY
.Xr AG_Object 3 ->
.Xr AG_Widget 3 ->
.Nm .
.Sh INTERFACE
.nr nS 1
.Ft "AG_Scrollbar *"
.Fn AG_ScrollbarNew "AG_Widget *parent" "enum ag_scrollbar_type type" "Uint flags"
.Pp
.Ft void
.Fn AG_ScrollbarSizeHint "AG_Scrollbar *scrollbar" "int length"
.Pp
.Ft void
.Fn AG_ScrollbarSetControlLength "AG_Scrollbar *scrollbar" "int length"
.Pp
.Ft void
.Fn AG_ScrollbarSetWidth "int width"
.Pp
.Ft int
.Fn AG_ScrollbarWidth "void"
.Pp
.Ft int
.Fn AG_ScrollbarVisible "AG_Scrollbar *scrollbar"
.Pp
.Ft void
.Fn AG_ScrollbarSetIncFn "AG_Scrollbar *scrollbar" "AG_EventFn fn" "const char *fmt" "..."
.Pp
.Ft void
.Fn AG_ScrollbarSetDecFn "AG_Scrollbar *scrollbar" "AG_EventFn fn" "const char *fmt" "..."
.Pp
.nr nS 0
The
.Fn AG_ScrollbarNew
function allocates, initializes, and attaches a new
.Nm
widget.
The
.Fa type
argument should be either
.Dv AG_SCROLLBAR_HORIZ
to create a horizontal scrollbar, or
.Dv AG_SCROLLBAR_VERT
to create a vertical scrollbar.
Acceptable
.Fa flags
include:
.Bl -tag -width "AG_SCROLLBAR_NOAUTOHIDE "
.It AG_SCROLLBAR_NOAUTOHIDE
Always display the scrollbar.
By default, the scrollbar is automatically hidden if the values of
.Va min ,
.Va max
and
.Va visible
do not allow any room for scrolling.
.It AG_SCROLLBAR_EXCL
Advise that no external changes to the
.Va value ,
.Va min ,
.Va max
and
.Va visible
bindings are expected.
By default, the binding values are periodically checked and the scrollbar is
redrawn if a change is detected.
Note that this setting only influences redraw -- external changes to the
binding values are handled safely regardless.
.It AG_SCROLLBAR_HFILL
Expand horizontally in parent (equivalent to invoking
.Xr AG_ExpandHoriz 3 ) .
This flag is only sensible with horizontal scrollbars, and renders the use of
.Fn AG_ScrollbarSizeHint
unnecessary.
.It AG_SCROLLBAR_VFILL
Expand vertically in parent (equivalent to invoking
.Xr AG_ExpandVert 3 ) .
This flag is only sensible with vertical scrollbars, and renders the use of
.Fn AG_ScrollbarSizeHint
unnecessary.
.It AG_SCROLLBAR_EXPAND
Shorthand for
.Dv AG_SCROLLBAR_HFILL|AG_SCROLLBAR_VFILL .
.It AG_SCROLLBAR_TEXT
Display the minimum, current and maximum values in text.
This option is primarily useful for debugging.
.El
.Pp
The
.Fn AG_ScrollbarSizeHint
function specifies a default, preferred scrollbar length in pixels.
This is rarely used; in practice, scrollbars almost always use
.Dv AG_SCROLLBAR_HFILL
or
.Dv AG_SCROLLBAR_VFILL .
.Pp
The
.Fn AG_ScrollbarSetControlLength
function sets the size of the scrolling control in pixels.
Note that this parameter is ignored if the
.Va visible
binding is set to a non-zero value (in which case, the optimal size of the
control is determined automatically).
.Pp
.Fn AG_ScrollbarSetWidth
configures the width (i.e., thickness) of the scrollbar.
.Fn AG_ScrollbarWidth
returns the effective width of a scrollbar in pixels.
.Pp
The
.Fn AG_ScrollbarVisible
function returns 1 if the current range is such that the scrollbar is useful
to display, otherwise it returns 0.
.Pp
The
.Fn AG_ScrollbarSetDecFn
and
.Fn AG_ScrollbarSetIncFn
functions configure a callback routine that will be invoked when the user
presses the decrement (up/left) button and the increment (down/right) buttons.
A single
.Ft int
argument is passed to the callback (1 = pressed, 0 = released).
.Sh BINDINGS
The
.Nm
widget provides the following bindings:
.Pp
.Bl -tag -compact -width "long double *{value,min,max,inc,visible} "
.It Va float *{value,min,max,inc,visible}
Single precision number
.It Va double *{value,min,max,inc,visible}
Double precision number
.It Va long double *{value,min,max,inc,visible}
Quad precision number
.It Va int *{value,min,max,inc,visible}
Natural integer
.It Va Uint *{value,min,max,inc,visible}
Unsigned integer
.It Va [SU]int8 *{value,min,max,inc,visible}
Fixed 8-bit integer
.It Va [SU]int16 *{value,min,max,inc,visible}
Fixed 16-bit integer
.It Va [SU]int32 *{value,min,max,inc,visible}
Fixed 32-bit integer
.It Va [SU]int64 *{value,min,max,inc,visible}
Fixed 64-bit integer
.El
.Pp
The scrollbar is positioned to represent
.Va value
inside of a given range defined by
.Va min
and
.Va max .
The range defaults to 0.0 to 1.0 (for floating-point values),
or 0 to the maximum representible value (for integer values).
.Pp
Thea optional
.Va inc
binding specifies the increment effected by the buttons, or keyboard.
If not specified, it defaults to 0.1 (for floating-point values), or 1 (for
integer values).
.Pp
The optional
.Va visible
binding may be set to indicate the portion of the total range which is
currently visible on-screen.
If this is a non-zero value, then the size of the scrolling control button
will be set automatically.
.Pp
Note that the
.Va min ,
.Va max ,
.Va inc
and
.Va visible
bindings must share the same type as
.Va value .
The 64-bit types are only available if
.Dv AG_HAVE_64BIT
is set, and
.Ft long double
is only available if
.Dv AG_HAVE_LONG_DOUBLE
is set.
.Sh EVENTS
The
.Nm
widget generates the following events:
.Pp
.Bl -tag -compact -width 2n
.It Fn scrollbar-changed "void"
The scrollbar's value has changed.
.It Fn scrollbar-drag-begin "void"
User is starting to drag the scrollbar.
.It Fn scrollbar-drag-end "void"
User is done dragging the scrollbar.
.El
.Sh STRUCTURE DATA
For the
.Ft AG_Scrollbar
object:
.Pp
.Bl -tag -compact -width "int visible "
.It Ft int width
Scrollbar width in pixels.
.It Ft int hArrow
Size of "arrow" icons in pixels.
.El
.Sh SEE ALSO
.Xr AG_Intro 3 ,
.Xr AG_Scrollview 3 ,
.Xr AG_Slider 3 ,
.Xr AG_Widget 3 ,
.Xr AG_Window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.0.
The
.Dv AUTOSIZE
option was introduced in Agar 1.4.0.
The
.Va inc
binding was introduced in Agar 1.5.0.
