.\"	$Csoft: box.3,v 1.8 2005/03/09 06:39:20 vedge Exp $
.\"
.\" Copyright (c) 2002, 2003, 2004, 2005 CubeSoft Communications, Inc.
.\" <http://www.csoft.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd June 10, 2003
.Dt BOX 3
.Os
.ds vT Agar API Reference
.ds oS Agar 1.0
.Sh NAME
.Nm box
.Nd agar container widget
.Sh SYNOPSIS
.Bd -literal
#include <engine/widget/box.h>
.Ed
.Sh DESCRIPTION
The
.Nm
widget packs its children horizontally or vertically.
.Sh INHERITANCE HIERARCHY
.Pp
.Xr AG_Object 3 ->
.Xr widget 3 ->
.Nm .
.Sh INITIALIZATION
.nr nS 1
.Ft "AG_Box *"
.Fn AG_BoxNew "void *parent" "enum ag_box_type type" "int flags"
.Pp
.Ft "void"
.Fn AG_BoxInit "AG_Box *box" "enum ag_box_type type" "int flags"
.Pp
.Ft void
.Fn AG_BoxSetHomogenous "AG_Box *box" "int homogenous"
.Pp
.Ft void
.Fn AG_BoxSetPadding "AG_Box *box" "int padding"
.Pp
.Ft void
.Fn AG_BoxSetSpacing "AG_Box *box" "int spacing"
.Pp
.Ft void
.Fn AG_BoxSetDepth "AG_Box *box" "int depth"
.nr nS 0
.Pp
The
.Fn AG_BoxNew
function allocates, initializes, and attaches a
.Nm
widget.
.Fn AG_BoxInit
initializes a
.Nm
widget.
.Fa type
defines whether child widgets are packed horizontally:
.Bd -literal
enum ag_box_type {
	AG_BOX_HORIZ,
	AG_BOX_VERT
};
.Ed
.Pp
Acceptable
.Fa flags
include:
.Bd -literal
#define AG_BOX_HOMOGENOUS  0x01    /* Divide space evenly */
#define AG_BOX_WFILL       0x02    /* Fill container's remaining width */
#define AG_BOX_HFILL       0x04    /* Fill container's remaining height */
#define AG_BOX_FRAME	0x08	/* Display a frame */
.Ed
.Pp
The
.Fn AG_BoxSetHomogenous
function sets/clears the
.Dv AG_BOX_HOMOGENOUS
flag, which controls whether available space is divided evenly between widgets.
.Pp
The
.Fn AG_BoxSetPadding
function sets the padding around the group of child widgets to
.Fa padding
pixels.
.Fn AG_BoxSetSpacing
sets the spacing between individual child widgets to
.Fa spacing
pixels.
.Pp
Assuming that the
.Dv AG_BOX_FRAME
flag was given,
.Fn AG_BoxSetDepth
sets the depth of the frame.
.Sh EVENTS
The
.Nm
widget neither reacts to nor generates any event.
.Sh SEE ALSO
.Xr agar 3 ,
.Xr widget 3 ,
.Xr window 3
.Sh HISTORY
The
.Nm
widget first appeared in Agar 1.0.
