/* Agar icon reference file */
/* Generated by agarpaint 1.1 */

#include <agar/gui/iconmgr.h>
#include <agar/gui/begin.h>
__BEGIN_DECLS
extern AG_StaticIcon agIconLeftButton;
extern AG_StaticIcon agIconMidButton;
extern AG_StaticIcon agIconRightButton;
extern AG_StaticIcon agIconCtrlKey;
extern AG_StaticIcon agIconLoad;
extern AG_StaticIcon agIconSave;
extern AG_StaticIcon agIconUp;
extern AG_StaticIcon agIconDown;
extern AG_StaticIcon agIconTrash;
extern AG_StaticIcon agIconClose;
extern AG_StaticIcon agIconDoc;
extern AG_StaticIcon agIconSymLink;
extern AG_StaticIcon agIconDirectory;
extern AG_StaticIcon agIconSmallArrowRight;
extern AG_StaticIcon agIconWinClose;
extern AG_StaticIcon agIconWinMinimize;
extern AG_StaticIcon agIconWinMaximize;
extern AG_StaticIcon agIconMagnifier;
extern AG_StaticIcon agIconGear;
extern AG_StaticIcon agIconDocImport;
extern AG_StaticIcon agIconWindow;
__END_DECLS
#include <agar/gui/close.h>
