#	$Csoft: Makefile,v 1.7 2004/04/22 01:52:22 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

XCF=		props.xcf
DEN=		pixmaps.den
DEN_DIR=	engine/map/pixmaps
DEN_NAME=	"Agar level editor pixmaps"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2002, 2003, 2004, 2005 CubeSoft Communications, Inc."

DENCOMP=${TOP}/dencomp/dencomp
include ${TOP}/mk/csoft.den.mk
