#	$Csoft: Makefile,v 1.2 2003/08/13 01:47:35 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

LIB=		error
LIB_SHARED=	Yes
LIB_STATIC=	Yes
SRCS=		error.c

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
