#	$Csoft: Makefile,v 1.12 2004/11/25 02:49:01 vedge Exp $

TOP=	../..
include ${TOP}/Makefile.config

LIB=		bg
LIB_SHARED=	Yes
LIB_STATIC=	No

SRCS=	tileset.c
#MAN3=	vg.3

CFLAGS+=${SDL_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/mk/csoft.man.mk
