#	$Csoft: Makefile,v 1.6 2004/02/29 17:37:40 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

XCF=		props.xcf
DEN=		pixmaps.den
DEN_DIR=	engine/mapedit/mapview
DEN_NAME=	"Agar level editor pixmaps"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2002, 2003, 2004 CubeSoft Communications, Inc."

DENCOMP=${TOP}/dencomp/dencomp
include ${TOP}/mk/csoft.den.mk
