#	$Csoft: Makefile,v 1.1 2003/05/07 12:17:00 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

FOBJ=	mapview.fob
FOBDIR=	/engine/mapedit/mapview
FOFFS=	mapview_offs.h
XCF=	props.xcf

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/libfobj/Makefile.inc
