#	$Csoft: Makefile,v 1.40 2003/03/10 05:49:10 vedge Exp $

TOP=	../../..
include ${TOP}/Makefile.config

FOBJ=	mapview.fob
FOFFS=	mapview_offs.h
XCF=	props.xcf

include ${TOP}/mk/csoft.lib.mk
include ${TOP}/libfobj/Makefile.inc
